# Generated by Django 5.2.5 on 2026-04-24 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("baseinfo", "0002_initial"),
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="baseinfo.owner",
                verbose_name="所属货主",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="locations.warehouse",
                verbose_name="所属大仓",
            ),
        ),
        migrations.AddField(
            model_name="systemlog",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AddField(
            model_name="systemlog",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_deleted",
                to=settings.AUTH_USER_MODEL,
                verbose_name="删除人",
            ),
        ),
        migrations.AddField(
            model_name="systemlog",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="system_logs",
                to="baseinfo.owner",
                verbose_name="货主",
            ),
        ),
        migrations.AddField(
            model_name="systemlog",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="更新人",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["owner", "username"], name="idx_user_owner_username"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["warehouse"], name="idx_user_warehouse"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["created_at"], name="idx_user_created_at"),
        ),
        migrations.AddIndex(
            model_name="systemlog",
            index=models.Index(
                fields=["occurred_at", "username", "log_type"],
                name="idx_log_time_user_type",
            ),
        ),
        migrations.AddIndex(
            model_name="systemlog",
            index=models.Index(fields=["module"], name="idx_log_module"),
        ),
        migrations.AddIndex(
            model_name="systemlog",
            index=models.Index(
                fields=["owner", "occurred_at"], name="idx_log_owner_time"
            ),
        ),
    ]
