# Generated by Django 5.2.5 on 2026-07-17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
        ("baseinfo", "0002_initial"),
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserRoleScope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("warehouse_operator", "仓库操作员"),
                            ("warehouse_manager", "仓库管理员"),
                            ("warehouse_boss", "仓库老板"),
                            ("owner_manager", "货主管理员"),
                            ("owner_salesperson", "货主业务员"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="角色",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True, verbose_name="启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_role_scopes",
                        to="baseinfo.owner",
                        verbose_name="货主范围",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_scopes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_role_scopes",
                        to="locations.warehouse",
                        verbose_name="仓库范围",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户角色范围",
                "verbose_name_plural": "用户角色范围",
                "ordering": (
                    "user_id",
                    "role",
                    "warehouse_id",
                    "owner_id",
                    "id",
                ),
                "permissions": [
                    ("access_warehouse_operations", "可执行仓库现场作业"),
                    ("receive_without_order", "可执行无订单收货"),
                    ("access_warehouse_management", "可管理仓库作业"),
                    ("view_warehouse_reports", "可查看仓库运营报表"),
                    ("view_warehouse_boss_dashboard", "可查看仓库老板经营看板"),
                    ("view_warehouse_financials", "可查看仓库经营财务数据"),
                    ("access_owner_management", "可管理货主订单"),
                    ("access_owner_sales", "可执行货主业务"),
                    ("view_owner_reports", "可查看货主运营报表"),
                    ("view_owner_financials", "可查看货主财务数据"),
                    ("export_operational_reports", "可导出运营报表"),
                ],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="idx_user_role_scope_active",
                    ),
                    models.Index(
                        fields=["role", "is_active"],
                        name="idx_role_scope_active",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("owner__isnull", True),
                                (
                                    "role__in",
                                    (
                                        "warehouse_operator",
                                        "warehouse_manager",
                                        "warehouse_boss",
                                    ),
                                ),
                                ("warehouse__isnull", False),
                            ),
                            models.Q(
                                ("owner__isnull", False),
                                (
                                    "role__in",
                                    ("owner_manager", "owner_salesperson"),
                                ),
                                ("warehouse__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="ck_user_role_scope_target",
                    ),
                    models.UniqueConstraint(
                        fields=("user", "role", "warehouse"),
                        name="uq_user_role_warehouse_scope",
                    ),
                    models.UniqueConstraint(
                        fields=("user", "role", "owner"),
                        name="uq_user_role_owner_scope",
                    ),
                ],
            },
        ),
    ]
