# Generated by Django 5.2.5 on 2026-04-24 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("baseinfo", "0001_initial"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="已删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用状态"),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="仓库编号"
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="仓库名称")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "仓库",
                "verbose_name_plural": "仓库",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Subwarehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="已删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用状态"),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="仓库编号"
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="仓库名称")),
                (
                    "floor_no",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=1, verbose_name="楼层"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subwarehouse",
                        to="locations.warehouse",
                        verbose_name="所属仓库",
                    ),
                ),
            ],
            options={
                "verbose_name": "仓库",
                "verbose_name_plural": "仓库",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="已删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用状态"),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "zone_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "拣选区"),
                            (2, "存储区"),
                            (3, "收货区"),
                            (4, "发运区"),
                            (5, "退货区"),
                            (6, "整件区"),
                            (7, "拆零区"),
                            (8, "破损区"),
                            (9, "其他"),
                        ],
                        db_index=True,
                        default=1,
                        verbose_name="区域类型",
                    ),
                ),
                ("code", models.CharField(max_length=60, verbose_name="储位编码")),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="储位名称"
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="储位条码"
                    ),
                ),
                (
                    "max_volume_m3",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        verbose_name="最大体积(m³)",
                    ),
                ),
                (
                    "max_weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="最大承重(kg)",
                    ),
                ),
                (
                    "is_disabled",
                    models.BooleanField(default=False, verbose_name="禁用"),
                ),
                ("is_frozen", models.BooleanField(default=False, verbose_name="冻结")),
                (
                    "rack_code",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="货架编码"
                    ),
                ),
                (
                    "rack_level_code",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="货架层编码"
                    ),
                ),
                (
                    "level_code",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="层号"
                    ),
                ),
                (
                    "col_no",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="列号"
                    ),
                ),
                (
                    "slot_no",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="位号"
                    ),
                ),
                (
                    "batch_guide",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="批量设置指引",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "product_categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="locations",
                        to="products.productcategory",
                        verbose_name="存放商品类别",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
                (
                    "subwarehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="locations",
                        to="locations.subwarehouse",
                        verbose_name="所属仓",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="locations",
                        to="locations.warehouse",
                        verbose_name="所属仓库",
                    ),
                ),
            ],
            options={
                "verbose_name": "储位",
                "verbose_name_plural": "储位管理",
            },
        ),
        migrations.CreateModel(
            name="Container",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="已删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用状态"),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("PRIVATE", "私有（按货主）"),
                            ("PUBLIC", "公共（仓库）"),
                        ],
                        default="PRIVATE",
                        max_length=16,
                        verbose_name="范围",
                    ),
                ),
                (
                    "container_no",
                    models.CharField(max_length=60, verbose_name="容器号"),
                ),
                (
                    "container_type",
                    models.CharField(
                        choices=[
                            ("TOTE", "料箱"),
                            ("CARTON", "纸箱"),
                            ("PALLET", "托盘"),
                        ],
                        default="CARTON",
                        max_length=10,
                        verbose_name="容器类型",
                    ),
                ),
                (
                    "length_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="长(cm)",
                    ),
                ),
                (
                    "width_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="宽(cm)",
                    ),
                ),
                (
                    "height_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="高(cm)",
                    ),
                ),
                (
                    "tare_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="皮重(kg)",
                    ),
                ),
                (
                    "max_gross_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        verbose_name="最大毛重(kg)",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="baseinfo.owner",
                        verbose_name="货主",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="locations.container",
                        verbose_name="上级容器",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="locations.location",
                        verbose_name="当前位置",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="locations.warehouse",
                        verbose_name="仓库",
                    ),
                ),
            ],
            options={
                "verbose_name": "容器",
                "verbose_name_plural": "容器",
            },
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["subwarehouse", "zone_type"], name="ix_loc_sw_zt"
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["subwarehouse", "is_disabled"], name="ix_loc_sw_dis"
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["subwarehouse", "is_frozen"], name="ix_loc_sw_fro"
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(fields=["code"], name="ix_loc_code"),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(fields=["barcode"], name="ix_loc_barcode"),
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(
                fields=("warehouse", "code"), name="ux_loc_wh_code"
            ),
        ),
        migrations.AddIndex(
            model_name="container",
            index=models.Index(fields=["owner", "warehouse"], name="ix_cont_own_wh"),
        ),
        migrations.AddIndex(
            model_name="container",
            index=models.Index(fields=["parent"], name="ix_cont_parent"),
        ),
        migrations.AddConstraint(
            model_name="container",
            constraint=models.UniqueConstraint(
                fields=("warehouse", "container_no"), name="ux_container_wh_no"
            ),
        ),
    ]
