# Generated by Django 5.2.5 on 2025-10-18 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="zone",
        ),
    ]
