# Generated by Django 5.2.5 on 2026-04-24 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subwarehouse",
            options={
                "ordering": ["code"],
                "verbose_name": "子仓库",
                "verbose_name_plural": "子仓库",
            },
        ),
    ]
