# Generated by Django 5.2.5 on 2026-06-23 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_alter_subwarehouse_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subwarehouse",
            options={
                "ordering": ["code"],
                "verbose_name": "子仓",
                "verbose_name_plural": "子仓",
            },
        ),
        migrations.AlterField(
            model_name="location",
            name="subwarehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="locations",
                to="locations.subwarehouse",
                verbose_name="所属子仓",
            ),
        ),
        migrations.AlterField(
            model_name="subwarehouse",
            name="code",
            field=models.CharField(max_length=10, unique=True, verbose_name="子仓编号"),
        ),
        migrations.AlterField(
            model_name="subwarehouse",
            name="name",
            field=models.CharField(max_length=30, verbose_name="子仓名称"),
        ),
    ]
