# Generated by Django 5.2.5 on 2025-10-19 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_remove_location_zone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subwarehouse",
            name="warehouse",
            field=models.ForeignKey(
                default=1,
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subwarehouse",
                to="locations.warehouse",
                verbose_name="所属仓库",
            ),
        ),
    ]
