# Generated by Django 5.2.5 on 2025-10-19 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0003_alter_subwarehouse_warehouse"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Zone",
        ),
    ]
