# Generated by Django 5.2.5 on 2025-10-19 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0004_delete_zone"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="location",
            name="locations_l_subware_7ecbf5_idx",
        ),
        migrations.AlterField(
            model_name="container",
            name="warehouse",
            field=models.ForeignKey(
                default=1,
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                to="locations.warehouse",
                verbose_name="仓库",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="warehouse",
            field=models.ForeignKey(
                default=1,
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="locations",
                to="locations.warehouse",
                verbose_name="所属仓库",
            ),
        ),
    ]
