# Generated by Django 5.2.5 on 2025-10-19 02:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0005_remove_location_locations_l_subware_7ecbf5_idx_and_more"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="location",
            name="locations_l_zone_ty_be2147_idx",
        ),
        migrations.RemoveIndex(
            model_name="location",
            name="locations_l_warehou_901c92_idx",
        ),
        migrations.RemoveIndex(
            model_name="location",
            name="locations_l_warehou_bf556d_idx",
        ),
        migrations.RemoveIndex(
            model_name="location",
            name="locations_l_warehou_9999ea_idx",
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["subwarehouse", "zone_type"], name="ix_loc_sw_zt"
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["subwarehouse", "is_disabled"], name="ix_loc_sw_dis"
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["subwarehouse", "is_frozen"], name="ix_loc_sw_fro"
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(fields=["code"], name="ix_loc_code"),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(fields=["barcode"], name="ix_loc_barcode"),
        ),
    ]
