# Generated by Django 5.2.5 on 2025-10-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0006_remove_location_locations_l_zone_ty_be2147_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="level_code",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="层号"
            ),
        ),
    ]
