# Generated by Django 5.2.5 on 2026-03-29 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('tasking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskscanlog',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.warehouse', verbose_name='仓库'),
        ),
        migrations.AlterField(
            model_name='wmstask',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='locations.warehouse', verbose_name='仓库'),
        ),
    ]
