# Generated by Django 5.2.5 on 2025-10-19 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0006_remove_location_locations_l_zone_ty_be2147_idx_and_more"),
        ("tasking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskscanlog",
            name="warehouse",
            field=models.ForeignKey(
                default=1,
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                to="locations.warehouse",
                verbose_name="仓库",
            ),
        ),
        migrations.AlterField(
            model_name="wmstask",
            name="warehouse",
            field=models.ForeignKey(
                default=1,
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tasks",
                to="locations.warehouse",
                verbose_name="仓库",
            ),
        ),
    ]
