# Generated by Django 5.2.5 on 2025-11-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasking", "0002_alter_taskscanlog_warehouse_alter_wmstask_warehouse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wmstask",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("RECEIVE", "收货"),
                    ("PUTAWAY", "上架"),
                    ("PICK", "拣货"),
                    ("REVIEW", "复核"),
                    ("PACK", "打包"),
                    ("LOAD", "装车"),
                    ("DISPATCH", "发运"),
                    ("REPLEN", "补货"),
                    ("RELOC", "移位"),
                    ("COUNT", "盘点"),
                    ("OTHER", "其他"),
                    ("ADJUST", "调整"),
                ],
                max_length=12,
                verbose_name="任务类型",
            ),
        ),
    ]
