# Generated by Django 5.2.5 on 2025-11-08 12:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseinfo", "0007_alter_supplier_code"),
        ("locations", "0007_alter_location_level_code"),
        ("tasking", "0003_alter_wmstask_task_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="wmstask",
            name="ck_task_type_valid",
        ),
        migrations.AddConstraint(
            model_name="wmstask",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "task_type__in",
                        [
                            "RECEIVE",
                            "PUTAWAY",
                            "PICK",
                            "REVIEW",
                            "PACK",
                            "LOAD",
                            "DISPATCH",
                            "REPLEN",
                            "RELOC",
                            "COUNT",
                            "OTHER",
                            "ADJUST",
                        ],
                    )
                ),
                name="ck_task_type_valid",
            ),
        ),
    ]
