# Generated by Django 5.2.5 on 2025-11-29 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasking", "0004_remove_wmstask_ck_task_type_valid_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="wmstask",
            name="picked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks_picked_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="拣货人",
            ),
        ),
    ]
