# Generated by Django 5.2.5 on 2026-02-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasking", "0005_wmstask_picked_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wmstaskline",
            name="status",
            field=models.CharField(
                choices=[
                    ("RESERVED", "冻结预订"),
                    ("DRAFT", "草稿"),
                    ("READY", "待发布"),
                    ("RELEASED", "已发布"),
                    ("IN_PROGRESS", "执行中"),
                    ("COMPLETED", "已完成"),
                    ("CANCELLED", "已取消"),
                ],
                db_index=True,
                default="DRAFT",
                max_length=16,
                verbose_name="状态",
            ),
        ),
    ]
