# Generated by Django 5.2.5 on 2026-04-24 20:40

import datetime
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OrderLineSourceLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "src_id",
                    models.BigIntegerField(db_index=True, verbose_name="来源主键"),
                ),
                (
                    "plan_qty_base",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=14,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="计划数量(基本)",
                    ),
                ),
                (
                    "posted_qty_base",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="已过账数量(基本)",
                    ),
                ),
                (
                    "lot_no",
                    models.CharField(
                        blank=True, max_length=60, null=True, verbose_name="批号"
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "订单行来源映射",
                "verbose_name_plural": "订单行来源映射",
            },
        ),
        migrations.CreateModel(
            name="OutboundOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="已删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用状态"),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="制表时间"),
                ),
                (
                    "order_no",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="订单编号"
                    ),
                ),
                (
                    "biz_date",
                    models.DateField(default=datetime.date.today, verbose_name="日期"),
                ),
                (
                    "src_bill_no",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="源单号"
                    ),
                ),
                (
                    "outbound_type",
                    models.CharField(
                        choices=[
                            ("SALES", "销售出库"),
                            ("TRANSFER", "调拨出库"),
                            ("OTHER_OUT", "其他出库"),
                            ("SUPPLIER_RETURN", "退回供应商"),
                        ],
                        default="SALES",
                        max_length=15,
                        verbose_name="出库类型",
                    ),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PICKUP", "客户自提"),
                            ("OWN_TRUCK", "配送"),
                            ("COURIER", "快递/小包"),
                        ],
                        max_length=15,
                        null=True,
                        verbose_name="交货方式",
                    ),
                ),
                (
                    "etd",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="预计发货时间"
                    ),
                ),
                (
                    "submit_status",
                    models.CharField(
                        choices=[("SUBMITTED", "已提交"), ("DRAFT", "未提交")],
                        db_index=True,
                        default="DRAFT",
                        max_length=15,
                        verbose_name="提交状态",
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("OWNER_PENDING", "待货主管理员审核"),
                            ("OWNER_APPROVED", "货主管理员已审核通过"),
                            ("OWNER_REJECTED", "货主管理员已驳回"),
                            ("WHS_PENDING", "待仓库管理员确认"),
                            ("WHS_APPROVED", "仓库管理员已确认,待拣货"),
                            ("WHS_REJECTED", "仓库管理员已驳回"),
                            ("CANCELLED", "已取消"),
                        ],
                        db_index=True,
                        default="OWNER_PENDING",
                        max_length=15,
                        verbose_name="审核状态",
                    ),
                ),
                (
                    "ship_to",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="收货地址"
                    ),
                ),
                (
                    "contact",
                    models.CharField(
                        blank=True, max_length=80, null=True, verbose_name="联系人"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="联系电话"
                    ),
                ),
                (
                    "memo",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="备注"
                    ),
                ),
                (
                    "is_closed",
                    models.BooleanField(default=False, verbose_name="订单关闭"),
                ),
                (
                    "close_reason",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="关闭理由"
                    ),
                ),
                (
                    "approved_at_ownermanager",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="货主管理员审核时间"
                    ),
                ),
                (
                    "approved_at_warehouse",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="仓库管理员审核时间"
                    ),
                ),
                (
                    "next_line_no",
                    models.PositiveIntegerField(
                        default=10, verbose_name="下一个订单行号"
                    ),
                ),
                (
                    "pricing_status",
                    models.CharField(
                        choices=[("PENDING", "待定价"), ("CONFIRMED", "已确认")],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                        verbose_name="价格状态",
                    ),
                ),
                (
                    "priced_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="价格确认时间"
                    ),
                ),
                (
                    "final_order_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=18,
                        verbose_name="最终订单金额",
                    ),
                ),
            ],
            options={
                "verbose_name": "出库订单",
                "verbose_name_plural": "出库订单",
                "ordering": ["-biz_date", "-id"],
                "permissions": [
                    (
                        "approve_outbound_as_owner_manager",
                        "货主管理员可执行出库审核动作",
                    ),
                    ("approve_outbound_as_wh_manager", "仓库管理员可执行出库确认动作"),
                    ("submit_outbound_as_owner_buyers", "货主业务员可提交出库订单"),
                ],
            },
        ),
        migrations.CreateModel(
            name="OutboundOrderExtra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="已删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用状态"),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "vendor_rma_no",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=40,
                        verbose_name="供应商RMA/授权号",
                    ),
                ),
                (
                    "reason_code",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="退回原因代码",
                    ),
                ),
                (
                    "reason_desc",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="退回原因描述",
                    ),
                ),
                (
                    "chargeback_flag",
                    models.BooleanField(default=False, verbose_name="是否扣款/索赔"),
                ),
                (
                    "expected_credit_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="预计供应商贷项",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True, default="", max_length=3, verbose_name="币种"
                    ),
                ),
                (
                    "vehicle_no",
                    models.CharField(
                        blank=True, default="", max_length=32, verbose_name="车牌号"
                    ),
                ),
                (
                    "tracking_no",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="运单号/追踪号",
                    ),
                ),
                (
                    "seal_no",
                    models.CharField(
                        blank=True, default="", max_length=40, verbose_name="封签号"
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "出库单头扩展",
                "verbose_name_plural": "出库单头扩展",
            },
        ),
        migrations.CreateModel(
            name="OutboundOrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="已删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用状态"),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "base_qty",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=14,
                        verbose_name="基本数量",
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=14,
                        verbose_name="基本价格",
                    ),
                ),
                (
                    "aux_qty",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=14,
                        null=True,
                        verbose_name="包装数量",
                    ),
                ),
                (
                    "aux_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=14,
                        null=True,
                        verbose_name="包装价格",
                    ),
                ),
                (
                    "ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=14,
                        null=True,
                        verbose_name="换算率(快照)",
                    ),
                ),
                ("line_no", models.PositiveIntegerField(verbose_name="行号")),
                (
                    "lot_no",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="批号"
                    ),
                ),
                (
                    "min_remaining_days",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="最短剩余效期(天)"
                    ),
                ),
                (
                    "pack_requirement",
                    models.CharField(
                        choices=[
                            ("NONE", "无（不需要打包）"),
                            ("BAG", "袋装/气泡袋"),
                            ("BOX", "装箱"),
                            ("SHRINK", "缠绕/热缩"),
                            ("PALLET", "打托/缠膜"),
                        ],
                        default="NONE",
                        max_length=20,
                        verbose_name="打包要求",
                    ),
                ),
                (
                    "pack_note",
                    models.CharField(
                        blank=True, default="", max_length=120, verbose_name="打包备注"
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="明细备注"
                    ),
                ),
                (
                    "final_line_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=18,
                        verbose_name="最终行金额",
                    ),
                ),
            ],
            options={
                "verbose_name": "出库订单行",
                "verbose_name_plural": "出库订单行",
                "ordering": ["order_id", "line_no"],
            },
        ),
    ]
