# Generated by Django 5.2.5 on 2026-04-24 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("baseinfo", "0002_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("inbound", "0001_initial"),
        ("locations", "0001_initial"),
        ("outbound", "0001_initial"),
        ("products", "0001_initial"),
        ("tasking", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FuncLabelBatch",
            fields=[],
            options={
                "verbose_name": "面单批量打印",
                "verbose_name_plural": "面单批量打印",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("tasking.wmstask",),
        ),
        migrations.CreateModel(
            name="FuncShippingBoard",
            fields=[],
            options={
                "verbose_name": "发运看板",
                "verbose_name_plural": "发运看板",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("tasking.wmstask",),
        ),
        migrations.CreateModel(
            name="FuncWaveGenerate",
            fields=[],
            options={
                "verbose_name": "波次生成",
                "verbose_name_plural": "波次生成",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("tasking.wmstask",),
        ),
        migrations.AddField(
            model_name="orderlinesourcelink",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="products.product",
                verbose_name="商品",
            ),
        ),
        migrations.AddField(
            model_name="orderlinesourcelink",
            name="src_ct",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="contenttypes.contenttype",
                verbose_name="来源类型",
            ),
        ),
        migrations.AddField(
            model_name="outboundorder",
            name="approved_by_ownermanager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appr_by_owner_out_ord",
                to=settings.AUTH_USER_MODEL,
                verbose_name="货主管理员审核人",
            ),
        ),
        migrations.AddField(
            model_name="outboundorder",
            name="approved_by_warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appr_by_wh_out_orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="仓库管理员审核人",
            ),
        ),
        migrations.AddField(
            model_name="outboundorder",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="制表人",
            ),
        ),
        migrations.AddField(
            model_name="outboundorder",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="outbound_orders",
                to="baseinfo.customer",
                verbose_name="客户",
            ),
        ),
        migrations.AddField(
            model_name="outboundorder",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_deleted",
                to=settings.AUTH_USER_MODEL,
                verbose_name="删除人",
            ),
        ),
        migrations.AddField(
            model_name="outboundorder",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="outbound_orders",
                to="baseinfo.owner",
                verbose_name="货主",
            ),
        ),
        migrations.AddField(
            model_name="outboundorder",
            name="priced_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="priced_outbound_orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="价格确认人",
            ),
        ),
        migrations.AddField(
            model_name="outboundorder",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="outbound_returns",
                to="baseinfo.supplier",
                verbose_name="供应商",
            ),
        ),
        migrations.AddField(
            model_name="outboundorder",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="更新人",
            ),
        ),
        migrations.AddField(
            model_name="outboundorder",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="outbound_orders",
                to="locations.warehouse",
                verbose_name="仓库",
            ),
        ),
        migrations.AddField(
            model_name="outboundorderextra",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rtv_approved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="outboundorderextra",
            name="carrier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="baseinfo.carriercompany",
                verbose_name="承运商",
            ),
        ),
        migrations.AddField(
            model_name="outboundorderextra",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AddField(
            model_name="outboundorderextra",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_deleted",
                to=settings.AUTH_USER_MODEL,
                verbose_name="删除人",
            ),
        ),
        migrations.AddField(
            model_name="outboundorderextra",
            name="inbound_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="generated_outbound_rtv",
                to="inbound.inboundorder",
                verbose_name="来源入库单",
            ),
        ),
        migrations.AddField(
            model_name="outboundorderextra",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="extra",
                to="outbound.outboundorder",
                verbose_name="对应出库单",
            ),
        ),
        migrations.AddField(
            model_name="outboundorderextra",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="更新人",
            ),
        ),
        migrations.AddField(
            model_name="outboundorderline",
            name="aux_uom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="products.productpackage",
                verbose_name="包装单位",
            ),
        ),
        migrations.AddField(
            model_name="outboundorderline",
            name="base_uom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="products.productuom",
                verbose_name="基本单位",
            ),
        ),
        migrations.AddField(
            model_name="outboundorderline",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AddField(
            model_name="outboundorderline",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_deleted",
                to=settings.AUTH_USER_MODEL,
                verbose_name="删除人",
            ),
        ),
        migrations.AddField(
            model_name="outboundorderline",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lines",
                to="outbound.outboundorder",
                verbose_name="订单",
            ),
        ),
        migrations.AddField(
            model_name="outboundorderline",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="products.product",
                verbose_name="商品",
            ),
        ),
        migrations.AddField(
            model_name="outboundorderline",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="更新人",
            ),
        ),
        migrations.AddField(
            model_name="orderlinesourcelink",
            name="order_line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="source_links",
                to="outbound.outboundorderline",
                verbose_name="出库行",
            ),
        ),
        migrations.AddIndex(
            model_name="outboundorder",
            index=models.Index(
                fields=["owner", "biz_date", "submit_status"],
                name="idx_out_owner_date_stat",
            ),
        ),
        migrations.AddIndex(
            model_name="outboundorder",
            index=models.Index(fields=["approval_status"], name="idx_out_appr_stat"),
        ),
        migrations.AddIndex(
            model_name="outboundorder",
            index=models.Index(
                fields=["customer", "biz_date"], name="idx_out_cust_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="outboundorder",
            constraint=models.CheckConstraint(
                condition=models.Q(("submit_status__in", ["DRAFT", "SUBMITTED"])),
                name="ck_o_submit_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="outboundorder",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "approval_status__in",
                        [
                            "OWNER_PENDING",
                            "OWNER_APPROVED",
                            "OWNER_REJECTED",
                            "WHS_PENDING",
                            "WHS_APPROVED",
                            "WHS_REJECTED",
                            "CANCELLED",
                        ],
                    )
                ),
                name="ox_valid_approval",
            ),
        ),
        migrations.AddConstraint(
            model_name="outboundorder",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_closed", True), ("approval_status", "CANCELLED"), _negated=True
                ),
                name="ox_close_appr_chk",
            ),
        ),
        migrations.AddConstraint(
            model_name="outboundorder",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("outbound_type", "SUPPLIER_RETURN"),
                        ("supplier__isnull", False),
                        ("customer__isnull", True),
                    ),
                    models.Q(
                        models.Q(("outbound_type", "SUPPLIER_RETURN"), _negated=True),
                        ("customer__isnull", False),
                        ("supplier__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="ox_rtv_partner_chk",
            ),
        ),
        migrations.AddIndex(
            model_name="outboundorderextra",
            index=models.Index(fields=["vendor_rma_no"], name="ix_oextra_rma"),
        ),
        migrations.AddIndex(
            model_name="outboundorderextra",
            index=models.Index(fields=["tracking_no"], name="ix_oextra_track"),
        ),
        migrations.AddConstraint(
            model_name="outboundorderextra",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("approved_at__isnull", True), ("approved_by__isnull", True)
                    ),
                    models.Q(
                        ("approved_at__isnull", False), ("approved_by__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="chk_oextra_approved_pair",
            ),
        ),
        migrations.AddConstraint(
            model_name="outboundorderextra",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("expected_credit_amount__gte", 0),
                    ("expected_credit_amount__isnull", True),
                    _connector="OR",
                ),
                name="chk_oextra_credit_nonneg",
            ),
        ),
        migrations.AddIndex(
            model_name="outboundorderline",
            index=models.Index(fields=["order", "product"], name="idx_out_order_prod"),
        ),
        migrations.AddIndex(
            model_name="outboundorderline",
            index=models.Index(fields=["product", "lot_no"], name="idx_out_prod_lot"),
        ),
        migrations.AddIndex(
            model_name="outboundorderline",
            index=models.Index(fields=["order", "lot_no"], name="idx_out_order_lot"),
        ),
        migrations.AddConstraint(
            model_name="outboundorderline",
            constraint=models.UniqueConstraint(
                fields=("order", "line_no"), name="ux_out_line_no"
            ),
        ),
        migrations.AddConstraint(
            model_name="outboundorderline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("base_qty__gt", 0), ("aux_qty__gt", 0), _connector="OR"
                ),
                name="chk_out_qty_pos",
            ),
        ),
        migrations.AddConstraint(
            model_name="outboundorderline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("base_qty__gte", 0),
                    models.Q(
                        ("aux_qty__gte", 0), ("aux_qty__isnull", True), _connector="OR"
                    ),
                ),
                name="chk_out_qty_nonneg",
            ),
        ),
        migrations.AddConstraint(
            model_name="outboundorderline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("base_price__gte", 0),
                    models.Q(
                        ("aux_price__gte", 0),
                        ("aux_price__isnull", True),
                        _connector="OR",
                    ),
                ),
                name="chk_out_price_nonneg",
            ),
        ),
        migrations.AddIndex(
            model_name="orderlinesourcelink",
            index=models.Index(fields=["order_line"], name="ix_olsrc_line"),
        ),
        migrations.AddIndex(
            model_name="orderlinesourcelink",
            index=models.Index(fields=["src_ct", "src_id"], name="ix_olsrc_src"),
        ),
        migrations.AddIndex(
            model_name="orderlinesourcelink",
            index=models.Index(fields=["product", "lot_no"], name="ix_olsrc_prod_lot"),
        ),
        migrations.AddConstraint(
            model_name="orderlinesourcelink",
            constraint=models.UniqueConstraint(
                fields=("order_line", "src_ct", "src_id"), name="ux_olsrc_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="orderlinesourcelink",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("posted_qty_base__gte", 0),
                    models.Q(
                        ("plan_qty_base__isnull", True),
                        ("plan_qty_base__gte", 0),
                        _connector="OR",
                    ),
                ),
                name="ck_olsrc_qty_nonneg",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderlinesourcelink",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("plan_qty_base__isnull", True),
                    ("posted_qty_base__lte", models.F("plan_qty_base")),
                    _connector="OR",
                ),
                name="ck_olsrc_post_le_plan",
            ),
        ),
    ]
