# Generated by Django 5.2.12 on 2026-07-16 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outbound", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="outboundorder",
            options={
                "ordering": ["-biz_date", "-id"],
                "permissions": [
                    (
                        "approve_outbound_as_owner_manager",
                        "货主管理员可执行出库审核动作",
                    ),
                    (
                        "approve_outbound_as_wh_manager",
                        "仓库管理员可执行出库确认动作",
                    ),
                    (
                        "submit_outbound_as_owner_buyers",
                        "货主业务员可提交出库订单",
                    ),
                    (
                        "process_warehouse_assisted_outbound",
                        "仓库操作员可代货主处理出库",
                    ),
                    ("view_all_outbound_orders", "可查看全部出库订单"),
                ],
                "verbose_name": "出库订单",
                "verbose_name_plural": "出库订单",
            },
        ),
        migrations.AddField(
            model_name="outboundorder",
            name="assistance_reason",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="代办原因"
            ),
        ),
        migrations.AddField(
            model_name="outboundorder",
            name="assistance_request_id",
            field=models.UUIDField(
                blank=True, null=True, unique=True, verbose_name="代办请求 ID"
            ),
        ),
        migrations.AddField(
            model_name="outboundorder",
            name="assisted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="代办时间"),
        ),
        migrations.AddField(
            model_name="outboundorder",
            name="assisted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="warehouse_assisted_outbound_orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="代办操作员",
            ),
        ),
        migrations.AddField(
            model_name="outboundorder",
            name="processing_mode",
            field=models.CharField(
                choices=[
                    ("STANDARD", "标准出库"),
                    ("WAREHOUSE_ASSISTED", "仓库代办出库"),
                ],
                db_index=True,
                default="STANDARD",
                max_length=20,
                verbose_name="处理模式",
            ),
        ),
    ]
