# Generated by Django 5.2.5 on 2026-04-03 23:35

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outbound", "0003_alter_outboundorder_warehouse"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="outboundorder",
            name="final_order_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=18,
                verbose_name="最终订单金额",
            ),
        ),
        migrations.AddField(
            model_name="outboundorder",
            name="priced_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="价格确认时间"
            ),
        ),
        migrations.AddField(
            model_name="outboundorder",
            name="priced_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="outbound_orders_priced",
                to=settings.AUTH_USER_MODEL,
                verbose_name="价格确认人",
            ),
        ),
        migrations.AddField(
            model_name="outboundorder",
            name="pricing_status",
            field=models.CharField(
                choices=[("PENDING", "待定价"), ("CONFIRMED", "已确认")],
                default="PENDING",
                max_length=20,
                verbose_name="价格状态",
            ),
        ),
    ]
