# Generated by Django 5.2.5 on 2025-10-23 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("outbound", "0003_alter_outboundorder_warehouse"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="outboundorder",
            options={
                "ordering": ["-biz_date", "-id"],
                "permissions": [
                    (
                        "approve_outbound_as_owner_manager",
                        "货主管理员可执行出库审核动作",
                    ),
                    ("approve_outbound_as_wh_manager", "仓库管理员可执行出库确认动作"),
                    ("submit_outbound_as_owner_buyers", "货主业务员可提交出库订单"),
                ],
                "verbose_name": "出库订单",
                "verbose_name_plural": "出库订单",
            },
        ),
    ]
