# Generated by Django 5.2.5 on 2026-04-03 23:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outbound", "0004_outboundorder_final_order_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="outboundorderline",
            name="final_line_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=18,
                verbose_name="最终行金额",
            ),
        ),
    ]
