# Generated by Django 5.2.5 on 2026-04-04 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbound', '0005_outboundorderline_final_line_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboundorder',
            name='priced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='priced_outbound_orders', to=settings.AUTH_USER_MODEL, verbose_name='价格确认人'),
        ),
        migrations.AlterField(
            model_name='outboundorder',
            name='pricing_status',
            field=models.CharField(choices=[('PENDING', '待定价'), ('CONFIRMED', '已确认')], db_index=True, default='PENDING', max_length=20, verbose_name='价格状态'),
        ),
    ]
