# Generated by Django 5.2.5 on 2026-04-24 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("baseinfo", "0002_initial"),
        ("locations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="已删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用状态"),
                ),
                ("ref_type", models.CharField(blank=True, default="", max_length=64)),
                ("ref_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "ref_no",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "新建"),
                            ("assigned", "已指派"),
                            ("accepted", "已受理"),
                            ("in_transit", "在途"),
                            ("arrived", "已到达"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="new",
                        max_length=16,
                    ),
                ),
                ("planned_depart_at", models.DateTimeField(blank=True, null=True)),
                ("planned_arrive_at", models.DateTimeField(blank=True, null=True)),
                ("departed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("priority", models.PositiveSmallIntegerField(default=5)),
                ("remark", models.CharField(blank=True, default="", max_length=255)),
                (
                    "CarrierCompany",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delivery_tasks",
                        to="baseinfo.carriercompany",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delivery_tasks",
                        to="baseinfo.driver",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delivery_tasks",
                        to="baseinfo.owner",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delivery_tasks",
                        to="baseinfo.vehicle",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delivery_tasks",
                        to="locations.warehouse",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DriverDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="已删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
                ("device_id", models.CharField(max_length=128)),
                ("brand", models.CharField(blank=True, default="", max_length=64)),
                ("model", models.CharField(blank=True, default="", max_length=64)),
                ("os", models.CharField(blank=True, default="", max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="devices",
                        to="baseinfo.driver",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DriverShift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="已删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用状态"),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("in", "上班"), ("out", "下班")], max_length=8
                    ),
                ),
                ("at", models.DateTimeField()),
                (
                    "geo_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "geo_lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                ("request_id", models.CharField(db_index=True, max_length=64)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="driverapp.driverdevice",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shifts",
                        to="baseinfo.driver",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="driver_shifts",
                        to="locations.warehouse",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskStop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="已删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用状态"),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
                ("seq", models.PositiveSmallIntegerField()),
                ("consignee_name", models.CharField(max_length=128)),
                (
                    "consignee_phone",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("address", models.CharField(max_length=255)),
                (
                    "geo_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "geo_lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "待执行"),
                            ("enroute", "在途"),
                            ("arrived", "已到达"),
                            ("servicing", "服务中"),
                            ("done", "完成"),
                            ("exception", "异常"),
                        ],
                        default="new",
                        max_length=16,
                    ),
                ),
                ("planned_arrive_at", models.DateTimeField(blank=True, null=True)),
                ("actual_arrive_at", models.DateTimeField(blank=True, null=True)),
                ("actual_leave_at", models.DateTimeField(blank=True, null=True)),
                ("ref_type", models.CharField(blank=True, default="", max_length=64)),
                ("ref_id", models.CharField(blank=True, default="", max_length=64)),
                ("ref_no", models.CharField(blank=True, default="", max_length=64)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stops",
                        to="driverapp.deliverytask",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExceptionReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="已删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用状态"),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("damage", "破损"),
                            ("shortage", "少货"),
                            ("delay", "延误"),
                            ("refusal", "拒收"),
                            ("traffic", "交通/封路"),
                            ("other", "其它"),
                        ],
                        default="other",
                        max_length=16,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "提示"),
                            ("minor", "一般"),
                            ("major", "严重"),
                            ("critical", "致命"),
                        ],
                        default="minor",
                        max_length=16,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("photo_urls", models.JSONField(blank=True, default=list)),
                ("files", models.JSONField(blank=True, default=list)),
                ("occurred_at", models.DateTimeField()),
                ("request_id", models.CharField(db_index=True, max_length=64)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exceptions",
                        to="driverapp.deliverytask",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
                (
                    "stop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exceptions",
                        to="driverapp.taskstop",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeliveryPreSign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="已删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用状态"),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待确认"),
                            ("confirmed", "已确认"),
                            ("rejected", "已驳回"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "consignee_contact",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "consignee_note",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("photo_urls", models.JSONField(blank=True, default=list)),
                ("files", models.JSONField(blank=True, default=list)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("request_id", models.CharField(db_index=True, max_length=64)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pre_signs",
                        to="driverapp.deliverytask",
                    ),
                ),
                (
                    "stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pre_signs",
                        to="driverapp.taskstop",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrackingDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="已删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用状态"),
                ),
                ("imei", models.CharField(max_length=64, unique=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("gps_hw", "GPS硬件"),
                            ("obd", "OBD"),
                            ("other", "其它"),
                        ],
                        default="gps_hw",
                        max_length=16,
                    ),
                ),
                ("remark", models.CharField(blank=True, default="", max_length=255)),
                (
                    "CarrierCompany",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="baseinfo.carriercompany",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tracking_devices",
                        to="baseinfo.vehicle",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TrackingPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="已删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用状态"),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("phone", "手机定位"), ("gps_hw", "GPS硬件")],
                        default="phone",
                        max_length=16,
                    ),
                ),
                ("lat", models.DecimalField(decimal_places=6, max_digits=10)),
                ("lng", models.DecimalField(decimal_places=6, max_digits=10)),
                (
                    "speed",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "heading",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("located_at", models.DateTimeField()),
                ("request_id", models.CharField(max_length=64)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "driver_device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tracking_points",
                        to="driverapp.driverdevice",
                    ),
                ),
                (
                    "stop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tracking_points",
                        to="driverapp.taskstop",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tracking_points",
                        to="driverapp.deliverytask",
                    ),
                ),
                (
                    "tracking_device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tracking_points",
                        to="driverapp.trackingdevice",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="deliverytask",
            index=models.Index(
                fields=["owner", "status"], name="driverapp_d_owner_i_97020e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deliverytask",
            index=models.Index(
                fields=["status", "planned_depart_at"],
                name="driverapp_d_status_8dbeff_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="deliverytask",
            index=models.Index(
                fields=["driver", "status"], name="driverapp_d_driver__68c3ad_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="driverdevice",
            unique_together={("driver", "device_id")},
        ),
        migrations.AddIndex(
            model_name="drivershift",
            index=models.Index(
                fields=["driver", "at"], name="driverapp_d_driver__8ccc89_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="drivershift",
            index=models.Index(
                fields=["action", "at"], name="driverapp_d_action_a4f1b7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="drivershift",
            unique_together={("driver", "request_id")},
        ),
        migrations.AddIndex(
            model_name="taskstop",
            index=models.Index(
                fields=["task", "seq"], name="driverapp_t_task_id_e5cac3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskstop",
            index=models.Index(fields=["status"], name="driverapp_t_status_07bf5e_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="taskstop",
            unique_together={("task", "seq")},
        ),
        migrations.AddIndex(
            model_name="exceptionreport",
            index=models.Index(
                fields=["task", "occurred_at"], name="driverapp_e_task_id_180fc3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exceptionreport",
            index=models.Index(
                fields=["category", "level"], name="driverapp_e_categor_eb4c3c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="exceptionreport",
            unique_together={("task", "request_id")},
        ),
        migrations.AddIndex(
            model_name="deliverypresign",
            index=models.Index(
                fields=["task", "stop", "status"], name="driverapp_d_task_id_02a6e9_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="deliverypresign",
            unique_together={("stop", "request_id")},
        ),
        migrations.AddIndex(
            model_name="trackingpoint",
            index=models.Index(
                fields=["task", "located_at"], name="driverapp_t_task_id_460695_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trackingpoint",
            index=models.Index(
                fields=["source", "located_at"], name="driverapp_t_source_c95a01_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="trackingpoint",
            unique_together={
                ("driver_device", "request_id"),
                ("tracking_device", "request_id"),
            },
        ),
    ]
