# Generated by Django 5.2.5 on 2026-03-29 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driverapp', '0001_initial'),
        ('locations', '0002_alter_container_warehouse_alter_location_warehouse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytask',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_tasks', to='locations.warehouse'),
        ),
        migrations.AlterField(
            model_name='drivershift',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='driver_shifts', to='locations.warehouse'),
        ),
    ]
