# Generated by Django 5.2.5 on 2025-10-19 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("driverapp", "0001_initial"),
        ("locations", "0002_remove_location_zone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliverytask",
            name="warehouse",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="delivery_tasks",
                to="locations.warehouse",
            ),
        ),
        migrations.AlterField(
            model_name="drivershift",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="driver_shifts",
                to="locations.warehouse",
            ),
        ),
    ]
