# Generated by Django 5.2.5 on 2026-06-24 12:25

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseinfo", "0002_initial"),
        ("locations", "0003_clarify_warehouse_subwarehouse_scope"),
        ("pos", "0004_print_log_source_shift_reopen"),
        ("products", "0002_add_cross_owner_product_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="posshift",
            name="return_count",
            field=models.PositiveIntegerField(default=0, verbose_name="退货单数"),
        ),
        migrations.AddField(
            model_name="posshift",
            name="total_return_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=18,
                verbose_name="退货金额",
            ),
        ),
        migrations.AddField(
            model_name="posshiftpaymentsummary",
            name="refund_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=18,
                verbose_name="退款金额",
            ),
        ),
        migrations.AddField(
            model_name="posshiftpaymentsummary",
            name="refund_count",
            field=models.PositiveIntegerField(default=0, verbose_name="退款单数"),
        ),
        migrations.CreateModel(
            name="PosReturn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "return_no",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="POS退货单号"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("COMPLETED", "已完成"), ("VOIDED", "已撤销")],
                        db_index=True,
                        default="COMPLETED",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=18,
                        verbose_name="退货金额",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="退货原因"
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="幂等键",
                    ),
                ),
                (
                    "idempotency_fingerprint",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="幂等请求指纹",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "cashier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pos_returns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="returns",
                        to="pos.possale",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="returns",
                        to="pos.posshift",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pos_returns",
                        to="locations.warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "POS退货单",
                "verbose_name_plural": "POS退货单",
            },
        ),
        migrations.CreateModel(
            name="PosRefund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("CASH", "现金"),
                            ("WECHAT", "微信"),
                            ("ALIPAY", "支付宝"),
                            ("BANK_CARD", "银行卡"),
                            ("OTHER", "其他"),
                        ],
                        max_length=20,
                        verbose_name="退款方式",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=18, verbose_name="退款金额"
                    ),
                ),
                (
                    "reference_no",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="退款参考号",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待退款"),
                            ("REFUNDED", "已退款"),
                            ("FAILED", "退款失败"),
                            ("CANCELED", "已取消"),
                        ],
                        db_index=True,
                        default="REFUNDED",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="退款时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="processed_pos_refunds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="pos.possale",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="pos.posshift",
                    ),
                ),
                (
                    "return_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="pos.posreturn",
                    ),
                ),
            ],
            options={
                "verbose_name": "POS退款流水",
                "verbose_name_plural": "POS退款流水",
            },
        ),
        migrations.CreateModel(
            name="PosAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CHECKOUT", "收银结账"),
                            ("VOID", "销售作废"),
                            ("RETURN", "退货"),
                            ("REFUND", "退款"),
                            ("SHIFT_OPEN", "开班"),
                            ("SHIFT_CLOSE", "交班"),
                            ("SHIFT_REOPEN", "重开班次"),
                            ("PRINT", "打印"),
                        ],
                        max_length=30,
                        verbose_name="动作",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="原因"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="元数据"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pos_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_logs",
                        to="pos.possale",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_logs",
                        to="pos.posshift",
                    ),
                ),
                (
                    "return_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_logs",
                        to="pos.posreturn",
                    ),
                ),
            ],
            options={
                "verbose_name": "POS操作审计",
                "verbose_name_plural": "POS操作审计",
            },
        ),
        migrations.CreateModel(
            name="PosReturnLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_no", models.PositiveIntegerField(verbose_name="行号")),
                (
                    "qty",
                    models.DecimalField(
                        decimal_places=3, max_digits=18, verbose_name="基本数量"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=4, max_digits=18, verbose_name="基本单价"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=18, verbose_name="金额"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pos_return_lines",
                        to="baseinfo.owner",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pos_return_lines",
                        to="products.product",
                    ),
                ),
                (
                    "return_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="pos.posreturn",
                    ),
                ),
                (
                    "sale_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_lines",
                        to="pos.possaleline",
                    ),
                ),
            ],
            options={
                "verbose_name": "POS退货明细",
                "verbose_name_plural": "POS退货明细",
            },
        ),
        migrations.CreateModel(
            name="PosPaymentLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("CASH", "现金"),
                            ("WECHAT", "微信"),
                            ("ALIPAY", "支付宝"),
                            ("BANK_CARD", "银行卡"),
                            ("OTHER", "其他"),
                        ],
                        max_length=20,
                        verbose_name="支付方式",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=18, verbose_name="抵扣金额"
                    ),
                ),
                (
                    "amount_received",
                    models.DecimalField(
                        decimal_places=2, max_digits=18, verbose_name="实收金额"
                    ),
                ),
                (
                    "change_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=18,
                        verbose_name="找零",
                    ),
                ),
                (
                    "reference_no",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="支付参考号",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("PAID", "已收款"), ("VOIDED", "已撤销")],
                        db_index=True,
                        default="PAID",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_lines",
                        to="pos.possale",
                    ),
                ),
            ],
            options={
                "verbose_name": "POS收款明细",
                "verbose_name_plural": "POS收款明细",
                "indexes": [
                    models.Index(
                        fields=["sale", "method"], name="idx_pos_payline_sale"
                    ),
                    models.Index(
                        fields=["method", "created_at"], name="idx_pos_payline_method"
                    ),
                    models.Index(
                        fields=["status", "created_at"], name="idx_pos_payline_status"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="posreturn",
            index=models.Index(
                fields=["warehouse", "created_at"], name="idx_pos_return_wh_created"
            ),
        ),
        migrations.AddIndex(
            model_name="posreturn",
            index=models.Index(
                fields=["shift", "created_at"], name="idx_pos_return_shift"
            ),
        ),
        migrations.AddIndex(
            model_name="posreturn",
            index=models.Index(
                fields=["sale", "created_at"], name="idx_pos_return_sale"
            ),
        ),
        migrations.AddIndex(
            model_name="posrefund",
            index=models.Index(
                fields=["return_order", "method"], name="idx_pos_refund_return"
            ),
        ),
        migrations.AddIndex(
            model_name="posrefund",
            index=models.Index(
                fields=["shift", "created_at"], name="idx_pos_refund_shift"
            ),
        ),
        migrations.AddIndex(
            model_name="posrefund",
            index=models.Index(
                fields=["method", "created_at"], name="idx_pos_refund_method"
            ),
        ),
        migrations.AddIndex(
            model_name="posrefund",
            index=models.Index(
                fields=["status", "created_at"], name="idx_pos_refund_status"
            ),
        ),
        migrations.AddIndex(
            model_name="posauditlog",
            index=models.Index(
                fields=["action", "created_at"], name="idx_pos_audit_action"
            ),
        ),
        migrations.AddIndex(
            model_name="posauditlog",
            index=models.Index(
                fields=["sale", "created_at"], name="idx_pos_audit_sale"
            ),
        ),
        migrations.AddIndex(
            model_name="posauditlog",
            index=models.Index(
                fields=["shift", "created_at"], name="idx_pos_audit_shift"
            ),
        ),
        migrations.AddIndex(
            model_name="posauditlog",
            index=models.Index(
                fields=["return_order", "created_at"], name="idx_pos_audit_return"
            ),
        ),
        migrations.AddIndex(
            model_name="posreturnline",
            index=models.Index(
                fields=["return_order", "owner"], name="idx_pos_return_line_owner"
            ),
        ),
        migrations.AddIndex(
            model_name="posreturnline",
            index=models.Index(
                fields=["sale_line"], name="idx_pos_return_line_sale_line"
            ),
        ),
        migrations.AddIndex(
            model_name="posreturnline",
            index=models.Index(fields=["product"], name="idx_pos_return_line_product"),
        ),
        migrations.AddConstraint(
            model_name="posreturnline",
            constraint=models.UniqueConstraint(
                fields=("return_order", "line_no"), name="ux_pos_return_line_no"
            ),
        ),
    ]
