# Generated by Django 5.2.5 on 2026-06-30 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0003_clarify_warehouse_subwarehouse_scope"),
        ("pos", "0006_backfill_pos_payment_lines"),
    ]

    operations = [
        migrations.CreateModel(
            name="PosReceiptWarehouseInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="名称")),
                (
                    "address",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="店铺地址"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="电话"
                    ),
                ),
                (
                    "bank_account",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="银行账号"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                ("is_default", models.BooleanField(default=False, verbose_name="默认")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="排序"),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="备注"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        help_text="留空表示所有仓库通用。",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pos_receipt_infos",
                        to="locations.warehouse",
                        verbose_name="适用仓库",
                    ),
                ),
            ],
            options={
                "verbose_name": "POS销售单仓库信息",
                "verbose_name_plural": "POS销售单仓库信息",
                "indexes": [
                    models.Index(
                        fields=["warehouse", "is_active", "sort_order"],
                        name="idx_pos_receipt_info_wh",
                    ),
                    models.Index(
                        fields=["is_default", "sort_order"],
                        name="idx_pos_receipt_info_def",
                    ),
                ],
            },
        ),
    ]
