# Generated by Codex on 2026-07-01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

PAYMENT_METHOD_CHOICES = [
    ("CASH", "现金"),
    ("WECHAT", "微信"),
    ("ALIPAY", "支付宝"),
    ("BANK_CARD", "银行卡"),
    ("CREDIT", "赊账"),
    ("OTHER", "其他"),
]


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("baseinfo", "0001_initial"),
        ("locations", "0003_clarify_warehouse_subwarehouse_scope"),
        ("pos", "0007_posreceiptwarehouseinfo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("CHECKOUT", "收银结账"),
                    ("VOID", "销售作废"),
                    ("RETURN", "退货"),
                    ("REFUND", "退款"),
                    ("REPAYMENT", "客户还款"),
                    ("SHIFT_OPEN", "开班"),
                    ("SHIFT_CLOSE", "交班"),
                    ("SHIFT_REOPEN", "重开班次"),
                    ("PRINT", "打印"),
                ],
                max_length=30,
                verbose_name="动作",
            ),
        ),
        migrations.AlterField(
            model_name="pospayment",
            name="method",
            field=models.CharField(
                choices=PAYMENT_METHOD_CHOICES,
                max_length=20,
                verbose_name="支付方式",
            ),
        ),
        migrations.AlterField(
            model_name="pospaymentline",
            name="method",
            field=models.CharField(
                choices=PAYMENT_METHOD_CHOICES,
                max_length=20,
                verbose_name="支付方式",
            ),
        ),
        migrations.AlterField(
            model_name="posrefund",
            name="method",
            field=models.CharField(
                choices=PAYMENT_METHOD_CHOICES,
                max_length=20,
                verbose_name="退款方式",
            ),
        ),
        migrations.AlterField(
            model_name="posshiftpaymentsummary",
            name="method",
            field=models.CharField(
                choices=PAYMENT_METHOD_CHOICES,
                max_length=20,
                verbose_name="支付方式",
            ),
        ),
        migrations.AddField(
            model_name="posshiftpaymentsummary",
            name="repayment_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=18,
                verbose_name="还款金额",
            ),
        ),
        migrations.AddField(
            model_name="posshiftpaymentsummary",
            name="repayment_count",
            field=models.PositiveIntegerField(default=0, verbose_name="还款单数"),
        ),
        migrations.CreateModel(
            name="PosCustomerRepayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "repayment_no",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="POS客户还款单号",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=PAYMENT_METHOD_CHOICES,
                        max_length=20,
                        verbose_name="还款方式",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        verbose_name="还款金额",
                    ),
                ),
                (
                    "reference_no",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="还款参考号",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("COMPLETED", "已完成"), ("VOIDED", "已撤销")],
                        db_index=True,
                        default="COMPLETED",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="备注",
                    ),
                ),
                (
                    "voided_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="撤销时间",
                    ),
                ),
                (
                    "void_reason",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="撤销原因",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "cashier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pos_repayments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_pos_repayments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pos_repayments",
                        to="baseinfo.customer",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="repayments",
                        to="pos.posshift",
                    ),
                ),
                (
                    "voided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="voided_pos_repayments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pos_repayments",
                        to="locations.warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "POS客户还款",
                "verbose_name_plural": "POS客户还款",
                "indexes": [
                    models.Index(
                        fields=["warehouse", "created_at"],
                        name="idx_pos_repay_wh_created",
                    ),
                    models.Index(
                        fields=["customer", "created_at"],
                        name="idx_pos_repay_customer",
                    ),
                    models.Index(
                        fields=["shift", "created_at"], name="idx_pos_repay_shift"
                    ),
                    models.Index(
                        fields=["method", "created_at"], name="idx_pos_repay_method"
                    ),
                    models.Index(
                        fields=["status", "created_at"], name="idx_pos_repay_status"
                    ),
                ],
            },
        ),
    ]
