# Generated by Django 5.2.5 on 2026-07-01 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_pos_customers(apps, schema_editor):
    Customer = apps.get_model("baseinfo", "Customer")
    PosCustomer = apps.get_model("pos", "PosCustomer")
    PosCustomerRepayment = apps.get_model("pos", "PosCustomerRepayment")
    PosSale = apps.get_model("pos", "PosSale")

    sale_pairs = set(
        PosSale.objects.filter(
            selected_customer_id__isnull=False,
            pos_customer_id__isnull=True,
        ).values_list("warehouse_id", "selected_customer_id")
    )
    repayment_pairs = set(
        PosCustomerRepayment.objects.filter(
            customer_id__isnull=False,
            pos_customer_id__isnull=True,
        ).values_list("warehouse_id", "customer_id")
    )
    pairs = sorted(pair for pair in sale_pairs | repayment_pairs if pair[0] and pair[1])
    if not pairs:
        return

    legacy_ids = {customer_id for _, customer_id in pairs}
    legacy_customers = {
        customer.id: customer for customer in Customer.objects.filter(id__in=legacy_ids)
    }
    used_codes = {
        warehouse_id: set(
            PosCustomer.objects.filter(warehouse_id=warehouse_id).values_list(
                "code", flat=True
            )
        )
        for warehouse_id, _ in pairs
    }
    created_by_pair = {}

    for warehouse_id, legacy_id in pairs:
        legacy = legacy_customers.get(legacy_id)
        if not legacy:
            continue
        warehouse_codes = used_codes.setdefault(warehouse_id, set())
        base_code = (getattr(legacy, "code", "") or f"LEGACY-{legacy_id}").strip()
        base_code = base_code[:30] or f"LEGACY-{legacy_id}"
        code = base_code
        suffix = 1
        while code in warehouse_codes:
            suffix_text = f"-{legacy_id}" if suffix == 1 else f"-{legacy_id}-{suffix}"
            code = f"{base_code[: 30 - len(suffix_text)]}{suffix_text}"
            suffix += 1
        warehouse_codes.add(code)

        pos_customer = PosCustomer.objects.create(
            warehouse_id=warehouse_id,
            code=code,
            name=(getattr(legacy, "name", "") or code)[:80],
            contact_person=(getattr(legacy, "contact_person", "") or "")[:80],
            phone=(getattr(legacy, "phone", "") or "")[:30],
            mobile=(getattr(legacy, "mobile", "") or "")[:30],
            address=(getattr(legacy, "address", "") or "")[:255],
            remark=f"由历史终端客户ID {legacy_id} 自动迁移"[:200],
            is_active=True,
        )
        created_by_pair[(warehouse_id, legacy_id)] = pos_customer.id

    for (warehouse_id, legacy_id), pos_customer_id in created_by_pair.items():
        PosSale.objects.filter(
            warehouse_id=warehouse_id,
            selected_customer_id=legacy_id,
            pos_customer_id__isnull=True,
        ).update(pos_customer_id=pos_customer_id)
        PosCustomerRepayment.objects.filter(
            warehouse_id=warehouse_id,
            customer_id=legacy_id,
            pos_customer_id__isnull=True,
        ).update(pos_customer_id=pos_customer_id)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("baseinfo", "0002_initial"),
        ("locations", "0003_clarify_warehouse_subwarehouse_scope"),
        ("pos", "0008_pos_credit_repayment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PosCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, max_length=30, verbose_name="客户编号"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=80, verbose_name="客户名称"
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True, default="", max_length=80, verbose_name="联系人"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="", max_length=30, verbose_name="联系电话"
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True, default="", max_length=30, verbose_name="移动电话"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="地址"
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="备注"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="启用"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "POS客户",
                "verbose_name_plural": "POS客户管理",
                "ordering": ["warehouse_id", "code", "id"],
            },
        ),
        migrations.RemoveIndex(
            model_name="poscustomerrepayment",
            name="idx_pos_repay_customer",
        ),
        migrations.AlterField(
            model_name="poscustomerrepayment",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                help_text="历史兼容字段。新的 POS 客户还款使用 POS客户。",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pos_repayments",
                to="baseinfo.customer",
                verbose_name="历史终端客户",
            ),
        ),
        migrations.AlterField(
            model_name="possale",
            name="selected_customer",
            field=models.ForeignKey(
                blank=True,
                help_text="历史兼容字段。新的 POS 收银客户使用 POS客户。",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pos_sales",
                to="baseinfo.customer",
                verbose_name="历史终端客户",
            ),
        ),
        migrations.AddField(
            model_name="poscustomer",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_pos_customers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AddField(
            model_name="poscustomer",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="updated_pos_customers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="更新人",
            ),
        ),
        migrations.AddField(
            model_name="poscustomer",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pos_customers",
                to="locations.warehouse",
                verbose_name="所属仓库",
            ),
        ),
        migrations.AddField(
            model_name="poscustomerrepayment",
            name="pos_customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="repayments",
                to="pos.poscustomer",
                verbose_name="POS客户",
            ),
        ),
        migrations.AddField(
            model_name="possale",
            name="pos_customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sales",
                to="pos.poscustomer",
                verbose_name="POS客户",
            ),
        ),
        migrations.AddIndex(
            model_name="poscustomerrepayment",
            index=models.Index(
                fields=["pos_customer", "created_at"], name="idx_pos_repay_customer"
            ),
        ),
        migrations.AddIndex(
            model_name="possale",
            index=models.Index(
                fields=["pos_customer", "created_at"], name="idx_pos_sale_customer"
            ),
        ),
        migrations.AddIndex(
            model_name="poscustomer",
            index=models.Index(
                fields=["warehouse", "is_active", "name"],
                name="idx_pos_customer_wh_active",
            ),
        ),
        migrations.AddIndex(
            model_name="poscustomer",
            index=models.Index(
                fields=["warehouse", "phone"], name="idx_pos_customer_phone"
            ),
        ),
        migrations.AddIndex(
            model_name="poscustomer",
            index=models.Index(
                fields=["warehouse", "mobile"], name="idx_pos_customer_mobile"
            ),
        ),
        migrations.RunPython(backfill_pos_customers, noop_reverse),
        migrations.AddConstraint(
            model_name="poscustomer",
            constraint=models.UniqueConstraint(
                fields=("warehouse", "code"), name="ux_pos_customer_wh_code"
            ),
        ),
    ]
