<template>
  <view class="page"><view v-if="canCreate" class="card"><text class="title">{{canManage?'直接下发移库任务':'提交移库申请'}}</text><picker :range="warehouseLabels" @change="selectWarehouse"><view class="picker">{{selectedWarehouse?.name||'选择仓库'}}</view></picker><picker :range="ownerLabels" @change="selectOwner"><view class="picker">{{selectedOwner?.name||'选择货主'}}</view></picker><picker :range="modeLabels" @change="mode=Number($event.detail.value)?'CONTAINER':'LAYER'"><view class="picker">{{mode==='LAYER'?'库存层移库':'整容器移库'}}</view></picker>
    <template v-if="mode==='LAYER'"><picker :range="inventoryLabels" @change="selectedInventory=inventory[Number($event.detail.value)]"><view class="picker">{{selectedInventory?inventoryLabel(selectedInventory):'选择来源库存'}}</view></picker><input v-model="qty" class="input" type="digit" placeholder="移库数量"/></template>
    <template v-else><picker :range="containerLabels" @change="selectedSourceContainer=containers[Number($event.detail.value)]"><view class="picker">{{selectedSourceContainer?.container_no||'选择来源容器'}}</view></picker></template>
    <picker :range="locationLabels" @change="selectedLocation=locations[Number($event.detail.value)]"><view class="picker">{{selectedLocation?.code||'选择目标库位'}}</view></picker>
    <picker v-if="mode==='LAYER'" :range="targetContainerLabels" @change="selectTargetContainer"><view class="picker">{{selectedTargetContainer?.container_no||'目标散件（可选目标容器）'}}</view></picker><picker v-else :range="targetParentLabels" @change="selectTargetParent"><view class="picker">{{selectedTargetParent?.container_no||'不挂入父容器（可选）'}}</view></picker>
    <input v-model="reason" class="input" placeholder="申请原因"/><button type="primary" @click="submit">{{canManage?'直接发布':'提交申请'}}</button></view>
    <text class="section">申请记录</text><view v-for="item in requests" :key="item.id" class="card"><text class="product">{{item.mode}} · {{item.reason}}</text><text class="meta">{{item.status}} · {{item.lines.length}} 行</text><view v-if="item.status==='PENDING'" class="actions"><template v-if="canApprove"><button size="mini" type="primary" @click="approve(item)">批准</button><button size="mini" @click="reject(item)">驳回</button></template><button v-else-if="canRequest" size="mini" @click="cancelRequest(item)">取消</button></view></view>
  </view>
</template>
<script setup>
import{computed,ref}from'vue';import{onShow}from'@dcloudio/uni-app';import{useAuth}from'@/store/auth';import{api}from'@/utils/request'
const auth=useAuth(),mode=ref('LAYER'),owners=ref([]),warehouses=ref([]),inventory=ref([]),locations=ref([]),containers=ref([]),requests=ref([]),selectedOwner=ref(null),selectedWarehouse=ref(null),selectedInventory=ref(null),selectedSourceContainer=ref(null),selectedLocation=ref(null),selectedTargetContainer=ref(null),selectedTargetParent=ref(null),qty=ref(''),reason=ref('')
const canRequest=computed(()=>auth.canRequestRelocation),canApprove=computed(()=>auth.canApproveRelocation),canManage=computed(()=>auth.canManageRelocation),canCreate=computed(()=>canRequest.value||canManage.value),modeLabels=['库存层移库','整容器移库'];const inventoryLabel=r=>`${r.location_code} · ${r.product_name} · 可用${r.available_qty}${r.container_no?' · '+r.container_no:''}`;const ownerLabels=computed(()=>owners.value.map(r=>`${r.code} · ${r.name}`)),warehouseLabels=computed(()=>warehouses.value.map(r=>`${r.code} · ${r.name}`)),inventoryLabels=computed(()=>inventory.value.map(inventoryLabel)),locationLabels=computed(()=>locations.value.map(r=>r.code)),containerLabels=computed(()=>containers.value.map(r=>`${r.container_no} · ${r.location_code||'-'}`)),targetContainers=computed(()=>[null,...containers.value.filter(r=>r.location_id===selectedLocation.value?.id)]),targetContainerLabels=computed(()=>targetContainers.value.map(r=>r?r.container_no:'目标散件')),targetParents=computed(()=>[null,...containers.value.filter(r=>r.location_id===selectedLocation.value?.id&&r.id!==selectedSourceContainer.value?.id)]),targetParentLabels=computed(()=>targetParents.value.map(r=>r?r.container_no:'不挂入父容器'))
function selectTargetContainer(e){selectedTargetContainer.value=targetContainers.value[Number(e.detail.value)]}
function selectTargetParent(e){selectedTargetParent.value=targetParents.value[Number(e.detail.value)]}
function applyOptions(o){owners.value=o.owners||[];warehouses.value=o.warehouses||[];selectedWarehouse.value=warehouses.value.find(r=>r.id===o.warehouse_id)||null;selectedOwner.value=owners.value.find(r=>r.id===o.owner_id)||null;inventory.value=o.inventory||[];locations.value=o.locations||[];containers.value=o.containers||[];selectedInventory.value=null;selectedSourceContainer.value=null;selectedLocation.value=null;selectedTargetContainer.value=null;selectedTargetParent.value=null}
async function refreshOptions(){applyOptions(await api.relocationOptions({warehouse_id:selectedWarehouse.value?.id||'',owner_id:selectedOwner.value?.id||''}))}
async function selectWarehouse(e){selectedWarehouse.value=warehouses.value[Number(e.detail.value)];selectedOwner.value=null;await refreshOptions()}
async function selectOwner(e){selectedOwner.value=owners.value[Number(e.detail.value)];await refreshOptions()}
async function load(){const options=await api.relocationOptions({warehouse_id:auth.user?.warehouse_id||'',owner_id:auth.user?.owner_id||''});applyOptions(options);const data=await api.relocationRequests();requests.value=Array.isArray(data)?data:(data?.results||[])}
async function submit(){if(!selectedOwner.value||!selectedWarehouse.value||!selectedLocation.value||!reason.value.trim()){uni.showToast({title:'请选择货主、仓库、目标库位并填写原因',icon:'none'});return}const base={owner_id:selectedOwner.value.id,warehouse_id:selectedWarehouse.value.id,mode:mode.value,reason:reason.value.trim()};if(mode.value==='LAYER'){if(!selectedInventory.value||Number(qty.value)<=0){uni.showToast({title:'请选择来源库存并填写数量',icon:'none'});return}base.lines=[{inventory_detail_id:selectedInventory.value.id,qty:Number(qty.value),to_location_id:selectedLocation.value.id,to_container_id:selectedTargetContainer.value?.id||null}]}else{if(!selectedSourceContainer.value){uni.showToast({title:'请选择来源容器',icon:'none'});return}base.source_container_id=selectedSourceContainer.value.id;base.to_location_id=selectedLocation.value.id;base.target_parent_container_id=selectedTargetParent.value?.id||null}if(canManage.value)await api.directReleaseRelocation(base);else await api.createRelocationRequest(base);reason.value='';qty.value='';await load()}
async function approve(i){await api.approveRelocationRequest(i.id);await load()}function reject(i){uni.showModal({title:'驳回申请',editable:true,placeholderText:'请输入原因',success:async r=>{if(r.confirm&&r.content){await api.rejectRelocationRequest(i.id,{note:r.content});await load()}}})}async function cancelRequest(i){await api.cancelRelocationRequest(i.id);await load()}
onShow(async()=>{await auth.loadProfile({force:true});await load()})
</script>
<style scoped>
.page{min-height:100vh;padding:24rpx;background:#f5f7fb;box-sizing:border-box}.card{margin-bottom:18rpx;padding:24rpx;background:#fff;border-radius:16rpx}.title,.section,.product{display:block;font-size:30rpx;font-weight:700;color:#172033}.section{margin:28rpx 0 16rpx}.picker,.input{height:72rpx;line-height:72rpx;margin-top:16rpx;padding:0 18rpx;border:1rpx solid #d7dfeb;border-radius:12rpx}.meta{display:block;margin-top:10rpx;color:#65758b;font-size:24rpx}.actions{display:flex;justify-content:flex-end;gap:14rpx;margin-top:16rpx}.actions button{margin:0}button{margin-top:18rpx}
</style>
