# Generated by Django 5.2.5 on 2026-04-24 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("baseinfo", "0002_initial"),
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doc_type", models.CharField(max_length=16)),
                ("biz_date", models.DateField()),
                ("next_no", models.BigIntegerField(default=1)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="baseinfo.owner",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="locations.warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "单据序列",
                "verbose_name_plural": "单据序列",
                "db_table": "doc_sequence",
                "indexes": [
                    models.Index(
                        fields=["doc_type", "biz_date", "warehouse", "owner"],
                        name="ix_docseq_scope",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("doc_type", "biz_date", "warehouse", "owner"),
                        name="uq_docseq_scope",
                    )
                ],
            },
        ),
    ]
