# Generated by Django 5.2.5 on 2025-10-19 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseinfo", "0004_remove_carriercompany_idx_carrier_wh_center_and_more"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="docsequence",
            name="uq_docseq_scope",
        ),
        migrations.RemoveIndex(
            model_name="docsequence",
            name="ix_docseq_scope",
        ),
        migrations.RemoveField(
            model_name="docsequence",
            name="warehouse",
        ),
        migrations.AddIndex(
            model_name="docsequence",
            index=models.Index(
                fields=["doc_type", "biz_date", "owner"], name="ix_docseq_scope"
            ),
        ),
        migrations.AddConstraint(
            model_name="docsequence",
            constraint=models.UniqueConstraint(
                fields=("doc_type", "biz_date", "owner"), name="uq_docseq_scope"
            ),
        ),
    ]
