# Generated by Django 5.2.5 on 2026-03-29 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('locations', '0002_alter_container_warehouse_alter_location_warehouse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docsequence',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.warehouse'),
        ),
    ]
