# Generated by Codex on 2026-07-03

from django.db import migrations, models


def create_default_print_configs(apps, schema_editor):
    PrintConfig = apps.get_model("core", "PrintConfig")
    SystemSetting = apps.get_model("core", "SystemSetting")

    defaults = [
        {
            "code": "pos_dot_241_93",
            "name": "Epson LQ-635KII 三等分 241mm × 93mm",
            "module": "pos_sale",
            "print_method": "frontend_html",
            "printer_type": "dot_matrix",
            "paper_mode": "dot_241_93",
            "paper_width": "241mm",
            "paper_height": "93mm",
            "page_size_css": "241mm 93mm",
            "page_margin": "0",
            "sheet_width": "200mm",
            "sheet_padding_top": "3mm",
            "sheet_padding_right": "0",
            "sheet_padding_bottom": "0",
            "sheet_padding_left": "0",
            "body_font_size": "22px",
            "company_font_size": "36px",
            "title_font_size": "24px",
            "meta_font_size": "22px",
            "table_font_size": "22px",
            "table_header_font_size": "22px",
            "money_font_size": "22px",
            "footer_font_size": "22px",
            "body_line_height": "1.15",
            "meta_line_height": "1.15",
            "table_line_height": "1.05",
            "money_line_height": "1.15",
            "footer_line_height": "1.12",
            "table_cell_padding": "1px 2px",
            "money_gap": "6px",
            "money_margin_top": "5px",
            "is_default": True,
            "is_active": True,
            "sort_order": 10,
            "remark": "POS销售单默认针式三等分连续纸配置。",
        },
        {
            "code": "pos_a4_landscape",
            "name": "A4 激光横向",
            "module": "pos_sale",
            "print_method": "frontend_html",
            "printer_type": "laser",
            "paper_mode": "a4_landscape",
            "paper_width": "A4",
            "paper_height": "landscape",
            "page_size_css": "A4 landscape",
            "page_margin": "0",
            "sheet_width": "98%",
            "sheet_padding_top": "1mm",
            "sheet_padding_right": "4px",
            "sheet_padding_bottom": "0",
            "sheet_padding_left": "4px",
            "body_font_size": "22.5px",
            "company_font_size": "42px",
            "title_font_size": "27px",
            "meta_font_size": "22.5px",
            "table_font_size": "22.5px",
            "table_header_font_size": "22.5px",
            "money_font_size": "22.5px",
            "footer_font_size": "22.5px",
            "body_line_height": "1.2",
            "meta_line_height": "1.2",
            "table_line_height": "1.05",
            "money_line_height": "1.2",
            "footer_line_height": "1.18",
            "table_cell_padding": "1px 3px",
            "money_gap": "14px",
            "money_margin_top": "8px",
            "is_default": False,
            "is_active": True,
            "sort_order": 20,
            "remark": "POS销售单 A4 横向激光打印配置。",
        },
        {
            "code": "pos_dot_9_5_5",
            "name": "Epson LQ-635KII 二等分 241mm × 140mm",
            "module": "pos_sale",
            "print_method": "frontend_html",
            "printer_type": "dot_matrix",
            "paper_mode": "dot_9_5_5",
            "paper_width": "241mm",
            "paper_height": "140mm",
            "page_size_css": "241mm 140mm",
            "page_margin": "0",
            "sheet_width": "200mm",
            "sheet_padding_top": "3mm",
            "sheet_padding_right": "0",
            "sheet_padding_bottom": "0",
            "sheet_padding_left": "0",
            "body_font_size": "22px",
            "company_font_size": "36px",
            "title_font_size": "24px",
            "meta_font_size": "22px",
            "table_font_size": "22px",
            "table_header_font_size": "22px",
            "money_font_size": "22px",
            "footer_font_size": "22px",
            "body_line_height": "1.15",
            "meta_line_height": "1.15",
            "table_line_height": "1.05",
            "money_line_height": "1.15",
            "footer_line_height": "1.12",
            "table_cell_padding": "1px 2px",
            "money_gap": "6px",
            "money_margin_top": "5px",
            "is_default": False,
            "is_active": True,
            "sort_order": 30,
            "remark": "POS销售单针式二等分连续纸配置。",
        },
        {
            "code": "pos_dot_9_5_11",
            "name": "Epson LQ-635KII 整张 241mm × 279mm",
            "module": "pos_sale",
            "print_method": "frontend_html",
            "printer_type": "dot_matrix",
            "paper_mode": "dot_9_5_11",
            "paper_width": "241mm",
            "paper_height": "279mm",
            "page_size_css": "241mm 279mm",
            "page_margin": "0",
            "sheet_width": "200mm",
            "sheet_padding_top": "3mm",
            "sheet_padding_right": "0",
            "sheet_padding_bottom": "0",
            "sheet_padding_left": "0",
            "body_font_size": "22px",
            "company_font_size": "36px",
            "title_font_size": "24px",
            "meta_font_size": "22px",
            "table_font_size": "22px",
            "table_header_font_size": "22px",
            "money_font_size": "22px",
            "footer_font_size": "22px",
            "body_line_height": "1.15",
            "meta_line_height": "1.15",
            "table_line_height": "1.05",
            "money_line_height": "1.15",
            "footer_line_height": "1.12",
            "table_cell_padding": "1px 2px",
            "money_gap": "6px",
            "money_margin_top": "5px",
            "is_default": False,
            "is_active": True,
            "sort_order": 40,
            "remark": "POS销售单针式整张连续纸配置。",
        },
    ]

    for config in defaults:
        code = config.pop("code")
        PrintConfig.objects.update_or_create(code=code, defaults=config)

    SystemSetting.objects.update_or_create(
        namespace="pos",
        key="sale_print_config",
        defaults={
            "name": "POS销售单打印配置",
            "value_type": "string",
            "value": "pos_dot_241_93",
            "default_value": "pos_dot_241_93",
            "description": "POS销售单默认使用的打印配置编码。",
            "client_visible": True,
            "is_active": True,
            "sort_order": 11,
            "options": {
                "model": "core.PrintConfig",
                "module": "pos_sale",
                "field": "code",
            },
        },
    )


def remove_default_print_configs(apps, schema_editor):
    PrintConfig = apps.get_model("core", "PrintConfig")
    SystemSetting = apps.get_model("core", "SystemSetting")
    PrintConfig.objects.filter(
        code__in=[
            "pos_dot_241_93",
            "pos_a4_landscape",
            "pos_dot_9_5_5",
            "pos_dot_9_5_11",
        ]
    ).delete()
    SystemSetting.objects.filter(namespace="pos", key="sale_print_config").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_systemsetting"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrintConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=80, unique=True, verbose_name="配置编码"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="名称")),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("pos_sale", "POS销售单"),
                            ("pos_shift", "POS班次"),
                            ("outbound", "出库单"),
                            ("generic", "通用"),
                        ],
                        db_index=True,
                        default="pos_sale",
                        max_length=30,
                        verbose_name="适用模块",
                    ),
                ),
                (
                    "print_method",
                    models.CharField(
                        choices=[
                            ("frontend_html", "前端HTML打印"),
                            ("backend_html", "后端打印页面"),
                            ("native", "本机/原生打印"),
                        ],
                        default="frontend_html",
                        max_length=30,
                        verbose_name="打印方式",
                    ),
                ),
                (
                    "printer_type",
                    models.CharField(
                        choices=[
                            ("laser", "激光/喷墨"),
                            ("dot_matrix", "针式"),
                            ("thermal", "热敏"),
                            ("other", "其他"),
                        ],
                        default="laser",
                        max_length=30,
                        verbose_name="打印机类型",
                    ),
                ),
                (
                    "paper_mode",
                    models.CharField(
                        default="a4_landscape",
                        max_length=50,
                        verbose_name="前端纸型标识",
                    ),
                ),
                (
                    "paper_width",
                    models.CharField(
                        default="A4", max_length=30, verbose_name="纸张宽度"
                    ),
                ),
                (
                    "paper_height",
                    models.CharField(
                        default="landscape", max_length=30, verbose_name="纸张高度"
                    ),
                ),
                (
                    "page_size_css",
                    models.CharField(
                        default="A4 landscape",
                        max_length=80,
                        verbose_name="CSS纸张尺寸",
                    ),
                ),
                (
                    "page_margin",
                    models.CharField(
                        default="0", max_length=30, verbose_name="页面边距"
                    ),
                ),
                (
                    "sheet_width",
                    models.CharField(
                        default="98%", max_length=30, verbose_name="单据宽度"
                    ),
                ),
                (
                    "sheet_padding_top",
                    models.CharField(
                        default="1mm", max_length=30, verbose_name="上边距"
                    ),
                ),
                (
                    "sheet_padding_right",
                    models.CharField(
                        default="0", max_length=30, verbose_name="右内边距"
                    ),
                ),
                (
                    "sheet_padding_bottom",
                    models.CharField(
                        default="0", max_length=30, verbose_name="下内边距"
                    ),
                ),
                (
                    "sheet_padding_left",
                    models.CharField(
                        default="0", max_length=30, verbose_name="左内边距"
                    ),
                ),
                (
                    "body_font_size",
                    models.CharField(
                        default="22px", max_length=30, verbose_name="正文字号"
                    ),
                ),
                (
                    "company_font_size",
                    models.CharField(
                        default="36px", max_length=30, verbose_name="公司/仓库名字号"
                    ),
                ),
                (
                    "title_font_size",
                    models.CharField(
                        default="24px", max_length=30, verbose_name="标题字号"
                    ),
                ),
                (
                    "meta_font_size",
                    models.CharField(
                        default="22px", max_length=30, verbose_name="单据信息字号"
                    ),
                ),
                (
                    "table_font_size",
                    models.CharField(
                        default="22px", max_length=30, verbose_name="表格字号"
                    ),
                ),
                (
                    "table_header_font_size",
                    models.CharField(
                        default="22px", max_length=30, verbose_name="表头字号"
                    ),
                ),
                (
                    "money_font_size",
                    models.CharField(
                        default="22px", max_length=30, verbose_name="金额汇总字号"
                    ),
                ),
                (
                    "footer_font_size",
                    models.CharField(
                        default="22px", max_length=30, verbose_name="底部信息字号"
                    ),
                ),
                (
                    "body_line_height",
                    models.CharField(
                        default="1.15", max_length=20, verbose_name="正文行高"
                    ),
                ),
                (
                    "meta_line_height",
                    models.CharField(
                        default="1.15", max_length=20, verbose_name="单据信息行高"
                    ),
                ),
                (
                    "table_line_height",
                    models.CharField(
                        default="1.05", max_length=20, verbose_name="表格行高"
                    ),
                ),
                (
                    "money_line_height",
                    models.CharField(
                        default="1.15", max_length=20, verbose_name="金额汇总行高"
                    ),
                ),
                (
                    "footer_line_height",
                    models.CharField(
                        default="1.12", max_length=20, verbose_name="底部信息行高"
                    ),
                ),
                (
                    "table_cell_padding",
                    models.CharField(
                        default="1px 2px",
                        max_length=40,
                        verbose_name="表格单元格内边距",
                    ),
                ),
                (
                    "money_gap",
                    models.CharField(
                        default="6px", max_length=30, verbose_name="金额汇总列间距"
                    ),
                ),
                (
                    "money_margin_top",
                    models.CharField(
                        default="5px", max_length=30, verbose_name="金额汇总上间距"
                    ),
                ),
                (
                    "extra",
                    models.JSONField(blank=True, default=dict, verbose_name="扩展配置"),
                ),
                ("is_default", models.BooleanField(default=False, verbose_name="默认")),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="排序"),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="备注"
                    ),
                ),
            ],
            options={
                "verbose_name": "打印配置",
                "verbose_name_plural": "打印配置",
                "ordering": ("module", "sort_order", "code"),
                "indexes": [
                    models.Index(
                        fields=["module", "is_active", "is_default", "sort_order"],
                        name="idx_printcfg_module",
                    )
                ],
            },
        ),
        migrations.RunPython(
            create_default_print_configs, remove_default_print_configs
        ),
    ]
