# Generated by Django 5.2.5 on 2025-10-19 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_docsequence_uq_docseq_scope_and_more"),
        ("locations", "0002_remove_location_zone"),
    ]

    operations = [
        migrations.AddField(
            model_name="docsequence",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="locations.warehouse",
            ),
        ),
    ]
