# Generated by Django 5.2.5 on 2025-10-19 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseinfo", "0004_remove_carriercompany_idx_carrier_wh_center_and_more"),
        ("core", "0003_docsequence_warehouse"),
        ("locations", "0002_remove_location_zone"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="docsequence",
            name="uq_docseq_scope",
        ),
        migrations.RemoveIndex(
            model_name="docsequence",
            name="ix_docseq_scope",
        ),
        migrations.AlterField(
            model_name="docsequence",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                default=1,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="locations.warehouse",
            ),
        ),
        migrations.AddIndex(
            model_name="docsequence",
            index=models.Index(
                fields=["doc_type", "biz_date", "warehouse", "owner"],
                name="ix_docseq_scope",
            ),
        ),
        migrations.AddConstraint(
            model_name="docsequence",
            constraint=models.UniqueConstraint(
                fields=("doc_type", "biz_date", "warehouse", "owner"),
                name="uq_docseq_scope",
            ),
        ),
    ]
