# Generated by Django 5.2.5 on 2025-10-18 13:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("baseinfo", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="已删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用状态"),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="全局唯一", max_length=50, verbose_name="品牌编码"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="品牌名称")),
                (
                    "remark",
                    models.CharField(blank=True, max_length=255, verbose_name="备注"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "品牌",
                "verbose_name_plural": "品牌",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="已删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用状态"),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="分类唯一编码", max_length=50, verbose_name="分类编码"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="分类名称"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="products.productcategory",
                        verbose_name="上级分类",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品分类",
                "verbose_name_plural": "商品分类",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="已删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用状态"),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="货主内唯一", max_length=50, verbose_name="商品编号"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="商品名称")),
                (
                    "spec",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="规格"
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True,
                        help_text="货主内（有值时）唯一",
                        max_length=50,
                        null=True,
                        verbose_name="SKU编码",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "gtin",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="标准条码(GTIN/EAN/UPC)",
                    ),
                ),
                (
                    "unit_barcode",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="零码"
                    ),
                ),
                (
                    "carton_barcode",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="箱码"
                    ),
                ),
                (
                    "pack_requirement",
                    models.CharField(
                        choices=[
                            ("NONE", "无（不需要打包）"),
                            ("BAG", "袋装/气泡袋"),
                            ("BOX", "装箱"),
                            ("SHRINK", "缠绕/热缩"),
                            ("PALLET", "打托/缠膜"),
                        ],
                        db_index=True,
                        default="NONE",
                        max_length=20,
                        verbose_name="打包要求",
                    ),
                ),
                (
                    "pack_note",
                    models.CharField(
                        blank=True, default="", max_length=120, verbose_name="打包备注"
                    ),
                ),
                (
                    "pick_policy",
                    models.CharField(
                        choices=[
                            ("AUTO", "优先整箱可用则整箱，否则散件"),
                            ("BASE_ONLY", "只允许散件"),
                            ("AUX_ONLY", "只允许整箱(不破箱)"),
                            ("OPTIMIZE", "按效率优化：整箱优先，尾差阈值内散拣"),
                        ],
                        default="AUTO",
                        max_length=12,
                        verbose_name="拣配策略",
                    ),
                ),
                (
                    "break_box_allowed",
                    models.BooleanField(default=True, verbose_name="允许破箱"),
                ),
                (
                    "min_pick_multiple",
                    models.PositiveIntegerField(
                        default=1, verbose_name="最小拣配倍数(基本单位)"
                    ),
                ),
                (
                    "replenish_min",
                    models.PositiveIntegerField(
                        default=0, verbose_name="前置区补货下限(基本单位)"
                    ),
                ),
                (
                    "volume",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=12,
                        null=True,
                        verbose_name="体积(基本单位,m³)",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        verbose_name="重量(基本单位,kg)",
                    ),
                ),
                (
                    "net_content",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        verbose_name="净含量(基本单位,g)",
                    ),
                ),
                (
                    "min_stock",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="最低库存(基本单位)",
                    ),
                ),
                (
                    "max_stock",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="最高库存(基本单位)",
                    ),
                ),
                (
                    "serial_control",
                    models.BooleanField(default=False, verbose_name="序列号管理"),
                ),
                (
                    "batch_control",
                    models.BooleanField(default=False, verbose_name="批次管理"),
                ),
                (
                    "expiry_control",
                    models.BooleanField(default=False, verbose_name="保质期管理"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="products/%Y/%m/%d/"
                    ),
                ),
                (
                    "pricing_strategy",
                    models.CharField(
                        choices=[("WAC", "加权平均法"), ("NEW", "按最新批次")],
                        default="WAC",
                        max_length=20,
                        verbose_name="定价策略",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="价格"
                    ),
                ),
                (
                    "expiry_basis",
                    models.CharField(
                        blank=True,
                        choices=[("MFG", "生产日期"), ("INBOUND", "入库日期")],
                        max_length=10,
                        null=True,
                        verbose_name="效期基准",
                    ),
                ),
                (
                    "shelf_life_days",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="保质期天数"
                    ),
                ),
                (
                    "inbound_valid_days",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="入库有效天数(入库基准)"
                    ),
                ),
                (
                    "expiry_warning_days",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="效期预警阈值(剩余天数)"
                    ),
                ),
                (
                    "fefo_required",
                    models.BooleanField(
                        default=True, verbose_name="FEFO拣选(先到期先出)"
                    ),
                ),
                (
                    "mix_lot_allowed",
                    models.BooleanField(default=False, verbose_name="允许库位混批"),
                ),
                (
                    "mix_expiry_allowed",
                    models.BooleanField(default=False, verbose_name="允许库位混效期"),
                ),
                (
                    "origin_country",
                    models.CharField(
                        blank=True,
                        max_length=2,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{2}$", "必须为两位大写字母的 ISO-2 代码"
                            )
                        ],
                        verbose_name="原产国(ISO-2)",
                    ),
                ),
                (
                    "external_code",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="外部系统编码",
                    ),
                ),
                (
                    "extra",
                    models.JSONField(blank=True, default=dict, verbose_name="扩展属性"),
                ),
                (
                    "material_quality",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="材质"
                    ),
                ),
                (
                    "vender",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="厂家"
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="products.brand",
                        verbose_name="品牌",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="baseinfo.owner",
                        verbose_name="货主",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="products.productcategory",
                        verbose_name="分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品档案",
                "verbose_name_plural": "商品档案",
                "ordering": ["owner", "code"],
            },
        ),
        migrations.CreateModel(
            name="ProductUom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="已删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用状态"),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="EA/PCS/CTN/PLT/KG/L 等",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z0-9_\\-]+$",
                                "仅允许大写字母、数字、下划线、连字符",
                            )
                        ],
                        verbose_name="单位编码",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="单位名称")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("COUNT", "计数"),
                            ("WEIGHT", "重量"),
                            ("VOLUME", "体积"),
                            ("LENGTH", "长度"),
                            ("AREA", "面积"),
                            ("OTHER", "其他"),
                        ],
                        default="COUNT",
                        max_length=12,
                        verbose_name="类型",
                    ),
                ),
                (
                    "decimal_places",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(6)],
                        verbose_name="小数位数",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "计量单位",
                "verbose_name_plural": "计量单位",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ProductPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="已删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用状态"),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
                ("qty_in_base", models.PositiveIntegerField(verbose_name="换算数量")),
                (
                    "barcode",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="层级条码"
                    ),
                ),
                (
                    "length_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="长(cm)",
                    ),
                ),
                (
                    "width_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="宽(cm)",
                    ),
                ),
                (
                    "height_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="高(cm)",
                    ),
                ),
                (
                    "gross_weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="毛重(kg)",
                    ),
                ),
                (
                    "volume_m3",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=12,
                        null=True,
                        verbose_name="体积(m³)",
                    ),
                ),
                (
                    "volume_auto",
                    models.BooleanField(default=True, verbose_name="体积自动计算"),
                ),
                (
                    "volume_m3_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "未校验"),
                            ("CALCULATED", "已计算"),
                            ("MISMATCH", "手输与计算不一致"),
                        ],
                        default="",
                        max_length=12,
                        verbose_name="体积状态",
                    ),
                ),
                (
                    "is_pickable",
                    models.BooleanField(default=False, verbose_name="可直接拣配"),
                ),
                (
                    "is_purchase_default",
                    models.BooleanField(default=False, verbose_name="采购默认单位"),
                ),
                (
                    "is_sales_default",
                    models.BooleanField(default=False, verbose_name="销售默认单位"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="排序"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="packages",
                        to="products.product",
                        verbose_name="商品",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
                (
                    "uom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="packages",
                        to="products.productuom",
                        verbose_name="包装单位",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品包装层级",
                "verbose_name_plural": "商品包装层级",
                "ordering": ["product", "sort_order", "uom"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="base_uom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="as_base_of_products",
                to="products.productuom",
                verbose_name="基本单位",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="replenish_uom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="products.productuom",
                verbose_name="补货单位",
            ),
        ),
        migrations.CreateModel(
            name="TemperatureZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="已删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用状态"),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="温区代码", max_length=20, verbose_name="温区代码"
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="温区名称")),
                (
                    "min_temp",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("-100.00")
                            ),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="最低温度(°C)",
                    ),
                ),
                (
                    "max_temp",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("-100.00")
                            ),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="最高温度(°C)",
                    ),
                ),
                (
                    "storage_condition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AMBIENT", "常温"),
                            ("REFRIGERATED", "冷藏"),
                            ("FROZEN", "冷冻"),
                        ],
                        max_length=20,
                        verbose_name="存储条件",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "温区",
                "verbose_name_plural": "温区",
                "ordering": ["min_temp"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="temperature_zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="products.temperaturezone",
                verbose_name="温度区域",
            ),
        ),
        migrations.AddIndex(
            model_name="brand",
            index=models.Index(
                fields=["is_active", "code"], name="idx_brand_active_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="brand",
            constraint=models.UniqueConstraint(
                fields=("code",), name="uniq_brand_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="brand",
            constraint=models.CheckConstraint(
                condition=models.Q(("code", ""), _negated=True),
                name="chk_brand_code_not_empty",
            ),
        ),
        migrations.AddIndex(
            model_name="productcategory",
            index=models.Index(
                fields=["is_active"], name="products_pr_is_acti_226e74_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productcategory",
            index=models.Index(
                fields=["parent"], name="products_pr_parent__84d628_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="productcategory",
            constraint=models.UniqueConstraint(
                fields=("code",), name="uniq_category_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="productcategory",
            constraint=models.CheckConstraint(
                condition=models.Q(("code", ""), _negated=True),
                name="chk_category_code_not_empty",
            ),
        ),
        migrations.AddIndex(
            model_name="productuom",
            index=models.Index(
                fields=["is_active"], name="products_pr_is_acti_3f8ce0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productuom",
            index=models.Index(fields=["kind"], name="products_pr_kind_ec5dbf_idx"),
        ),
        migrations.AddConstraint(
            model_name="productuom",
            constraint=models.UniqueConstraint(fields=("code",), name="uniq_uom_code"),
        ),
        migrations.AddConstraint(
            model_name="productuom",
            constraint=models.CheckConstraint(
                condition=models.Q(("code", ""), _negated=True),
                name="chk_uom_code_not_empty",
            ),
        ),
        migrations.AddIndex(
            model_name="productpackage",
            index=models.Index(
                fields=["product", "uom"], name="products_pr_product_dce6ca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productpackage",
            index=models.Index(
                fields=["product", "sort_order"], name="idx_pkg_prod_sort"
            ),
        ),
        migrations.AddIndex(
            model_name="productpackage",
            index=models.Index(
                fields=["barcode"], name="products_pr_barcode_23c02f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productpackage",
            index=models.Index(
                fields=["is_active"], name="products_pr_is_acti_75d256_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="productpackage",
            constraint=models.UniqueConstraint(
                fields=("product", "uom"), name="uniq_product_uom"
            ),
        ),
        migrations.AddConstraint(
            model_name="productpackage",
            constraint=models.CheckConstraint(
                condition=models.Q(("qty_in_base__gt", 0)), name="chk_qty_in_base_gt_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="productpackage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("length_cm__isnull", True),
                        ("width_cm__isnull", True),
                        ("height_cm__isnull", True),
                    ),
                    models.Q(
                        ("length_cm__gt", 0), ("width_cm__gt", 0), ("height_cm__gt", 0)
                    ),
                    _connector="OR",
                ),
                name="chk_dims_all_or_none",
            ),
        ),
        migrations.AddConstraint(
            model_name="productpackage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("gross_weight_kg__isnull", True),
                        ("gross_weight_kg__gte", 0),
                        _connector="OR",
                    ),
                    models.Q(
                        ("volume_m3__isnull", True),
                        ("volume_m3__gte", 0),
                        _connector="OR",
                    ),
                ),
                name="chk_nonneg_weight_volume",
            ),
        ),
        migrations.AddConstraint(
            model_name="productpackage",
            constraint=models.UniqueConstraint(
                fields=("product", "barcode"), name="uni_pkg_pro_barcode"
            ),
        ),
        migrations.AddIndex(
            model_name="temperaturezone",
            index=models.Index(
                fields=["is_active"], name="products_te_is_acti_ab62bf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="temperaturezone",
            index=models.Index(
                fields=["min_temp", "max_temp"], name="idx_tempzone_range"
            ),
        ),
        migrations.AddConstraint(
            model_name="temperaturezone",
            constraint=models.UniqueConstraint(
                fields=("code",), name="uniq_tempzone_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="temperaturezone",
            constraint=models.CheckConstraint(
                condition=models.Q(("min_temp__lte", models.F("max_temp"))),
                name="chk_tempzone_min_le_max",
            ),
        ),
        migrations.AddConstraint(
            model_name="temperaturezone",
            constraint=models.CheckConstraint(
                condition=models.Q(("code", ""), _negated=True),
                name="chk_tempzone_code_not_empty",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["owner", "is_active"], name="products_pr_owner_i_0d361b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["temperature_zone"], name="products_pr_tempera_0cc355_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["owner", "name"], name="owner_name_prefix_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category"], name="products_pr_categor_9edb3d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["brand"], name="products_pr_brand_i_dc6890_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["owner", "category", "is_active"], name="owner_category_active"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["owner", "brand", "is_active"], name="owner_brand_active"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["owner", "is_active", "batch_control"],
                name="owner_active_batch_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["owner", "is_active", "expiry_control"],
                name="owner_active_expiry_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(("code", ""), _negated=True),
                name="chk_prod_code_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("owner", "code"), name="uniq_owner_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("owner", "sku"), name="uniq_owner_sku"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("owner", "gtin"), name="uniq_owner_gtin"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("owner", "unit_barcode"), name="uniq_owner_unit_barcode"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("owner", "carton_barcode"), name="uniq_owner_carton_barcode"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("owner", "external_code"), name="uniq_owner_external_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(("min_pick_multiple__gte", 1)),
                name="chk_min_pick_multiple_ge_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("min_stock__isnull", True),
                    ("max_stock__isnull", True),
                    ("min_stock__lt", models.F("max_stock")),
                    _connector="OR",
                ),
                name="chk_min_stock_lt_max",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("pick_policy", "AUX_ONLY"), _negated=True),
                    ("break_box_allowed", False),
                    _connector="OR",
                ),
                name="chk_aux_only_no_break",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("expiry_control", False),
                    ("expiry_basis__isnull", False),
                    _connector="OR",
                ),
                name="chk_expiry_requires_basis",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("expiry_control", False),
                    models.Q(("expiry_basis", "MFG"), ("shelf_life_days__gt", 0)),
                    models.Q(
                        ("expiry_basis", "INBOUND"), ("inbound_valid_days__gt", 0)
                    ),
                    _connector="OR",
                ),
                name="chk_expiry_days_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("expiry_control", False),
                    ("expiry_warning_days__isnull", True),
                    models.Q(
                        ("expiry_basis", "MFG"),
                        ("expiry_warning_days__gt", 0),
                        ("expiry_warning_days__lt", models.F("shelf_life_days")),
                    ),
                    models.Q(
                        ("expiry_basis", "INBOUND"),
                        ("expiry_warning_days__gt", 0),
                        ("expiry_warning_days__lt", models.F("inbound_valid_days")),
                    ),
                    _connector="OR",
                ),
                name="chk_expiry_warning_bounds",
            ),
        ),
    ]
