# Generated by Django 5.2.5 on 2026-06-23 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['owner', 'code'], 'permissions': [('view_all_owner_products', '可查看所有货主商品'), ('manage_all_owner_products', '可处理所有货主商品')], 'verbose_name': '商品档案', 'verbose_name_plural': '商品档案'},
        ),
    ]
