# Generated by Django 5.2.5 on 2025-10-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="expiry_basis",
            field=models.CharField(
                blank=True,
                choices=[("MFG", "生产日期"), ("INBOUND", "入库日期")],
                default="MFG",
                max_length=10,
                null=True,
                verbose_name="效期基准",
            ),
        ),
    ]
