# Generated by Django 5.2.5 on 2025-10-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_expiry_basis"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="max_discount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="最高折扣%"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="min_price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="最低价格"
            ),
            preserve_default=False,
        ),
    ]
