# Generated by Django 5.2.5 on 2026-02-09 15:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_productuom_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productuom",
            name="code",
            field=models.CharField(
                help_text="EA/PCS/CTN/PLT/KG/L 等",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Za-z0-9_\\-\\*]+$",
                        "仅允许字母、数字、下划线、连字符、星号",
                    )
                ],
                verbose_name="单位编码",
            ),
        ),
    ]
