# Generated by Django 5.2.5 on 2025-10-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_max_discount_product_min_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="max_discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="最高折扣%",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="min_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="最低价格",
            ),
        ),
    ]
