# Generated by Django 5.2.5 on 2026-08-07 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productcategory_mall_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(help_text='货主内唯一', max_length=50, verbose_name='货主商品编码'),
        ),
        migrations.AlterField(
            model_name='product',
            name='external_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='外部系统商品编码'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gtin',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='标准贸易条码'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='系统按“货主编码-序号”自动生成，货主内唯一', max_length=50, verbose_name='仓库SKU编码'),
        ),
    ]
