# Generated by Django 5.2.5 on 2025-10-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_product_max_discount_alter_product_min_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(
                default=1,
                help_text="货主内（有值时）唯一",
                max_length=50,
                verbose_name="SKU编码",
            ),
            preserve_default=False,
        ),
    ]
