# Generated by Django 5.2.5 on 2025-10-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_product_sku"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="batch_control",
            field=models.BooleanField(default=True, verbose_name="批次管理"),
        ),
        migrations.AlterField(
            model_name="product",
            name="expiry_control",
            field=models.BooleanField(default=True, verbose_name="保质期管理"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/%Y/%m/%d/",
                verbose_name="商品图片",
            ),
        ),
    ]
