# Generated by Django 5.2.5 on 2025-10-24 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_alter_product_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="image",
            new_name="product_image",
        ),
    ]
