# Generated by Django 5.2.5 on 2025-10-25 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_rename_image_product_product_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="productpackage",
            name="is_purchase_default",
            field=models.BooleanField(default=False, verbose_name="采购辅助单位"),
        ),
        migrations.AlterField(
            model_name="productpackage",
            name="is_sales_default",
            field=models.BooleanField(default=False, verbose_name="销售辅助单位"),
        ),
        migrations.AlterField(
            model_name="productpackage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="packages",
                related_query_name="product_package",
                to="products.product",
                verbose_name="商品",
            ),
        ),
        migrations.AddConstraint(
            model_name="productpackage",
            constraint=models.UniqueConstraint(
                fields=("product", "is_purchase_default"),
                name="uniproduct_purchasedefault",
            ),
        ),
        migrations.AddConstraint(
            model_name="productpackage",
            constraint=models.UniqueConstraint(
                fields=("product", "is_sales_default"), name="uniproduct_salesdefault"
            ),
        ),
    ]
