# Generated by Django 5.2.5 on 2026-08-08 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _normalize(value):
    return str(value).strip().upper() if value not in (None, "") else ""


def audit_identifier_history(apps, schema_editor):
    """Fail before schema changes when legacy identifiers cannot be migrated."""
    Product = apps.get_model("products", "Product")
    Package = apps.get_model("products", "ProductPackage")
    claims = {}
    conflicts = []

    def claim(owner_id, product_id, value, source, semantic=(None, 1)):
        normalized = _normalize(value)
        if not normalized:
            return
        key = (owner_id, normalized)
        previous = claims.get(key)
        if previous is None:
            claims[key] = (product_id, semantic, source)
            return
        previous_product, previous_semantic, previous_source = previous
        if previous_product != product_id:
            conflicts.append(
                f"货主={owner_id} 值={normalized} 商品={product_id} 来源={source} "
                f"与商品={previous_product} 来源={previous_source}冲突"
            )
        elif previous_semantic != semantic:
            conflicts.append(
                f"货主={owner_id} 值={normalized} 商品={product_id} "
                f"来源={source}/{previous_source} 包装换算语义冲突"
            )

    packages = {
        package.pk: package for package in Package._base_manager.all().iterator()
    }
    for product in Product._base_manager.all().iterator():
        for field in ("code", "sku", "gtin", "unit_barcode", "external_code"):
            claim(product.owner_id, product.pk, getattr(product, field), field)
        if product.carton_barcode:
            package = packages.get(product.carton_package_id)
            if package is None or package.product_id != product.pk:
                conflicts.append(
                    f"货主={product.owner_id} 商品={product.pk} "
                    f"箱码={product.carton_barcode} 未绑定本商品包装层级"
                )
            else:
                claim(
                    product.owner_id,
                    product.pk,
                    product.carton_barcode,
                    "carton_barcode",
                    (package.pk, package.qty_in_base),
                )
    for package in packages.values():
        if not package.barcode:
            continue
        product = Product._base_manager.get(pk=package.product_id)
        claim(
            product.owner_id,
            product.pk,
            package.barcode,
            f"package:{package.pk}",
            (package.pk, package.qty_in_base),
        )

    if conflicts:
        raise RuntimeError(
            "商品标识历史迁移前审计失败，需先清洗以下冲突：\n"
            + "\n".join(conflicts[:100])
        )


def backfill_identifier_history(apps, schema_editor):
    Product = apps.get_model("products", "Product")
    Package = apps.get_model("products", "ProductPackage")
    Barcode = apps.get_model("products", "ProductBarcode")
    External = apps.get_model("products", "ProductExternalIdentifier")
    Registry = apps.get_model("products", "ProductIdentifierRegistry")
    conflicts = []
    semantic_seen = {}

    def reserve(owner_id, product_id, value, source, semantic=(None, 1)):
        normalized = _normalize(value)
        if not normalized:
            return normalized
        key = (owner_id, normalized)
        previous = semantic_seen.get(key)
        if previous and previous[0] == product_id and previous[1] != semantic:
            conflicts.append(
                f"货主={owner_id} 值={normalized} 商品={product_id} "
                f"来源={source}/{previous[2]} 包装换算语义冲突"
            )
        semantic_seen.setdefault(key, (product_id, semantic, source))
        existing = Registry.objects.filter(
            owner_id=owner_id, normalized_value=normalized
        ).first()
        if existing and existing.product_id != product_id:
            conflicts.append(
                f"货主={owner_id} 值={normalized} 商品={product_id} 来源={source} "
                f"与商品={existing.product_id}冲突"
            )
        elif not existing:
            Registry.objects.create(
                owner_id=owner_id,
                product_id=product_id,
                normalized_value=normalized,
            )
        return normalized

    for product in Product._base_manager.all().iterator():
        reserve(product.owner_id, product.pk, product.code, "code")
        reserve(product.owner_id, product.pk, product.sku, "sku")
        for field, barcode_type in (
            ("gtin", "GTIN"),
            ("unit_barcode", "UNIT"),
            ("carton_barcode", "CARTON"),
        ):
            value = getattr(product, field)
            if not value:
                continue
            package_id = product.carton_package_id if barcode_type == "CARTON" else None
            if barcode_type == "CARTON" and not package_id:
                conflicts.append(
                    f"货主={product.owner_id} 商品={product.pk} 箱码={value} 未绑定包装层级"
                )
                continue
            qty = 1
            if package_id:
                package = Package._base_manager.get(pk=package_id)
                qty = package.qty_in_base
            normalized = reserve(
                product.owner_id, product.pk, value, field, (package_id, qty)
            )
            Barcode.objects.create(
                owner_id=product.owner_id,
                product_id=product.pk,
                barcode=str(value).strip(),
                normalized_value=normalized,
                barcode_type=barcode_type,
                package_id=package_id,
                qty_in_base=qty,
                is_primary=True,
            )
        if product.external_code:
            normalized = reserve(
                product.owner_id, product.pk, product.external_code, "external_code"
            )
            External.objects.create(
                owner_id=product.owner_id,
                product_id=product.pk,
                source_system="LEGACY",
                external_code=str(product.external_code).strip(),
                normalized_value=normalized,
                is_primary=True,
            )

    for package in (
        Package._base_manager.exclude(barcode__isnull=True)
        .exclude(barcode="")
        .iterator()
    ):
        product = Product._base_manager.get(pk=package.product_id)
        normalized = reserve(
            product.owner_id,
            product.pk,
            package.barcode,
            f"package:{package.pk}",
            (package.pk, package.qty_in_base),
        )
        Barcode.objects.create(
            owner_id=product.owner_id,
            product_id=product.pk,
            barcode=str(package.barcode).strip(),
            normalized_value=normalized,
            barcode_type="PACKAGE",
            package_id=package.pk,
            qty_in_base=package.qty_in_base,
            is_primary=True,
            is_active=package.is_active,
            is_deleted=package.is_deleted,
            deleted_at=package.deleted_at,
        )

    if conflicts:
        raise RuntimeError(
            "商品标识历史回填失败，需先清洗以下冲突：\n" + "\n".join(conflicts[:100])
        )


class Migration(migrations.Migration):

    dependencies = [
        ("baseinfo", "0005_ownerwarehousebinding"),
        ("products", "0008_product_carton_package"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(audit_identifier_history, migrations.RunPython.noop),
        migrations.CreateModel(
            name="ProductBarcode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="已删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用状态"),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
                ("barcode", models.CharField(max_length=50, verbose_name="条码")),
                (
                    "normalized_value",
                    models.CharField(
                        editable=False, max_length=50, verbose_name="标准化条码"
                    ),
                ),
                (
                    "barcode_type",
                    models.CharField(
                        choices=[
                            ("GTIN", "标准贸易条码"),
                            ("UNIT", "零码"),
                            ("CARTON", "箱码"),
                            ("PACKAGE", "包装层级条码"),
                            ("OTHER", "其他条码"),
                        ],
                        max_length=12,
                        verbose_name="条码类型",
                    ),
                ),
                (
                    "qty_in_base",
                    models.PositiveIntegerField(
                        default=1, verbose_name="基础单位换算快照"
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="主条码"),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="生效时间"
                    ),
                ),
                (
                    "valid_to",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="失效时间"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_barcodes",
                        to="baseinfo.owner",
                        verbose_name="货主",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="barcode_records",
                        to="products.productpackage",
                        verbose_name="包装层级",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="barcodes",
                        to="products.product",
                        verbose_name="商品",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品条码",
                "verbose_name_plural": "商品条码",
                "ordering": (
                    "product",
                    "barcode_type",
                    "package_id",
                    "-is_primary",
                    "id",
                ),
                "indexes": [
                    models.Index(
                        fields=["owner", "normalized_value"],
                        name="products_pr_owner_i_421bf5_idx",
                    ),
                    models.Index(
                        fields=["product", "barcode_type", "is_active"],
                        name="products_pr_product_a39367_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_deleted", False), ("is_primary", True)),
                        fields=("product", "barcode_type", "package"),
                        name="uniq_primary_product_barcode_scope",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("qty_in_base__gt", 0)),
                        name="chk_product_barcode_qty_gt_0",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("valid_from__isnull", True),
                            ("valid_to__isnull", True),
                            ("valid_from__lte", models.F("valid_to")),
                            _connector="OR",
                        ),
                        name="chk_product_barcode_valid_range",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductExternalIdentifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="已删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用状态"),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "source_system",
                    models.CharField(max_length=50, verbose_name="来源系统"),
                ),
                (
                    "external_code",
                    models.CharField(max_length=50, verbose_name="外部系统商品编码"),
                ),
                (
                    "normalized_value",
                    models.CharField(
                        editable=False, max_length=50, verbose_name="标准化外部编码"
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="主标识"),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="生效时间"
                    ),
                ),
                (
                    "valid_to",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="失效时间"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_external_identifiers",
                        to="baseinfo.owner",
                        verbose_name="货主",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="external_identifiers",
                        to="products.product",
                        verbose_name="商品",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品外部标识",
                "verbose_name_plural": "商品外部标识",
                "ordering": ("product", "source_system", "-is_primary", "id"),
                "indexes": [
                    models.Index(
                        fields=["owner", "normalized_value"],
                        name="products_pr_owner_i_3ecdfa_idx",
                    ),
                    models.Index(
                        fields=["product", "source_system", "is_active"],
                        name="products_pr_product_467ff5_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_deleted", False), ("is_primary", True)),
                        fields=("product", "source_system"),
                        name="uniq_primary_external_identifier_source",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("valid_from__isnull", True),
                            ("valid_to__isnull", True),
                            ("valid_from__lte", models.F("valid_to")),
                            _connector="OR",
                        ),
                        name="chk_external_identifier_valid_range",
                    ),
                ],
            },
        ),
        migrations.RunPython(backfill_identifier_history, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="productidentifierregistry",
            name="product_package",
        ),
    ]
