# Generated by Django 5.2.5 on 2026-02-07 17:30

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_alter_productpackage_is_purchase_default_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="productpackage",
            name="uniproduct_purchasedefault",
        ),
        migrations.RemoveConstraint(
            model_name="productpackage",
            name="uniproduct_salesdefault",
        ),
        migrations.AlterField(
            model_name="productpackage",
            name="is_purchase_default",
            field=models.BooleanField(
                blank=True, default=None, null=True, verbose_name="采购辅助单位"
            ),
        ),
        migrations.AlterField(
            model_name="productpackage",
            name="is_sales_default",
            field=models.BooleanField(
                blank=True, default=None, null=True, verbose_name="销售辅助单位"
            ),
        ),
        migrations.AlterField(
            model_name="productuom",
            name="code",
            field=models.CharField(
                help_text="EA/PCS/CTN/PLT/KG/L 等",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Za-z0-9_\\-]+$", "仅允许字母、数字、下划线、连字符"
                    )
                ],
                verbose_name="单位编码",
            ),
        ),
        migrations.AddConstraint(
            model_name="productpackage",
            constraint=models.UniqueConstraint(
                fields=("product", "is_purchase_default", "is_deleted"),
                name="uniq_prod_purchase_default_true",
            ),
        ),
        migrations.AddConstraint(
            model_name="productpackage",
            constraint=models.UniqueConstraint(
                fields=("product", "is_sales_default", "is_deleted"),
                name="uniq_prod_sales_default_true",
            ),
        ),
    ]
