# Generated by Django 5.2.5 on 2026-08-08 12:22

from django.conf import settings
from django.db import migrations, models


def backfill_primary_scopes(apps, schema_editor):
    Barcode = apps.get_model("products", "ProductBarcode")
    External = apps.get_model("products", "ProductExternalIdentifier")
    for record in Barcode.objects.filter(is_primary=True).iterator():
        record.primary_scope = f"{record.barcode_type}:{record.package_id or 0}"
        record.save(update_fields=["primary_scope"])
    for record in External.objects.filter(is_primary=True).iterator():
        record.primary_scope = record.source_system
        record.save(update_fields=["primary_scope"])


class Migration(migrations.Migration):

    dependencies = [
        ("baseinfo", "0005_ownerwarehousebinding"),
        ("products", "0009_remove_productidentifierregistry_product_package_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="productbarcode",
            name="uniq_primary_product_barcode_scope",
        ),
        migrations.RemoveConstraint(
            model_name="productexternalidentifier",
            name="uniq_primary_external_identifier_source",
        ),
        migrations.AddField(
            model_name="productbarcode",
            name="primary_scope",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=40,
                null=True,
                verbose_name="主码唯一范围",
            ),
        ),
        migrations.AddField(
            model_name="productexternalidentifier",
            name="primary_scope",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=50,
                null=True,
                verbose_name="主标识唯一范围",
            ),
        ),
        migrations.RunPython(backfill_primary_scopes, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="productbarcode",
            constraint=models.UniqueConstraint(
                fields=("product", "primary_scope"),
                name="uniq_primary_product_barcode_scope",
            ),
        ),
        migrations.AddConstraint(
            model_name="productexternalidentifier",
            constraint=models.UniqueConstraint(
                fields=("product", "primary_scope"),
                name="uniq_primary_external_identifier_source",
            ),
        ),
    ]
