# Generated by Django 5.2.5 on 2026-06-28 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0002_initial'),
        ('outbound', '0002_initial'),
        ('products', '0002_add_cross_owner_product_permissions'),
        ('salesapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniProgramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用状态')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('openid', models.CharField(blank=True, default='', max_length=128)),
                ('unionid', models.CharField(blank=True, default='', max_length=128)),
                ('nickname', models.CharField(blank=True, default='', max_length=80)),
                ('avatar_url', models.CharField(blank=True, default='', max_length=500)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mini_program_users', to='baseinfo.customer')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='删除人')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mini_program_users', to='baseinfo.owner')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mini_program_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MiniCustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用状态')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('contact', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=40)),
                ('province', models.CharField(blank=True, default='', max_length=30)),
                ('city', models.CharField(blank=True, default='', max_length=30)),
                ('district', models.CharField(blank=True, default='', max_length=30)),
                ('detail', models.CharField(max_length=200)),
                ('is_default', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mini_addresses', to='baseinfo.customer')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='删除人')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mini_customer_addresses', to='baseinfo.owner')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
                ('buyer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='salesapp.miniprogramuser')),
            ],
        ),
        migrations.CreateModel(
            name='SaleMiniBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用状态')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('title', models.CharField(max_length=120)),
                ('image_url', models.CharField(max_length=500)),
                ('link_type', models.CharField(blank=True, default='', max_length=30)),
                ('link_value', models.CharField(blank=True, default='', max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='删除人')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_mini_banners', to='baseinfo.owner')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SaleMiniOrderMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用状态')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('payment_status', models.CharField(choices=[('OFFLINE', '线下付款'), ('UNPAID', '待付款'), ('PAID', '已付款'), ('REFUNDING', '退款中'), ('REFUNDED', '已退款')], default='OFFLINE', max_length=12)),
                ('source', models.CharField(default='sale-mini', max_length=30)),
                ('buyer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_mappings', to='salesapp.miniprogramuser')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_mini_order_mappings', to='baseinfo.customer')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='删除人')),
                ('outbound_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sale_mini_mapping', to='outbound.outboundorder')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_mini_order_mappings', to='baseinfo.owner')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
        ),
        migrations.CreateModel(
            name='SaleProductConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用状态')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('market_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('is_listed', models.BooleanField(default=False)),
                ('is_recommended', models.BooleanField(default=False)),
                ('is_hot', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('stock_display', models.CharField(choices=[('STATUS', '库存状态'), ('EXACT', '准确库存'), ('HIDDEN', '不展示库存')], default='STATUS', max_length=12)),
                ('min_order_qty', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('max_order_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('multiple_qty', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='删除人')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_product_configs', to='baseinfo.owner')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_mini_configs', to='products.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'ordering': ['sort_order', 'product__code'],
            },
        ),
        migrations.AddIndex(
            model_name='miniprogramuser',
            index=models.Index(fields=['owner', 'customer'], name='salesapp_mi_owner_i_4b2a3e_idx'),
        ),
        migrations.AddIndex(
            model_name='miniprogramuser',
            index=models.Index(fields=['openid'], name='salesapp_mi_openid_4ac33b_idx'),
        ),
        migrations.AddConstraint(
            model_name='miniprogramuser',
            constraint=models.UniqueConstraint(fields=('owner', 'user'), name='ux_mini_owner_user'),
        ),
        migrations.AddIndex(
            model_name='minicustomeraddress',
            index=models.Index(fields=['owner', 'customer', 'is_default'], name='salesapp_mi_owner_i_fec68a_idx'),
        ),
        migrations.AddIndex(
            model_name='minicustomeraddress',
            index=models.Index(fields=['buyer_user', 'is_default'], name='salesapp_mi_buyer_u_d7055e_idx'),
        ),
        migrations.AddIndex(
            model_name='saleminibanner',
            index=models.Index(fields=['owner', 'is_active', 'sort_order'], name='salesapp_sa_owner_i_82e95f_idx'),
        ),
        migrations.AddIndex(
            model_name='saleminiordermapping',
            index=models.Index(fields=['owner', 'customer', 'created_at'], name='salesapp_sa_owner_i_a7f957_idx'),
        ),
        migrations.AddIndex(
            model_name='saleminiordermapping',
            index=models.Index(fields=['payment_status'], name='salesapp_sa_payment_e70d4b_idx'),
        ),
        migrations.AddIndex(
            model_name='saleproductconfig',
            index=models.Index(fields=['owner', 'is_listed', 'is_active'], name='salesapp_sa_owner_i_7ee4bd_idx'),
        ),
        migrations.AddIndex(
            model_name='saleproductconfig',
            index=models.Index(fields=['owner', 'is_recommended', 'sort_order'], name='salesapp_sa_owner_i_ec94c2_idx'),
        ),
        migrations.AddIndex(
            model_name='saleproductconfig',
            index=models.Index(fields=['owner', 'is_hot', 'sort_order'], name='salesapp_sa_owner_i_2bd0fd_idx'),
        ),
        migrations.AddConstraint(
            model_name='saleproductconfig',
            constraint=models.UniqueConstraint(fields=('owner', 'product'), name='ux_sale_cfg_owner_product'),
        ),
        migrations.AddConstraint(
            model_name='saleproductconfig',
            constraint=models.CheckConstraint(condition=models.Q(('min_order_qty__gt', 0)), name='ck_sale_cfg_min_qty_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='saleproductconfig',
            constraint=models.CheckConstraint(condition=models.Q(('multiple_qty__gt', 0)), name='ck_sale_cfg_multiple_gt_0'),
        ),
    ]
