# Generated by Django 5.2.5 on 2026-06-28 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0002_initial'),
        ('products', '0002_add_cross_owner_product_permissions'),
        ('salesapp', '0002_miniprogramuser_minicustomeraddress_saleminibanner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleMiniCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用状态')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('buyer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carts', to='salesapp.miniprogramuser')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_mini_carts', to='baseinfo.customer')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='删除人')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_mini_carts', to='baseinfo.owner')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
        ),
        migrations.CreateModel(
            name='SaleMiniCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用状态')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('order_uom', models.CharField(max_length=32)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='salesapp.saleminicart')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='删除人')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_mini_cart_items', to='products.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='saleminicart',
            index=models.Index(fields=['owner', 'customer', 'is_active'], name='salesapp_sa_owner_i_3a86e9_idx'),
        ),
        migrations.AddIndex(
            model_name='saleminicart',
            index=models.Index(fields=['buyer_user', 'is_active'], name='salesapp_sa_buyer_u_100ffc_idx'),
        ),
        migrations.AddConstraint(
            model_name='saleminicart',
            constraint=models.UniqueConstraint(fields=('owner', 'customer', 'buyer_user'), name='ux_sale_mini_cart_scope'),
        ),
        migrations.AddIndex(
            model_name='saleminicartitem',
            index=models.Index(fields=['cart', 'product'], name='salesapp_sa_cart_id_8b96fe_idx'),
        ),
        migrations.AddIndex(
            model_name='saleminicartitem',
            index=models.Index(fields=['product', 'order_uom'], name='salesapp_sa_product_eb58a6_idx'),
        ),
        migrations.AddConstraint(
            model_name='saleminicartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'product', 'order_uom'), name='ux_sale_mini_cart_item'),
        ),
        migrations.AddConstraint(
            model_name='saleminicartitem',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gt', 0)), name='ck_sale_mini_cart_qty_gt_0'),
        ),
    ]
