# Generated by Django 5.2.5 on 2026-06-28 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0002_initial'),
        ('outbound', '0002_initial'),
        ('salesapp', '0003_saleminicart_saleminicartitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleMiniPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用状态')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('payment_no', models.CharField(max_length=64, unique=True)),
                ('out_trade_no', models.CharField(max_length=64, unique=True)),
                ('channel', models.CharField(choices=[('WECHAT_JSAPI', '微信小程序支付')], default='WECHAT_JSAPI', max_length=20)),
                ('status', models.CharField(choices=[('CREATED', '已创建'), ('PREPAY', '已预下单'), ('PAID', '已支付'), ('CLOSED', '已关闭'), ('REFUNDING', '退款中'), ('REFUNDED', '已退款'), ('FAILED', '失败')], default='CREATED', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('amount_cents', models.PositiveIntegerField()),
                ('currency', models.CharField(default='CNY', max_length=8)),
                ('prepay_id', models.CharField(blank=True, default='', max_length=128)),
                ('transaction_id', models.CharField(blank=True, default='', max_length=128)),
                ('trade_state', models.CharField(blank=True, default='', max_length=40)),
                ('trade_state_desc', models.CharField(blank=True, default='', max_length=200)),
                ('client_pay_params', models.JSONField(blank=True, default=dict)),
                ('prepay_response', models.JSONField(blank=True, default=dict)),
                ('callback_payload', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaleMiniPaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用状态')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('event_id', models.CharField(max_length=128, unique=True)),
                ('event_type', models.CharField(max_length=80)),
                ('resource_type', models.CharField(blank=True, default='', max_length=80)),
                ('out_trade_no', models.CharField(blank=True, default='', max_length=64)),
                ('out_refund_no', models.CharField(blank=True, default='', max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('decrypted_payload', models.JSONField(blank=True, default=dict)),
                ('process_status', models.CharField(choices=[('PENDING', '待处理'), ('PROCESSED', '已处理'), ('FAILED', '处理失败')], default='PENDING', max_length=20)),
                ('error_message', models.CharField(blank=True, default='', max_length=300)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaleMiniRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用状态')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('refund_no', models.CharField(max_length=64, unique=True)),
                ('out_refund_no', models.CharField(max_length=64, unique=True)),
                ('refund_id', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('CREATED', '已创建'), ('PROCESSING', '处理中'), ('SUCCESS', '退款成功'), ('ABNORMAL', '退款异常'), ('CLOSED', '已关闭'), ('FAILED', '失败')], default='CREATED', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('amount_cents', models.PositiveIntegerField()),
                ('total_amount_cents', models.PositiveIntegerField()),
                ('currency', models.CharField(default='CNY', max_length=8)),
                ('reason', models.CharField(blank=True, default='', max_length=120)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('callback_payload', models.JSONField(blank=True, default=dict)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('success_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='saleminiordermapping',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saleminiordermapping',
            name='pay_deadline_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saleminiordermapping',
            name='payment_status',
            field=models.CharField(choices=[('OFFLINE', '线下付款'), ('UNPAID', '待付款'), ('PAID', '已付款'), ('REFUNDING', '退款中'), ('REFUNDED', '已退款'), ('CANCELLED', '已取消')], default='OFFLINE', max_length=20),
        ),
        migrations.AddIndex(
            model_name='saleminiordermapping',
            index=models.Index(fields=['payment_status', 'pay_deadline_at'], name='salesapp_sa_payment_1e0fbf_idx'),
        ),
        migrations.AddField(
            model_name='saleminipayment',
            name='buyer_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='salesapp.miniprogramuser'),
        ),
        migrations.AddField(
            model_name='saleminipayment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='saleminipayment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_mini_payments', to='baseinfo.customer'),
        ),
        migrations.AddField(
            model_name='saleminipayment',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='删除人'),
        ),
        migrations.AddField(
            model_name='saleminipayment',
            name='mapping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='salesapp.saleminiordermapping'),
        ),
        migrations.AddField(
            model_name='saleminipayment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_mini_payments', to='baseinfo.owner'),
        ),
        migrations.AddField(
            model_name='saleminipayment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='saleminipaymentevent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='saleminipaymentevent',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='删除人'),
        ),
        migrations.AddField(
            model_name='saleminipaymentevent',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='salesapp.saleminipayment'),
        ),
        migrations.AddField(
            model_name='saleminipaymentevent',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='saleminirefund',
            name='buyer_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='salesapp.miniprogramuser'),
        ),
        migrations.AddField(
            model_name='saleminirefund',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='saleminirefund',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_mini_refunds', to='baseinfo.customer'),
        ),
        migrations.AddField(
            model_name='saleminirefund',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='删除人'),
        ),
        migrations.AddField(
            model_name='saleminirefund',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_mini_refunds', to='baseinfo.owner'),
        ),
        migrations.AddField(
            model_name='saleminirefund',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='salesapp.saleminipayment'),
        ),
        migrations.AddField(
            model_name='saleminirefund',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='saleminipaymentevent',
            name='refund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='salesapp.saleminirefund'),
        ),
        migrations.AddIndex(
            model_name='saleminipayment',
            index=models.Index(fields=['owner', 'status', 'created_at'], name='salesapp_sa_owner_i_3ce9fa_idx'),
        ),
        migrations.AddIndex(
            model_name='saleminipayment',
            index=models.Index(fields=['mapping', 'status'], name='salesapp_sa_mapping_48a03c_idx'),
        ),
        migrations.AddIndex(
            model_name='saleminipayment',
            index=models.Index(fields=['transaction_id'], name='salesapp_sa_transac_ae0013_idx'),
        ),
        migrations.AddIndex(
            model_name='saleminirefund',
            index=models.Index(fields=['owner', 'status', 'created_at'], name='salesapp_sa_owner_i_8c37b3_idx'),
        ),
        migrations.AddIndex(
            model_name='saleminirefund',
            index=models.Index(fields=['payment', 'status'], name='salesapp_sa_payment_121901_idx'),
        ),
        migrations.AddIndex(
            model_name='saleminirefund',
            index=models.Index(fields=['refund_id'], name='salesapp_sa_refund__be6cea_idx'),
        ),
        migrations.AddIndex(
            model_name='saleminipaymentevent',
            index=models.Index(fields=['event_type', 'created_at'], name='salesapp_sa_event_t_a1db71_idx'),
        ),
        migrations.AddIndex(
            model_name='saleminipaymentevent',
            index=models.Index(fields=['out_trade_no'], name='salesapp_sa_out_tra_7215d2_idx'),
        ),
        migrations.AddIndex(
            model_name='saleminipaymentevent',
            index=models.Index(fields=['out_refund_no'], name='salesapp_sa_out_ref_2c4d9d_idx'),
        ),
        migrations.AddIndex(
            model_name='saleminipaymentevent',
            index=models.Index(fields=['process_status'], name='salesapp_sa_process_f39fe4_idx'),
        ),
    ]
