# Generated by Django 5.2.5 on 2026-06-28 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseinfo", "0002_initial"),
        ("outbound", "0002_initial"),
        (
            "salesapp",
            "0004_saleminipayment_saleminipaymentevent_saleminirefund_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SaleMiniCoupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="已删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用状态"),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
                ("coupon_no", models.CharField(max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "可用"),
                            ("LOCKED", "已锁定"),
                            ("USED", "已使用"),
                            ("RELEASED", "已释放"),
                            ("EXPIRED", "已过期"),
                            ("VOID", "已作废"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                    ),
                ),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SaleMiniCouponTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="已删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用状态"),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
                ("code", models.CharField(max_length=64)),
                ("title", models.CharField(max_length=120)),
                (
                    "coupon_type",
                    models.CharField(
                        choices=[("AMOUNT", "金额券")], default="AMOUNT", max_length=20
                    ),
                ),
                (
                    "threshold_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                (
                    "total_limit",
                    models.PositiveIntegerField(default=0, help_text="0 表示不限量"),
                ),
                (
                    "per_customer_limit",
                    models.PositiveIntegerField(default=0, help_text="0 表示不限量"),
                ),
                ("is_stackable", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="SaleMiniDistributionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="已删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用状态"),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待结算"),
                            ("SETTLED", "已结算"),
                            ("REVERSED", "已冲销"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(decimal_places=4, default=0, max_digits=7),
                ),
                (
                    "base_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "commission_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                ("reversed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SaleMiniOrderAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="已删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用状态"),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
                ("adjustment_no", models.CharField(max_length=64, unique=True)),
                (
                    "adjustment_type",
                    models.CharField(
                        choices=[
                            ("DISCOUNT_STEP", "满减"),
                            ("COUPON", "优惠券"),
                            ("POINTS", "积分抵扣"),
                            ("MANUAL", "人工调整"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PREVIEW", "预览"),
                            ("LOCKED", "已锁定"),
                            ("CONFIRMED", "已确认"),
                            ("RELEASED", "已释放"),
                            ("REVERSED", "已冲销"),
                        ],
                        default="PREVIEW",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="有符号调整金额，负数表示减少应付。",
                        max_digits=18,
                    ),
                ),
                (
                    "source_model",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                ("source_id", models.CharField(blank=True, default="", max_length=80)),
                (
                    "source_code",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SaleMiniPointLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="已删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用状态"),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
                ("tx_no", models.CharField(max_length=64, unique=True)),
                (
                    "tx_type",
                    models.CharField(
                        choices=[
                            ("EARN", "获得"),
                            ("FREEZE", "冻结"),
                            ("CONSUME", "消耗"),
                            ("RELEASE", "释放"),
                            ("REFUND", "退回"),
                            ("ADJUST", "调整"),
                        ],
                        max_length=20,
                    ),
                ),
                ("points_delta", models.IntegerField(default=0)),
                ("frozen_delta", models.IntegerField(default=0)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("note", models.CharField(blank=True, default="", max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name="saleminiordermapping",
            name="adjustment_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="订单级调整金额，负数表示优惠，正数表示加价。",
                max_digits=18,
            ),
        ),
        migrations.AddField(
            model_name="saleminiordermapping",
            name="goods_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="saleminiordermapping",
            name="payable_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddIndex(
            model_name="saleminiordermapping",
            index=models.Index(
                fields=["owner", "payable_amount"],
                name="salesapp_sa_owner_i_4f9d39_idx",
            ),
        ),
        migrations.AddField(
            model_name="saleminicoupon",
            name="buyer_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="coupons",
                to="salesapp.miniprogramuser",
            ),
        ),
        migrations.AddField(
            model_name="saleminicoupon",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AddField(
            model_name="saleminicoupon",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sale_mini_coupons",
                to="baseinfo.customer",
            ),
        ),
        migrations.AddField(
            model_name="saleminicoupon",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_deleted",
                to=settings.AUTH_USER_MODEL,
                verbose_name="删除人",
            ),
        ),
        migrations.AddField(
            model_name="saleminicoupon",
            name="locked_mapping",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="locked_coupons",
                to="salesapp.saleminiordermapping",
            ),
        ),
        migrations.AddField(
            model_name="saleminicoupon",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sale_mini_coupons",
                to="baseinfo.owner",
            ),
        ),
        migrations.AddField(
            model_name="saleminicoupon",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="更新人",
            ),
        ),
        migrations.AddField(
            model_name="saleminicoupon",
            name="used_mapping",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="used_coupons",
                to="salesapp.saleminiordermapping",
            ),
        ),
        migrations.AddField(
            model_name="saleminicoupontemplate",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AddField(
            model_name="saleminicoupontemplate",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_deleted",
                to=settings.AUTH_USER_MODEL,
                verbose_name="删除人",
            ),
        ),
        migrations.AddField(
            model_name="saleminicoupontemplate",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sale_mini_coupon_templates",
                to="baseinfo.owner",
            ),
        ),
        migrations.AddField(
            model_name="saleminicoupontemplate",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="更新人",
            ),
        ),
        migrations.AddField(
            model_name="saleminicoupon",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="coupons",
                to="salesapp.saleminicoupontemplate",
            ),
        ),
        migrations.AddField(
            model_name="saleminidistributionrecord",
            name="buyer_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="distribution_orders",
                to="salesapp.miniprogramuser",
            ),
        ),
        migrations.AddField(
            model_name="saleminidistributionrecord",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AddField(
            model_name="saleminidistributionrecord",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sale_mini_distribution_records",
                to="baseinfo.customer",
            ),
        ),
        migrations.AddField(
            model_name="saleminidistributionrecord",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_deleted",
                to=settings.AUTH_USER_MODEL,
                verbose_name="删除人",
            ),
        ),
        migrations.AddField(
            model_name="saleminidistributionrecord",
            name="mapping",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="distribution_record",
                to="salesapp.saleminiordermapping",
            ),
        ),
        migrations.AddField(
            model_name="saleminidistributionrecord",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sale_mini_distribution_records",
                to="baseinfo.owner",
            ),
        ),
        migrations.AddField(
            model_name="saleminidistributionrecord",
            name="referrer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="distribution_referrals",
                to="salesapp.miniprogramuser",
            ),
        ),
        migrations.AddField(
            model_name="saleminidistributionrecord",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="更新人",
            ),
        ),
        migrations.AddField(
            model_name="saleminiorderadjustment",
            name="buyer_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="adjustments",
                to="salesapp.miniprogramuser",
            ),
        ),
        migrations.AddField(
            model_name="saleminiorderadjustment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AddField(
            model_name="saleminiorderadjustment",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sale_mini_adjustments",
                to="baseinfo.customer",
            ),
        ),
        migrations.AddField(
            model_name="saleminiorderadjustment",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_deleted",
                to=settings.AUTH_USER_MODEL,
                verbose_name="删除人",
            ),
        ),
        migrations.AddField(
            model_name="saleminiorderadjustment",
            name="mapping",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="adjustments",
                to="salesapp.saleminiordermapping",
            ),
        ),
        migrations.AddField(
            model_name="saleminiorderadjustment",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sale_mini_adjustments",
                to="baseinfo.owner",
            ),
        ),
        migrations.AddField(
            model_name="saleminiorderadjustment",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="更新人",
            ),
        ),
        migrations.AddField(
            model_name="saleminipointledger",
            name="buyer_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="point_ledgers",
                to="salesapp.miniprogramuser",
            ),
        ),
        migrations.AddField(
            model_name="saleminipointledger",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AddField(
            model_name="saleminipointledger",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sale_mini_point_ledgers",
                to="baseinfo.customer",
            ),
        ),
        migrations.AddField(
            model_name="saleminipointledger",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_deleted",
                to=settings.AUTH_USER_MODEL,
                verbose_name="删除人",
            ),
        ),
        migrations.AddField(
            model_name="saleminipointledger",
            name="mapping",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="point_ledgers",
                to="salesapp.saleminiordermapping",
            ),
        ),
        migrations.AddField(
            model_name="saleminipointledger",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sale_mini_point_ledgers",
                to="baseinfo.owner",
            ),
        ),
        migrations.AddField(
            model_name="saleminipointledger",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="更新人",
            ),
        ),
        migrations.AddIndex(
            model_name="saleminicoupontemplate",
            index=models.Index(
                fields=["owner", "code"], name="salesapp_sa_owner_i_ab2441_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="saleminicoupontemplate",
            index=models.Index(
                fields=["owner", "effective_from", "effective_to"],
                name="salesapp_sa_owner_i_0e66d0_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="saleminicoupontemplate",
            constraint=models.UniqueConstraint(
                fields=("owner", "code"), name="ux_sale_mini_coupon_tpl_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="saleminicoupontemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(("threshold_amount__gte", 0)),
                name="ck_sale_mini_coupon_tpl_threshold_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="saleminicoupontemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount_amount__gt", 0)),
                name="ck_sale_mini_coupon_tpl_discount_gt_0",
            ),
        ),
        migrations.AddIndex(
            model_name="saleminicoupon",
            index=models.Index(
                fields=["owner", "customer", "status"],
                name="salesapp_sa_owner_i_5b5c1d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="saleminicoupon",
            index=models.Index(
                fields=["buyer_user", "status"], name="salesapp_sa_buyer_u_db5458_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="saleminicoupon",
            index=models.Index(
                fields=["locked_mapping"], name="salesapp_sa_locked__5b9676_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="saleminicoupon",
            index=models.Index(
                fields=["used_mapping"], name="salesapp_sa_used_ma_e35da8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="saleminidistributionrecord",
            index=models.Index(
                fields=["owner", "referrer", "status"],
                name="salesapp_sa_owner_i_0e3cf1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="saleminidistributionrecord",
            index=models.Index(
                fields=["mapping", "status"], name="salesapp_sa_mapping_45c3d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="saleminiorderadjustment",
            index=models.Index(
                fields=["owner", "customer", "adjustment_type"],
                name="salesapp_sa_owner_i_3ef86c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="saleminiorderadjustment",
            index=models.Index(
                fields=["mapping", "status"], name="salesapp_sa_mapping_faa379_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="saleminiorderadjustment",
            index=models.Index(
                fields=["source_model", "source_id"],
                name="salesapp_sa_source__6d3237_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="saleminipointledger",
            index=models.Index(
                fields=["owner", "customer", "created_at"],
                name="salesapp_sa_owner_i_3d0046_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="saleminipointledger",
            index=models.Index(
                fields=["buyer_user", "created_at"],
                name="salesapp_sa_buyer_u_ab7696_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="saleminipointledger",
            index=models.Index(
                fields=["mapping", "tx_type"], name="salesapp_sa_mapping_caefb4_idx"
            ),
        ),
    ]
