# Generated by Django 5.2.5 on 2026-06-28 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseinfo", "0002_initial"),
        ("salesapp", "0005_saleminicoupon_saleminicoupontemplate_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SaleMiniAfterSaleRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="已删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用状态"),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
                ("request_no", models.CharField(max_length=64, unique=True)),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("REFUND", "仅退款"),
                            ("RETURN_REFUND", "退货退款"),
                            ("EXCHANGE", "换货"),
                        ],
                        default="REFUND",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待处理"),
                            ("APPROVED", "已同意"),
                            ("REJECTED", "已拒绝"),
                            ("CANCELLED", "已取消"),
                            ("CLOSED", "已关闭"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=300)),
                ("requested_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "review_note",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "buyer_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="after_sale_requests",
                        to="salesapp.miniprogramuser",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_mini_after_sales",
                        to="baseinfo.customer",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "mapping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="after_sale_requests",
                        to="salesapp.saleminiordermapping",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_mini_after_sales",
                        to="baseinfo.owner",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["owner", "customer", "status"],
                        name="salesapp_sa_owner_i_4951dd_idx",
                    ),
                    models.Index(
                        fields=["mapping", "status"],
                        name="salesapp_sa_mapping_efd25c_idx",
                    ),
                    models.Index(
                        fields=["buyer_user", "created_at"],
                        name="salesapp_sa_buyer_u_ce5e62_idx",
                    ),
                ],
            },
        ),
    ]
