# Generated by Django 5.2.5 on 2026-07-22 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0004_owner_next_sku_sequence'),
        ('products', '0004_productcategory_mall_fields'),
        ('salesapp', '0007_allow_multi_owner_mini_program_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='minicustomeraddress',
            options={'verbose_name': '小程序收货地址', 'verbose_name_plural': '小程序收货地址'},
        ),
        migrations.AlterModelOptions(
            name='miniprogramuser',
            options={'verbose_name': '小程序用户', 'verbose_name_plural': '小程序用户'},
        ),
        migrations.AlterModelOptions(
            name='saleminiaftersalerequest',
            options={'verbose_name': '商城售后申请', 'verbose_name_plural': '商城售后申请'},
        ),
        migrations.AlterModelOptions(
            name='saleminibanner',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': '商城轮播图', 'verbose_name_plural': '商城轮播图'},
        ),
        migrations.AlterModelOptions(
            name='saleminicart',
            options={'verbose_name': '商城购物车', 'verbose_name_plural': '商城购物车'},
        ),
        migrations.AlterModelOptions(
            name='saleminicartitem',
            options={'ordering': ['id'], 'verbose_name': '商城购物车商品', 'verbose_name_plural': '商城购物车商品'},
        ),
        migrations.AlterModelOptions(
            name='saleminicoupon',
            options={'verbose_name': '商城优惠券', 'verbose_name_plural': '商城优惠券'},
        ),
        migrations.AlterModelOptions(
            name='saleminicoupontemplate',
            options={'verbose_name': '商城优惠券模板', 'verbose_name_plural': '商城优惠券模板'},
        ),
        migrations.AlterModelOptions(
            name='saleminidistributionrecord',
            options={'verbose_name': '商城分销记录', 'verbose_name_plural': '商城分销记录'},
        ),
        migrations.AlterModelOptions(
            name='saleminiorderadjustment',
            options={'verbose_name': '商城订单调整', 'verbose_name_plural': '商城订单调整'},
        ),
        migrations.AlterModelOptions(
            name='saleminiordermapping',
            options={'verbose_name': '商城订单映射', 'verbose_name_plural': '商城订单映射'},
        ),
        migrations.AlterModelOptions(
            name='saleminipayment',
            options={'verbose_name': '商城支付单', 'verbose_name_plural': '商城支付单'},
        ),
        migrations.AlterModelOptions(
            name='saleminipaymentevent',
            options={'verbose_name': '商城支付回调事件', 'verbose_name_plural': '商城支付回调事件'},
        ),
        migrations.AlterModelOptions(
            name='saleminipointledger',
            options={'verbose_name': '商城积分流水', 'verbose_name_plural': '商城积分流水'},
        ),
        migrations.AlterModelOptions(
            name='saleminirefund',
            options={'verbose_name': '商城退款单', 'verbose_name_plural': '商城退款单'},
        ),
        migrations.AlterModelOptions(
            name='saleproductconfig',
            options={'ordering': ['sort_order', 'product__code'], 'verbose_name': '商城商品配置', 'verbose_name_plural': '商城商品配置'},
        ),
        migrations.AlterField(
            model_name='saleproductconfig',
            name='is_hot',
            field=models.BooleanField(default=False, verbose_name='热销商品'),
        ),
        migrations.AlterField(
            model_name='saleproductconfig',
            name='is_listed',
            field=models.BooleanField(default=False, verbose_name='已上架'),
        ),
        migrations.AlterField(
            model_name='saleproductconfig',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='新品'),
        ),
        migrations.AlterField(
            model_name='saleproductconfig',
            name='is_recommended',
            field=models.BooleanField(default=False, verbose_name='推荐商品'),
        ),
        migrations.AlterField(
            model_name='saleproductconfig',
            name='market_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='划线价'),
        ),
        migrations.AlterField(
            model_name='saleproductconfig',
            name='max_order_qty',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='最大购买量'),
        ),
        migrations.AlterField(
            model_name='saleproductconfig',
            name='min_order_qty',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12, verbose_name='起购数量'),
        ),
        migrations.AlterField(
            model_name='saleproductconfig',
            name='multiple_qty',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12, verbose_name='购买递增量'),
        ),
        migrations.AlterField(
            model_name='saleproductconfig',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_product_configs', to='baseinfo.owner', verbose_name='货主'),
        ),
        migrations.AlterField(
            model_name='saleproductconfig',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_mini_configs', to='products.product', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='saleproductconfig',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='商城售价'),
        ),
        migrations.AlterField(
            model_name='saleproductconfig',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='saleproductconfig',
            name='stock_display',
            field=models.CharField(choices=[('STATUS', '库存状态'), ('EXACT', '准确库存'), ('HIDDEN', '不展示库存')], default='STATUS', max_length=12, verbose_name='库存展示方式'),
        ),
    ]
