# Generated by Django 5.2.5 on 2026-07-23 09:42

import allapp.salesapp.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baseinfo", "0004_owner_next_sku_sequence"),
        ("outbound", "0004_outboundorder_assisted_history_index"),
        ("products", "0004_productcategory_mall_fields"),
        ("salesapp", "0009_saleproductconfig_enable_qty_rules"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SaleMiniProductReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="已删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用状态"),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "quality_score",
                    models.PositiveSmallIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="商品质量评分",
                    ),
                ),
                (
                    "delivery_score",
                    models.PositiveSmallIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="配送服务评分",
                    ),
                ),
                (
                    "overall_score",
                    models.PositiveSmallIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="综合满意度",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, default="", max_length=1000, verbose_name="评价内容"
                    ),
                ),
                (
                    "is_anonymous",
                    models.BooleanField(default=True, verbose_name="匿名评价"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "草稿"),
                            ("PENDING", "待审核"),
                            ("PUBLISHED", "已发布"),
                            ("REJECTED", "已驳回"),
                            ("HIDDEN", "已隐藏"),
                        ],
                        default="DRAFT",
                        max_length=16,
                        verbose_name="审核状态",
                    ),
                ),
                (
                    "rejection_reason",
                    models.CharField(
                        blank=True, default="", max_length=300, verbose_name="驳回原因"
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="提交时间"
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="审核时间"
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="发布时间"
                    ),
                ),
                (
                    "buyer_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_reviews",
                        to="salesapp.miniprogramuser",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_mini_product_reviews",
                        to="baseinfo.customer",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "mapping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_reviews",
                        to="salesapp.saleminiordermapping",
                    ),
                ),
                (
                    "order_line",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_mini_review",
                        to="outbound.outboundorderline",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_mini_product_reviews",
                        to="baseinfo.owner",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_mini_reviews",
                        to="products.product",
                    ),
                ),
                (
                    "product_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviews",
                        to="salesapp.saleproductconfig",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviewed_sale_mini_product_reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审核人",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "商城商品评价",
                "verbose_name_plural": "商城商品评价",
                "ordering": ["-published_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SaleMiniProductReviewImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="已删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用状态"),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=allapp.salesapp.models.sale_mini_review_image_path,
                        verbose_name="评价图片",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="排序"),
                ),
                (
                    "size_bytes",
                    models.PositiveIntegerField(default=0, verbose_name="文件大小"),
                ),
                ("width", models.PositiveIntegerField(default=0, verbose_name="宽度")),
                ("height", models.PositiveIntegerField(default=0, verbose_name="高度")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="salesapp.saleminiproductreview",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "商城评价图片",
                "verbose_name_plural": "商城评价图片",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="saleminiproductreview",
            index=models.Index(
                fields=["product_config", "status", "published_at"],
                name="salesapp_sa_product_4e9f4d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="saleminiproductreview",
            index=models.Index(
                fields=["product", "status", "published_at"],
                name="salesapp_sa_product_126716_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="saleminiproductreview",
            index=models.Index(
                fields=["buyer_user", "status", "created_at"],
                name="salesapp_sa_buyer_u_52f3e1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="saleminiproductreview",
            index=models.Index(
                fields=["owner", "status", "created_at"],
                name="salesapp_sa_owner_i_1c620d_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="saleminiproductreview",
            constraint=models.CheckConstraint(
                condition=models.Q(("quality_score__range", (1, 5))),
                name="ck_sale_review_quality_1_5",
            ),
        ),
        migrations.AddConstraint(
            model_name="saleminiproductreview",
            constraint=models.CheckConstraint(
                condition=models.Q(("delivery_score__range", (1, 5))),
                name="ck_sale_review_delivery_1_5",
            ),
        ),
        migrations.AddConstraint(
            model_name="saleminiproductreview",
            constraint=models.CheckConstraint(
                condition=models.Q(("overall_score__range", (1, 5))),
                name="ck_sale_review_overall_1_5",
            ),
        ),
        migrations.AddConstraint(
            model_name="saleminiproductreviewimage",
            constraint=models.UniqueConstraint(
                fields=("review", "sort_order"), name="ux_sale_review_image_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="saleminiproductreviewimage",
            constraint=models.CheckConstraint(
                condition=models.Q(("sort_order__lt", 6)),
                name="ck_sale_review_image_order_lt_6",
            ),
        ),
    ]
