# Generated by Django 5.2.5 on 2026-07-23 16:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseinfo", "0004_owner_next_sku_sequence"),
        ("salesapp", "0010_saleminiproductreview_saleminiproductreviewimage_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="saleminirefund",
            name="idempotency_key",
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="saleminirefund",
            name="last_error",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="saleminirefund",
            name="next_retry_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="saleminirefund",
            name="requires_manual_action",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="saleminirefund",
            name="retry_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="saleminirefund",
            name="source",
            field=models.CharField(
                choices=[
                    ("USER_REQUEST", "用户申请"),
                    ("LATE_PAYMENT", "延迟到账自动退款"),
                ],
                default="USER_REQUEST",
                max_length=24,
            ),
        ),
        migrations.AddIndex(
            model_name="saleminirefund",
            index=models.Index(
                fields=["status", "next_retry_at"], name="salesapp_sa_status_bd14ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="saleminirefund",
            index=models.Index(
                fields=["requires_manual_action", "updated_at"],
                name="salesapp_sa_require_c0a531_idx",
            ),
        ),
    ]
