# Generated by Django 5.2.5 on 2026-08-13 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseinfo", "0005_ownerwarehousebinding"),
        ("outbound", "0007_operations_report_indexes"),
        ("products", "0014_product_purchase_price"),
        ("salesapp", "0012_payment_reliability"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name="minicustomeraddress",
                    name="buyer_user",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="addresses",
                        to="salesapp.miniprogramuser",
                        verbose_name="小程序用户",
                    ),
                ),
                migrations.AlterField(
                    model_name="minicustomeraddress",
                    name="city",
                    field=models.CharField(
                        blank=True, default="", max_length=30, verbose_name="城市"
                    ),
                ),
                migrations.AlterField(
                    model_name="minicustomeraddress",
                    name="contact",
                    field=models.CharField(max_length=80, verbose_name="联系人"),
                ),
                migrations.AlterField(
                    model_name="minicustomeraddress",
                    name="customer",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mini_addresses",
                        to="baseinfo.customer",
                        verbose_name="客户",
                    ),
                ),
                migrations.AlterField(
                    model_name="minicustomeraddress",
                    name="detail",
                    field=models.CharField(max_length=200, verbose_name="详细地址"),
                ),
                migrations.AlterField(
                    model_name="minicustomeraddress",
                    name="district",
                    field=models.CharField(
                        blank=True, default="", max_length=30, verbose_name="区县"
                    ),
                ),
                migrations.AlterField(
                    model_name="minicustomeraddress",
                    name="is_default",
                    field=models.BooleanField(default=False, verbose_name="默认地址"),
                ),
                migrations.AlterField(
                    model_name="minicustomeraddress",
                    name="owner",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mini_customer_addresses",
                        to="baseinfo.owner",
                        verbose_name="货主",
                    ),
                ),
                migrations.AlterField(
                    model_name="minicustomeraddress",
                    name="phone",
                    field=models.CharField(max_length=40, verbose_name="联系电话"),
                ),
                migrations.AlterField(
                    model_name="minicustomeraddress",
                    name="province",
                    field=models.CharField(
                        blank=True, default="", max_length=30, verbose_name="省份"
                    ),
                ),
                migrations.AlterField(
                    model_name="miniprogramuser",
                    name="avatar_url",
                    field=models.CharField(
                        blank=True, default="", max_length=500, verbose_name="头像地址"
                    ),
                ),
                migrations.AlterField(
                    model_name="miniprogramuser",
                    name="customer",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mini_program_users",
                        to="baseinfo.customer",
                        verbose_name="客户",
                    ),
                ),
                migrations.AlterField(
                    model_name="miniprogramuser",
                    name="nickname",
                    field=models.CharField(
                        blank=True, default="", max_length=80, verbose_name="昵称"
                    ),
                ),
                migrations.AlterField(
                    model_name="miniprogramuser",
                    name="openid",
                    field=models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="微信 OpenID",
                    ),
                ),
                migrations.AlterField(
                    model_name="miniprogramuser",
                    name="owner",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mini_program_users",
                        to="baseinfo.owner",
                        verbose_name="货主",
                    ),
                ),
                migrations.AlterField(
                    model_name="miniprogramuser",
                    name="phone",
                    field=models.CharField(
                        blank=True, default="", max_length=32, verbose_name="手机号"
                    ),
                ),
                migrations.AlterField(
                    model_name="miniprogramuser",
                    name="unionid",
                    field=models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="微信 UnionID",
                    ),
                ),
                migrations.AlterField(
                    model_name="miniprogramuser",
                    name="user",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mini_program_profiles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="关联账号",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminiaftersalerequest",
                    name="amount",
                    field=models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="申请金额",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminiaftersalerequest",
                    name="buyer_user",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="after_sale_requests",
                        to="salesapp.miniprogramuser",
                        verbose_name="小程序用户",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminiaftersalerequest",
                    name="customer",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_mini_after_sales",
                        to="baseinfo.customer",
                        verbose_name="客户",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminiaftersalerequest",
                    name="mapping",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="after_sale_requests",
                        to="salesapp.saleminiordermapping",
                        verbose_name="商城订单",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminiaftersalerequest",
                    name="owner",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_mini_after_sales",
                        to="baseinfo.owner",
                        verbose_name="货主",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminiaftersalerequest",
                    name="reason",
                    field=models.CharField(
                        blank=True, default="", max_length=300, verbose_name="申请原因"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminiaftersalerequest",
                    name="request_no",
                    field=models.CharField(
                        max_length=64, unique=True, verbose_name="售后申请单号"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminiaftersalerequest",
                    name="request_type",
                    field=models.CharField(
                        choices=[
                            ("REFUND", "仅退款"),
                            ("RETURN_REFUND", "退货退款"),
                            ("EXCHANGE", "换货"),
                        ],
                        default="REFUND",
                        max_length=20,
                        verbose_name="售后类型",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminiaftersalerequest",
                    name="requested_at",
                    field=models.DateTimeField(
                        blank=True, null=True, verbose_name="申请时间"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminiaftersalerequest",
                    name="review_note",
                    field=models.CharField(
                        blank=True, default="", max_length=300, verbose_name="审核意见"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminiaftersalerequest",
                    name="reviewed_at",
                    field=models.DateTimeField(
                        blank=True, null=True, verbose_name="审核时间"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminiaftersalerequest",
                    name="status",
                    field=models.CharField(
                        choices=[
                            ("PENDING", "待处理"),
                            ("APPROVED", "已同意"),
                            ("REJECTED", "已拒绝"),
                            ("CANCELLED", "已取消"),
                            ("CLOSED", "已关闭"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="处理状态",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminibanner",
                    name="image_url",
                    field=models.CharField(max_length=500, verbose_name="图片地址"),
                ),
                migrations.AlterField(
                    model_name="saleminibanner",
                    name="link_type",
                    field=models.CharField(
                        blank=True, default="", max_length=30, verbose_name="链接类型"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminibanner",
                    name="link_value",
                    field=models.CharField(
                        blank=True, default="", max_length=120, verbose_name="链接内容"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminibanner",
                    name="owner",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_mini_banners",
                        to="baseinfo.owner",
                        verbose_name="货主",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminibanner",
                    name="sort_order",
                    field=models.PositiveIntegerField(default=0, verbose_name="排序"),
                ),
                migrations.AlterField(
                    model_name="saleminibanner",
                    name="title",
                    field=models.CharField(max_length=120, verbose_name="标题"),
                ),
                migrations.AlterField(
                    model_name="saleminicart",
                    name="buyer_user",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="carts",
                        to="salesapp.miniprogramuser",
                        verbose_name="小程序用户",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminicart",
                    name="customer",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_mini_carts",
                        to="baseinfo.customer",
                        verbose_name="客户",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminicart",
                    name="owner",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_mini_carts",
                        to="baseinfo.owner",
                        verbose_name="货主",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminicartitem",
                    name="cart",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="salesapp.saleminicart",
                        verbose_name="购物车",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminicartitem",
                    name="order_uom",
                    field=models.CharField(max_length=32, verbose_name="购买单位"),
                ),
                migrations.AlterField(
                    model_name="saleminicartitem",
                    name="product",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_mini_cart_items",
                        to="products.product",
                        verbose_name="商品",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminicartitem",
                    name="qty",
                    field=models.DecimalField(
                        decimal_places=3, max_digits=12, verbose_name="数量"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminicoupon",
                    name="buyer_user",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coupons",
                        to="salesapp.miniprogramuser",
                        verbose_name="小程序用户",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminicoupon",
                    name="coupon_no",
                    field=models.CharField(
                        max_length=64, unique=True, verbose_name="优惠券编号"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminicoupon",
                    name="customer",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_mini_coupons",
                        to="baseinfo.customer",
                        verbose_name="客户",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminicoupon",
                    name="expires_at",
                    field=models.DateTimeField(
                        blank=True, null=True, verbose_name="过期时间"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminicoupon",
                    name="locked_at",
                    field=models.DateTimeField(
                        blank=True, null=True, verbose_name="锁定时间"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminicoupon",
                    name="locked_mapping",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="locked_coupons",
                        to="salesapp.saleminiordermapping",
                        verbose_name="锁定订单",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminicoupon",
                    name="owner",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_mini_coupons",
                        to="baseinfo.owner",
                        verbose_name="货主",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminicoupon",
                    name="status",
                    field=models.CharField(
                        choices=[
                            ("AVAILABLE", "可用"),
                            ("LOCKED", "已锁定"),
                            ("USED", "已使用"),
                            ("RELEASED", "已释放"),
                            ("EXPIRED", "已过期"),
                            ("VOID", "已作废"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminicoupon",
                    name="template",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coupons",
                        to="salesapp.saleminicoupontemplate",
                        verbose_name="优惠券模板",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminicoupon",
                    name="used_at",
                    field=models.DateTimeField(
                        blank=True, null=True, verbose_name="使用时间"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminicoupon",
                    name="used_mapping",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="used_coupons",
                        to="salesapp.saleminiordermapping",
                        verbose_name="使用订单",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminicoupontemplate",
                    name="code",
                    field=models.CharField(max_length=64, verbose_name="模板编码"),
                ),
                migrations.AlterField(
                    model_name="saleminicoupontemplate",
                    name="coupon_type",
                    field=models.CharField(
                        choices=[("AMOUNT", "金额券")],
                        default="AMOUNT",
                        max_length=20,
                        verbose_name="优惠券类型",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminicoupontemplate",
                    name="discount_amount",
                    field=models.DecimalField(
                        decimal_places=2, max_digits=18, verbose_name="优惠金额"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminicoupontemplate",
                    name="effective_from",
                    field=models.DateField(verbose_name="生效日期"),
                ),
                migrations.AlterField(
                    model_name="saleminicoupontemplate",
                    name="effective_to",
                    field=models.DateField(
                        blank=True, null=True, verbose_name="失效日期"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminicoupontemplate",
                    name="is_stackable",
                    field=models.BooleanField(
                        default=True, verbose_name="允许叠加使用"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminicoupontemplate",
                    name="owner",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_mini_coupon_templates",
                        to="baseinfo.owner",
                        verbose_name="货主",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminicoupontemplate",
                    name="per_customer_limit",
                    field=models.PositiveIntegerField(
                        default=0,
                        help_text="0 表示不限量",
                        verbose_name="每客户限领数量",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminicoupontemplate",
                    name="threshold_amount",
                    field=models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="使用门槛",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminicoupontemplate",
                    name="title",
                    field=models.CharField(max_length=120, verbose_name="模板名称"),
                ),
                migrations.AlterField(
                    model_name="saleminicoupontemplate",
                    name="total_limit",
                    field=models.PositiveIntegerField(
                        default=0, help_text="0 表示不限量", verbose_name="发放总量"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminidistributionrecord",
                    name="base_amount",
                    field=models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="计佣金额",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminidistributionrecord",
                    name="buyer_user",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="distribution_orders",
                        to="salesapp.miniprogramuser",
                        verbose_name="小程序用户",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminidistributionrecord",
                    name="commission_amount",
                    field=models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="佣金金额",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminidistributionrecord",
                    name="commission_rate",
                    field=models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=7,
                        verbose_name="佣金比例",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminidistributionrecord",
                    name="confirmed_at",
                    field=models.DateTimeField(
                        blank=True, null=True, verbose_name="确认时间"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminidistributionrecord",
                    name="customer",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_mini_distribution_records",
                        to="baseinfo.customer",
                        verbose_name="客户",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminidistributionrecord",
                    name="mapping",
                    field=models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="distribution_record",
                        to="salesapp.saleminiordermapping",
                        verbose_name="商城订单",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminidistributionrecord",
                    name="owner",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_mini_distribution_records",
                        to="baseinfo.owner",
                        verbose_name="货主",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminidistributionrecord",
                    name="referrer",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="distribution_referrals",
                        to="salesapp.miniprogramuser",
                        verbose_name="推荐人",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminidistributionrecord",
                    name="reversed_at",
                    field=models.DateTimeField(
                        blank=True, null=True, verbose_name="冲销时间"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminidistributionrecord",
                    name="settled_at",
                    field=models.DateTimeField(
                        blank=True, null=True, verbose_name="结算时间"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminidistributionrecord",
                    name="status",
                    field=models.CharField(
                        choices=[
                            ("PENDING", "待结算"),
                            ("SETTLED", "已结算"),
                            ("REVERSED", "已冲销"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminiorderadjustment",
                    name="adjustment_no",
                    field=models.CharField(
                        max_length=64, unique=True, verbose_name="调整单号"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminiorderadjustment",
                    name="adjustment_type",
                    field=models.CharField(
                        choices=[
                            ("DISCOUNT_STEP", "满减"),
                            ("COUPON", "优惠券"),
                            ("POINTS", "积分抵扣"),
                            ("MANUAL", "人工调整"),
                        ],
                        max_length=20,
                        verbose_name="调整类型",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminiorderadjustment",
                    name="amount",
                    field=models.DecimalField(
                        decimal_places=2,
                        help_text="有符号调整金额，负数表示减少应付。",
                        max_digits=18,
                        verbose_name="调整金额",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminiorderadjustment",
                    name="buyer_user",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adjustments",
                        to="salesapp.miniprogramuser",
                        verbose_name="小程序用户",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminiorderadjustment",
                    name="confirmed_at",
                    field=models.DateTimeField(
                        blank=True, null=True, verbose_name="确认时间"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminiorderadjustment",
                    name="customer",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_mini_adjustments",
                        to="baseinfo.customer",
                        verbose_name="客户",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminiorderadjustment",
                    name="locked_at",
                    field=models.DateTimeField(
                        blank=True, null=True, verbose_name="锁定时间"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminiorderadjustment",
                    name="mapping",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adjustments",
                        to="salesapp.saleminiordermapping",
                        verbose_name="商城订单",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminiorderadjustment",
                    name="owner",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_mini_adjustments",
                        to="baseinfo.owner",
                        verbose_name="货主",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminiorderadjustment",
                    name="released_at",
                    field=models.DateTimeField(
                        blank=True, null=True, verbose_name="释放时间"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminiorderadjustment",
                    name="source_code",
                    field=models.CharField(
                        blank=True, default="", max_length=120, verbose_name="来源编号"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminiorderadjustment",
                    name="source_id",
                    field=models.CharField(
                        blank=True,
                        default="",
                        max_length=80,
                        verbose_name="来源记录 ID",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminiorderadjustment",
                    name="source_model",
                    field=models.CharField(
                        blank=True, default="", max_length=80, verbose_name="来源模型"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminiorderadjustment",
                    name="status",
                    field=models.CharField(
                        choices=[
                            ("PREVIEW", "预览"),
                            ("LOCKED", "已锁定"),
                            ("CONFIRMED", "已确认"),
                            ("RELEASED", "已释放"),
                            ("REVERSED", "已冲销"),
                        ],
                        default="PREVIEW",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminiorderadjustment",
                    name="title",
                    field=models.CharField(max_length=120, verbose_name="调整说明"),
                ),
                migrations.AlterField(
                    model_name="saleminiordermapping",
                    name="adjustment_amount",
                    field=models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="订单级调整金额，负数表示优惠，正数表示加价。",
                        max_digits=18,
                        verbose_name="调整金额",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminiordermapping",
                    name="buyer_user",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_mappings",
                        to="salesapp.miniprogramuser",
                        verbose_name="小程序用户",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminiordermapping",
                    name="customer",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_mini_order_mappings",
                        to="baseinfo.customer",
                        verbose_name="客户",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminiordermapping",
                    name="goods_amount",
                    field=models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="商品金额",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminiordermapping",
                    name="outbound_order",
                    field=models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_mini_mapping",
                        to="outbound.outboundorder",
                        verbose_name="出库订单",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminiordermapping",
                    name="owner",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_mini_order_mappings",
                        to="baseinfo.owner",
                        verbose_name="货主",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminiordermapping",
                    name="paid_at",
                    field=models.DateTimeField(
                        blank=True, null=True, verbose_name="支付时间"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminiordermapping",
                    name="pay_deadline_at",
                    field=models.DateTimeField(
                        blank=True, null=True, verbose_name="支付截止时间"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminiordermapping",
                    name="payable_amount",
                    field=models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="应付金额",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminiordermapping",
                    name="payment_status",
                    field=models.CharField(
                        choices=[
                            ("OFFLINE", "线下付款"),
                            ("UNPAID", "待付款"),
                            ("PAID", "已付款"),
                            ("REFUNDING", "退款中"),
                            ("REFUNDED", "已退款"),
                            ("CANCELLED", "已取消"),
                        ],
                        default="OFFLINE",
                        max_length=20,
                        verbose_name="支付状态",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminiordermapping",
                    name="source",
                    field=models.CharField(
                        default="sale-mini", max_length=30, verbose_name="订单来源"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminipayment",
                    name="amount",
                    field=models.DecimalField(
                        decimal_places=2, max_digits=18, verbose_name="支付金额"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminipayment",
                    name="amount_cents",
                    field=models.PositiveIntegerField(verbose_name="支付金额（分）"),
                ),
                migrations.AlterField(
                    model_name="saleminipayment",
                    name="buyer_user",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="salesapp.miniprogramuser",
                        verbose_name="小程序用户",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminipayment",
                    name="callback_payload",
                    field=models.JSONField(
                        blank=True, default=dict, verbose_name="支付回调报文"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminipayment",
                    name="channel",
                    field=models.CharField(
                        choices=[
                            ("WECHAT_JSAPI", "微信小程序支付"),
                            ("INTERNAL_ZERO", "内部零元结算"),
                        ],
                        default="WECHAT_JSAPI",
                        max_length=20,
                        verbose_name="支付渠道",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminipayment",
                    name="client_pay_params",
                    field=models.JSONField(
                        blank=True, default=dict, verbose_name="小程序支付参数"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminipayment",
                    name="closed_at",
                    field=models.DateTimeField(
                        blank=True, null=True, verbose_name="关闭时间"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminipayment",
                    name="currency",
                    field=models.CharField(
                        default="CNY", max_length=8, verbose_name="币种"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminipayment",
                    name="customer",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_mini_payments",
                        to="baseinfo.customer",
                        verbose_name="客户",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminipayment",
                    name="expires_at",
                    field=models.DateTimeField(
                        blank=True, null=True, verbose_name="支付过期时间"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminipayment",
                    name="last_error",
                    field=models.CharField(
                        blank=True, default="", max_length=300, verbose_name="最后错误"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminipayment",
                    name="mapping",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="salesapp.saleminiordermapping",
                        verbose_name="商城订单",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminipayment",
                    name="next_reconcile_at",
                    field=models.DateTimeField(
                        blank=True, null=True, verbose_name="下次对账时间"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminipayment",
                    name="out_trade_no",
                    field=models.CharField(
                        max_length=64, unique=True, verbose_name="商户支付单号"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminipayment",
                    name="owner",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_mini_payments",
                        to="baseinfo.owner",
                        verbose_name="货主",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminipayment",
                    name="paid_at",
                    field=models.DateTimeField(
                        blank=True, null=True, verbose_name="支付时间"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminipayment",
                    name="payment_no",
                    field=models.CharField(
                        max_length=64, unique=True, verbose_name="支付流水号"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminipayment",
                    name="prepay_id",
                    field=models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="微信预支付 ID",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminipayment",
                    name="prepay_response",
                    field=models.JSONField(
                        blank=True, default=dict, verbose_name="预支付响应报文"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminipayment",
                    name="request_payload",
                    field=models.JSONField(
                        blank=True, default=dict, verbose_name="预支付请求报文"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminipayment",
                    name="requires_manual_action",
                    field=models.BooleanField(
                        default=False, verbose_name="需要人工处理"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminipayment",
                    name="retry_count",
                    field=models.PositiveSmallIntegerField(
                        default=0, verbose_name="重试次数"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminipayment",
                    name="status",
                    field=models.CharField(
                        choices=[
                            ("CREATED", "已创建"),
                            ("PREPAY", "已预下单"),
                            ("PAID", "已支付"),
                            ("CLOSED", "已关闭"),
                            ("REFUNDING", "退款中"),
                            ("REFUNDED", "已退款"),
                            ("FAILED", "失败"),
                        ],
                        default="CREATED",
                        max_length=20,
                        verbose_name="支付状态",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminipayment",
                    name="trade_state",
                    field=models.CharField(
                        blank=True,
                        default="",
                        max_length=40,
                        verbose_name="微信交易状态",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminipayment",
                    name="trade_state_desc",
                    field=models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="微信交易状态说明",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminipayment",
                    name="transaction_id",
                    field=models.CharField(
                        blank=True,
                        default=None,
                        max_length=128,
                        null=True,
                        unique=True,
                        verbose_name="微信支付单号",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminipaymentevent",
                    name="decrypted_payload",
                    field=models.JSONField(
                        blank=True, default=dict, verbose_name="解密后报文"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminipaymentevent",
                    name="error_message",
                    field=models.CharField(
                        blank=True, default="", max_length=300, verbose_name="错误信息"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminipaymentevent",
                    name="event_id",
                    field=models.CharField(
                        max_length=128, unique=True, verbose_name="事件编号"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminipaymentevent",
                    name="event_type",
                    field=models.CharField(max_length=80, verbose_name="事件类型"),
                ),
                migrations.AlterField(
                    model_name="saleminipaymentevent",
                    name="out_refund_no",
                    field=models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="商户退款单号",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminipaymentevent",
                    name="out_trade_no",
                    field=models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="商户支付单号",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminipaymentevent",
                    name="payload",
                    field=models.JSONField(
                        blank=True, default=dict, verbose_name="原始回调报文"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminipaymentevent",
                    name="payment",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="salesapp.saleminipayment",
                        verbose_name="支付单",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminipaymentevent",
                    name="process_status",
                    field=models.CharField(
                        choices=[
                            ("PENDING", "待处理"),
                            ("PROCESSED", "已处理"),
                            ("FAILED", "处理失败"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="处理状态",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminipaymentevent",
                    name="processed_at",
                    field=models.DateTimeField(
                        blank=True, null=True, verbose_name="处理时间"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminipaymentevent",
                    name="refund",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="salesapp.saleminirefund",
                        verbose_name="退款单",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminipaymentevent",
                    name="resource_type",
                    field=models.CharField(
                        blank=True, default="", max_length=80, verbose_name="资源类型"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminipointledger",
                    name="amount",
                    field=models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="关联金额",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminipointledger",
                    name="buyer_user",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="point_ledgers",
                        to="salesapp.miniprogramuser",
                        verbose_name="小程序用户",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminipointledger",
                    name="customer",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_mini_point_ledgers",
                        to="baseinfo.customer",
                        verbose_name="客户",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminipointledger",
                    name="frozen_delta",
                    field=models.IntegerField(default=0, verbose_name="冻结积分变动"),
                ),
                migrations.AlterField(
                    model_name="saleminipointledger",
                    name="mapping",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="point_ledgers",
                        to="salesapp.saleminiordermapping",
                        verbose_name="商城订单",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminipointledger",
                    name="note",
                    field=models.CharField(
                        blank=True, default="", max_length=200, verbose_name="说明"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminipointledger",
                    name="owner",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_mini_point_ledgers",
                        to="baseinfo.owner",
                        verbose_name="货主",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminipointledger",
                    name="points_delta",
                    field=models.IntegerField(default=0, verbose_name="积分变动"),
                ),
                migrations.AlterField(
                    model_name="saleminipointledger",
                    name="tx_no",
                    field=models.CharField(
                        max_length=64, unique=True, verbose_name="流水号"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminipointledger",
                    name="tx_type",
                    field=models.CharField(
                        choices=[
                            ("EARN", "获得"),
                            ("FREEZE", "冻结"),
                            ("CONSUME", "消耗"),
                            ("RELEASE", "释放"),
                            ("REFUND", "退回"),
                            ("ADJUST", "调整"),
                        ],
                        max_length=20,
                        verbose_name="流水类型",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminiproductreview",
                    name="buyer_user",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_reviews",
                        to="salesapp.miniprogramuser",
                        verbose_name="小程序用户",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminiproductreview",
                    name="customer",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_mini_product_reviews",
                        to="baseinfo.customer",
                        verbose_name="客户",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminiproductreview",
                    name="mapping",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_reviews",
                        to="salesapp.saleminiordermapping",
                        verbose_name="商城订单",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminiproductreview",
                    name="order_line",
                    field=models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_mini_review",
                        to="outbound.outboundorderline",
                        verbose_name="出库订单明细",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminiproductreview",
                    name="owner",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_mini_product_reviews",
                        to="baseinfo.owner",
                        verbose_name="货主",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminiproductreview",
                    name="product",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_mini_reviews",
                        to="products.product",
                        verbose_name="商品",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminiproductreview",
                    name="product_config",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviews",
                        to="salesapp.saleproductconfig",
                        verbose_name="商城商品配置",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminiproductreviewimage",
                    name="review",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="salesapp.saleminiproductreview",
                        verbose_name="商品评价",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminirefund",
                    name="amount",
                    field=models.DecimalField(
                        decimal_places=2, max_digits=18, verbose_name="退款金额"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminirefund",
                    name="amount_cents",
                    field=models.PositiveIntegerField(verbose_name="退款金额（分）"),
                ),
                migrations.AlterField(
                    model_name="saleminirefund",
                    name="buyer_user",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="salesapp.miniprogramuser",
                        verbose_name="小程序用户",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminirefund",
                    name="callback_payload",
                    field=models.JSONField(
                        blank=True, default=dict, verbose_name="退款回调报文"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminirefund",
                    name="currency",
                    field=models.CharField(
                        default="CNY", max_length=8, verbose_name="币种"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminirefund",
                    name="customer",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_mini_refunds",
                        to="baseinfo.customer",
                        verbose_name="客户",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminirefund",
                    name="idempotency_key",
                    field=models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        unique=True,
                        verbose_name="幂等键",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminirefund",
                    name="last_error",
                    field=models.CharField(
                        blank=True, default="", max_length=300, verbose_name="最后错误"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminirefund",
                    name="next_retry_at",
                    field=models.DateTimeField(
                        blank=True, null=True, verbose_name="下次重试时间"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminirefund",
                    name="out_refund_no",
                    field=models.CharField(
                        max_length=64, unique=True, verbose_name="商户退款单号"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminirefund",
                    name="owner",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_mini_refunds",
                        to="baseinfo.owner",
                        verbose_name="货主",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminirefund",
                    name="payment",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="salesapp.saleminipayment",
                        verbose_name="支付单",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminirefund",
                    name="reason",
                    field=models.CharField(
                        blank=True, default="", max_length=120, verbose_name="退款原因"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminirefund",
                    name="refund_id",
                    field=models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="微信退款单号",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminirefund",
                    name="refund_no",
                    field=models.CharField(
                        max_length=64, unique=True, verbose_name="退款流水号"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminirefund",
                    name="request_payload",
                    field=models.JSONField(
                        blank=True, default=dict, verbose_name="退款请求报文"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminirefund",
                    name="requested_at",
                    field=models.DateTimeField(
                        blank=True, null=True, verbose_name="申请退款时间"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminirefund",
                    name="requires_manual_action",
                    field=models.BooleanField(
                        default=False, verbose_name="需要人工处理"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminirefund",
                    name="response_payload",
                    field=models.JSONField(
                        blank=True, default=dict, verbose_name="退款响应报文"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminirefund",
                    name="retry_count",
                    field=models.PositiveSmallIntegerField(
                        default=0, verbose_name="重试次数"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminirefund",
                    name="source",
                    field=models.CharField(
                        choices=[
                            ("USER_REQUEST", "用户申请"),
                            ("LATE_PAYMENT", "延迟到账自动退款"),
                        ],
                        default="USER_REQUEST",
                        max_length=24,
                        verbose_name="退款来源",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminirefund",
                    name="status",
                    field=models.CharField(
                        choices=[
                            ("CREATED", "已创建"),
                            ("PROCESSING", "处理中"),
                            ("SUCCESS", "退款成功"),
                            ("ABNORMAL", "退款异常"),
                            ("CLOSED", "已关闭"),
                            ("FAILED", "失败"),
                        ],
                        default="CREATED",
                        max_length=20,
                        verbose_name="退款状态",
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminirefund",
                    name="success_at",
                    field=models.DateTimeField(
                        blank=True, null=True, verbose_name="退款成功时间"
                    ),
                ),
                migrations.AlterField(
                    model_name="saleminirefund",
                    name="total_amount_cents",
                    field=models.PositiveIntegerField(verbose_name="原订单金额（分）"),
                ),
            ],
        ),
    ]
