# Generated by Django 5.2.5 on 2026-04-24 20:40

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("baseinfo", "0002_initial"),
        ("locations", "0001_initial"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InboundOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="已删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用状态"),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="制表时间"),
                ),
                (
                    "order_no",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="订单编号"
                    ),
                ),
                (
                    "biz_date",
                    models.DateField(default=datetime.date.today, verbose_name="日期"),
                ),
                (
                    "src_bill_no",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="源单号"
                    ),
                ),
                (
                    "inbound_type",
                    models.CharField(
                        choices=[
                            ("PURCHASE", "采购入库"),
                            ("CUST_RETURN", "退货入库"),
                            ("TRANSFER", "调拨入库"),
                            ("OTHER_IN", "其他入库"),
                        ],
                        default="PURCHASE",
                        max_length=15,
                        verbose_name="入库类型",
                    ),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        blank=True,
                        choices=[("CIF", "到岸"), ("DISPATCH", "派车")],
                        max_length=15,
                        null=True,
                        verbose_name="交货方式",
                    ),
                ),
                (
                    "eta",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="预计到货时间"
                    ),
                ),
                (
                    "submit_status",
                    models.CharField(
                        choices=[("SUBMITTED", "已提交"), ("DRAFT", "未提交")],
                        db_index=True,
                        default="DRAFT",
                        max_length=15,
                        verbose_name="提交状态",
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("NOT_READY", "未到审核时机"),
                            ("OWNER_PENDING", "待货主管理员审核"),
                            ("OWNER_APPROVED", "货主管理员已审核通过,待仓库确认"),
                            ("OWNER_REJECTED", "货主管理员已驳回"),
                            ("WHS_PENDING", "待仓库管理员确认"),
                            ("WHS_APPROVED", "仓库管理员已确认,待收货"),
                            ("WHS_REJECTED", "仓库管理员已驳回"),
                            ("CANCELLED", "已取消"),
                        ],
                        db_index=True,
                        default="NOT_READY",
                        max_length=15,
                        verbose_name="审核状态",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="地址"
                    ),
                ),
                (
                    "memo",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="备注"
                    ),
                ),
                (
                    "is_closed",
                    models.BooleanField(default=False, verbose_name="订单关闭"),
                ),
                (
                    "close_reason",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="关闭理由"
                    ),
                ),
                (
                    "approved_at_ownermanager",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="货主管理员审核时间"
                    ),
                ),
                (
                    "approved_at_warehouse",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="仓库管理员审核时间"
                    ),
                ),
                (
                    "next_line_no",
                    models.PositiveIntegerField(
                        default=10, verbose_name="下一个订单行号"
                    ),
                ),
                (
                    "approved_by_ownermanager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appr_by_owner_in_ord",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="货主管理员审核人",
                    ),
                ),
                (
                    "approved_by_warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appr_by_wh_inbound_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="仓库管理员审核人",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="制表人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inbound_orders",
                        to="baseinfo.owner",
                        verbose_name="货主",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inbound_orders",
                        to="baseinfo.supplier",
                        verbose_name="供应商",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inbound_orders",
                        to="locations.warehouse",
                        verbose_name="仓库",
                    ),
                ),
            ],
            options={
                "verbose_name": "入库订单",
                "verbose_name_plural": "入库订单",
                "ordering": ["-biz_date", "-id"],
                "permissions": [
                    ("approve_as_owner_manager", "货主管理员可执行审核动作"),
                    ("approve_as_wh_manager", "仓库管理员可执行确认动作"),
                    ("submit_as_owner_buyers", "货主业务员可提交入库订单"),
                ],
            },
        ),
        migrations.CreateModel(
            name="InboundOrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="已删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用状态"),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "base_uom",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="基本单位"
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=14,
                        verbose_name="基本价格",
                    ),
                ),
                (
                    "base_qty",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=18,
                        verbose_name="基本数量",
                    ),
                ),
                (
                    "aux_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=14,
                        null=True,
                        verbose_name="包装价格",
                    ),
                ),
                (
                    "aux_qty",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=18,
                        null=True,
                        verbose_name="包装数量",
                    ),
                ),
                (
                    "ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=14,
                        null=True,
                        verbose_name="换算率",
                    ),
                ),
                ("line_no", models.PositiveIntegerField(verbose_name="行号")),
                (
                    "lot_no",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="批号"
                    ),
                ),
                (
                    "min_remaining_days",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="最短剩余效期(天)"
                    ),
                ),
                (
                    "expiry_not_earlier_than",
                    models.DateField(
                        blank=True, null=True, verbose_name="到期不得早于"
                    ),
                ),
                (
                    "pack_requirement",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="打包要求"
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="明细备注"
                    ),
                ),
                (
                    "aux_uom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="products.productpackage",
                        verbose_name="包装单位",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="inbound.inboundorder",
                        verbose_name="订单",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="products.product",
                        verbose_name="商品",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "入库订单行",
                "verbose_name_plural": "入库订单行",
                "ordering": ["order_id", "line_no"],
            },
        ),
        migrations.CreateModel(
            name="InboundOrderReturnInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="已删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用状态"),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "rma_no",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="退货授权号"
                    ),
                ),
                (
                    "source_channel",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ONLINE", "线上"),
                            ("STORE", "门店"),
                            ("THIRD_PARTY", "三方/3PL"),
                            ("OTHER", "其他"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="来源渠道",
                    ),
                ),
                (
                    "orig_outbound_order_no",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="原出库单号"
                    ),
                ),
                (
                    "reason_code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="退货原因"
                    ),
                ),
                (
                    "photos_required",
                    models.BooleanField(default=False, verbose_name="需要照片"),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="退款金额",
                    ),
                ),
                (
                    "refund_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PENDING", "待处理"),
                            ("APPROVED", "已通过"),
                            ("PAID", "已退款"),
                            ("REJECTED", "已驳回"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="退款状态",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_info",
                        to="inbound.inboundorder",
                        verbose_name="入库订单",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "销售退货入库",
                "verbose_name_plural": "销售退货入库",
            },
        ),
        migrations.CreateModel(
            name="InboundReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="已删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用状态"),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "receipt_no",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="单据编号"
                    ),
                ),
                ("biz_date", models.DateField(verbose_name="日期")),
                (
                    "order_no_snap",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="关联订单编号(快照)",
                    ),
                ),
                (
                    "inbound_type",
                    models.CharField(
                        choices=[
                            ("PURCHASE", "采购入库"),
                            ("CUST_RETURN", "退货入库"),
                            ("TRANSFER", "调拨入库"),
                            ("OTHER_IN", "其他入库"),
                        ],
                        default="PURCHASE",
                        max_length=16,
                        verbose_name="入库类型",
                    ),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        blank=True,
                        choices=[("CIF", "到岸"), ("DISPATCH", "派车")],
                        max_length=16,
                        null=True,
                        verbose_name="交货方式",
                    ),
                ),
                (
                    "submit_status",
                    models.CharField(
                        choices=[("SUBMITTED", "提交"), ("DRAFT", "未提交")],
                        db_index=True,
                        default="DRAFT",
                        max_length=16,
                        verbose_name="提交状态",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="地址"
                    ),
                ),
                (
                    "stevedore_team",
                    models.CharField(
                        blank=True, max_length=80, null=True, verbose_name="装卸队"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="审核时间"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_inbound_receipts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审核人",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "made_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="made_inbound_receipts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="制单人",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipts",
                        to="inbound.inboundorder",
                        verbose_name="关联订单",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inbound_receipts",
                        to="baseinfo.owner",
                        verbose_name="货主",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inbound_receipts",
                        to="baseinfo.supplier",
                        verbose_name="供应商",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inbound_receipts",
                        to="locations.warehouse",
                        verbose_name="所属仓库",
                    ),
                ),
            ],
            options={
                "verbose_name": "入库收货单",
                "verbose_name_plural": "入库收货单",
                "ordering": ["-biz_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="InboundReceiptLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="已删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用状态"),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
                ("line_no", models.PositiveIntegerField(verbose_name="行号")),
                (
                    "product_code",
                    models.CharField(max_length=60, verbose_name="商品编号"),
                ),
                ("product_name", models.CharField(max_length=120, verbose_name="名称")),
                (
                    "spec",
                    models.CharField(
                        blank=True, max_length=120, null=True, verbose_name="规格型号"
                    ),
                ),
                (
                    "sku_barcode",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="SKU条码(快照)",
                    ),
                ),
                (
                    "order_qty",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=14,
                        null=True,
                        verbose_name="订购数量",
                    ),
                ),
                (
                    "base_qty",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=14,
                        verbose_name="本次入库数(基本单位)",
                    ),
                ),
                (
                    "base_uom",
                    models.CharField(max_length=20, verbose_name="基本单位(快照)"),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=14,
                        verbose_name="单价(每基本单位)",
                    ),
                ),
                (
                    "pack_code",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="包装编码(快照)",
                    ),
                ),
                (
                    "pack_size",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=18,
                        null=True,
                        verbose_name="换算(基本单位/包,快照)",
                    ),
                ),
                (
                    "pack_qty",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=14,
                        null=True,
                        verbose_name="本次包数(快照)",
                    ),
                ),
                (
                    "pack_barcode",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="包装条码(快照)",
                    ),
                ),
                (
                    "lot_no",
                    models.CharField(
                        blank=True, max_length=60, null=True, verbose_name="批号"
                    ),
                ),
                (
                    "mfg_date",
                    models.DateField(blank=True, null=True, verbose_name="生产日期"),
                ),
                (
                    "exp_date",
                    models.DateField(blank=True, null=True, verbose_name="有效期至"),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inbound_receipt_lines",
                        to="locations.location",
                        verbose_name="仓位",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="products.product",
                        verbose_name="商品",
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="inbound.inboundreceipt",
                        verbose_name="入库单",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "入库单明细",
                "verbose_name_plural": "入库单明细",
                "ordering": ["receipt_id", "line_no"],
            },
        ),
        migrations.CreateModel(
            name="Lot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="已删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用状态"),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "product_code",
                    models.CharField(max_length=60, verbose_name="商品编号(快照)"),
                ),
                ("lot_no", models.CharField(max_length=60, verbose_name="批号")),
                (
                    "lot_no_norm",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="批号(规范化)"
                    ),
                ),
                (
                    "mfg_date",
                    models.DateField(blank=True, null=True, verbose_name="生产日期"),
                ),
                (
                    "exp_date",
                    models.DateField(blank=True, null=True, verbose_name="有效期至"),
                ),
                (
                    "default_qa_status",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="默认质检状态",
                    ),
                ),
                (
                    "extra",
                    models.JSONField(blank=True, default=dict, verbose_name="扩展属性"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lots",
                        to="baseinfo.owner",
                        verbose_name="货主",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lots",
                        to="products.product",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lots",
                        to="baseinfo.supplier",
                        verbose_name="供应商",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "批次",
                "verbose_name_plural": "批次",
                "ordering": ["product_code", "lot_no"],
            },
        ),
        migrations.CreateModel(
            name="LotWarehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="已删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用状态"),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "qa_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("RELEASED", "可用"),
                            ("HOLD", "冻结/待检"),
                            ("QUARANTINE", "隔离"),
                            ("RETURN", "待退供应商"),
                            ("SCRAP_PENDING", "待报废"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="质检状态",
                    ),
                ),
                (
                    "blocked_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="解封时间"
                    ),
                ),
                (
                    "blocked_reason",
                    models.CharField(
                        blank=True, max_length=120, null=True, verbose_name="冻结原因"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="warehouses",
                        to="inbound.lot",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lot_warehouses",
                        to="baseinfo.owner",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lot_warehouses",
                        to="locations.warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "批次-仓库状态",
                "verbose_name_plural": "批次-仓库状态",
                "ordering": ["warehouse_id", "lot_id"],
            },
        ),
        migrations.CreateModel(
            name="ReturnInspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="已删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用状态"),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "lot_no",
                    models.CharField(
                        blank=True, max_length=60, null=True, verbose_name="批号"
                    ),
                ),
                (
                    "exp_date",
                    models.DateField(blank=True, null=True, verbose_name="有效期至"),
                ),
                (
                    "serial_no",
                    models.CharField(
                        blank=True, max_length=60, null=True, verbose_name="序列号"
                    ),
                ),
                (
                    "serial_no_norm",
                    models.CharField(
                        blank=True,
                        max_length=60,
                        null=True,
                        verbose_name="序列号(归一)",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "全新"),
                            ("B", "完好"),
                            ("C", "轻微问题"),
                            ("D", "严重问题"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="品相",
                    ),
                ),
                (
                    "disposition",
                    models.CharField(
                        choices=[
                            ("RESTOCK", "再上架"),
                            ("REFURBISH", "翻新"),
                            ("REPAIR", "返修"),
                            ("SCRAP", "报废"),
                            ("RTV", "退供应商"),
                        ],
                        max_length=20,
                        verbose_name="处置",
                    ),
                ),
                (
                    "qty",
                    models.DecimalField(
                        decimal_places=3, max_digits=14, verbose_name="数量"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "待审核"),
                            ("APPROVED", "已审核"),
                            ("POSTED", "已下发执行"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=10,
                        verbose_name="状态",
                    ),
                ),
                (
                    "inspected_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="检验时间"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="审核时间"
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_return_inspections",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审核人",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "inspected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="检验人",
                    ),
                ),
                (
                    "order_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inspections",
                        to="inbound.inboundorderline",
                        verbose_name="来源订单行",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_inspections",
                        to="baseinfo.owner",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_inspections",
                        to="locations.warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "退货检验处置",
                "verbose_name_plural": "退货检验处置",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="inboundorder",
            index=models.Index(
                fields=["owner", "biz_date", "submit_status"],
                name="ii_order_owner_date_status",
            ),
        ),
        migrations.AddIndex(
            model_name="inboundorder",
            index=models.Index(
                fields=["approval_status"], name="ii_order_approval_status"
            ),
        ),
        migrations.AddConstraint(
            model_name="inboundorder",
            constraint=models.CheckConstraint(
                condition=models.Q(("submit_status__in", ["DRAFT", "SUBMITTED"])),
                name="chk_inb_submit_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="inboundorder",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "approval_status__in",
                        [
                            "NOT_READY",
                            "OWNER_PENDING",
                            "OWNER_APPROVED",
                            "OWNER_REJECTED",
                            "WHS_PENDING",
                            "WHS_APPROVED",
                            "WHS_REJECTED",
                            "CANCELLED",
                        ],
                    )
                ),
                name="valid_approval_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="inboundorder",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_closed", True),
                    ("approval_status__in", ["CANCELLED"]),
                    _negated=True,
                ),
                name="close_approval_status_check",
            ),
        ),
        migrations.AddIndex(
            model_name="inboundorderline",
            index=models.Index(
                fields=["order", "product"], name="idx_inb_order_product"
            ),
        ),
        migrations.AddIndex(
            model_name="inboundorderline",
            index=models.Index(
                fields=["product", "lot_no"], name="idx_inb_product_lot"
            ),
        ),
        migrations.AddIndex(
            model_name="inboundorderline",
            index=models.Index(fields=["order", "lot_no"], name="idx_inb_order_lot"),
        ),
        migrations.AddConstraint(
            model_name="inboundorderline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("aux_uom__isnull", True), ("ratio__gt", 0), _connector="OR"
                ),
                name="chk_inb_ratio_pos_when_aux",
            ),
        ),
        migrations.AddConstraint(
            model_name="inboundorderline",
            constraint=models.UniqueConstraint(
                fields=("order", "line_no"), name="ux_inb_order_line_no"
            ),
        ),
        migrations.AddConstraint(
            model_name="inboundorderline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("base_qty__gt", 0), ("aux_qty__gt", 0), _connector="OR"
                ),
                name="chk_inb_qty_one_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="inboundorderline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("base_qty__gte", 0),
                    models.Q(
                        ("aux_qty__gte", 0), ("aux_qty__isnull", True), _connector="OR"
                    ),
                ),
                name="chk_inb_qty_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="inboundorderline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("base_price__gte", 0),
                    models.Q(
                        ("aux_price__gte", 0),
                        ("aux_price__isnull", True),
                        _connector="OR",
                    ),
                ),
                name="chk_inb_price_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="inboundorderreturninfo",
            index=models.Index(fields=["rma_no"], name="ix_ret_rma_no"),
        ),
        migrations.AddIndex(
            model_name="inboundorderreturninfo",
            index=models.Index(
                fields=["orig_outbound_order_no"], name="ix_ret_orig_out_no"
            ),
        ),
        migrations.AddIndex(
            model_name="inboundorderreturninfo",
            index=models.Index(fields=["refund_status"], name="ix_ret_refund_status"),
        ),
        migrations.AddIndex(
            model_name="inboundorderreturninfo",
            index=models.Index(fields=["source_channel"], name="ix_ret_src_channel"),
        ),
        migrations.AddConstraint(
            model_name="inboundorderreturninfo",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("refund_amount__isnull", True),
                    ("refund_amount__gte", 0),
                    _connector="OR",
                ),
                name="ck_ret_refund_nonneg",
            ),
        ),
        migrations.AddIndex(
            model_name="inboundreceipt",
            index=models.Index(
                fields=["owner", "submit_status", "biz_date"],
                name="ix_rcpt_own_stat_date",
            ),
        ),
        migrations.AddIndex(
            model_name="inboundreceipt",
            index=models.Index(
                fields=["supplier", "biz_date"], name="ix_rcpt_sup_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="inboundreceipt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("approved_at__isnull", True), ("approved_by__isnull", True)
                    ),
                    models.Q(
                        ("approved_at__isnull", False), ("approved_by__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="chk_rcpt_approved_pair",
            ),
        ),
        migrations.AddConstraint(
            model_name="inboundreceipt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("approved_by__isnull", True),
                    ("submit_status", "SUBMITTED"),
                    _connector="OR",
                ),
                name="chk_rcpt_approved_after_submit",
            ),
        ),
        migrations.AddConstraint(
            model_name="inboundreceipt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("made_by__isnull", True),
                    ("submit_status", "SUBMITTED"),
                    _negated=True,
                ),
                name="chk_rcpt_submit_need_maker",
            ),
        ),
        migrations.AddIndex(
            model_name="inboundreceiptline",
            index=models.Index(
                fields=["receipt", "product_code"], name="ix_rcpt_prodcode"
            ),
        ),
        migrations.AddIndex(
            model_name="inboundreceiptline",
            index=models.Index(fields=["product", "lot_no"], name="ix_rcpt_prod_lot"),
        ),
        migrations.AddIndex(
            model_name="inboundreceiptline",
            index=models.Index(
                fields=["receipt", "lot_no", "exp_date"], name="ix_rcpt_lot_exp"
            ),
        ),
        migrations.AddConstraint(
            model_name="inboundreceiptline",
            constraint=models.UniqueConstraint(
                fields=("receipt", "line_no"), name="uq_rcpt_line_no"
            ),
        ),
        migrations.AddConstraint(
            model_name="inboundreceiptline",
            constraint=models.CheckConstraint(
                condition=models.Q(("line_no__gte", 1)), name="ck_rcpt_lineno_pos"
            ),
        ),
        migrations.AddConstraint(
            model_name="inboundreceiptline",
            constraint=models.CheckConstraint(
                condition=models.Q(("base_qty__gte", 0)), name="ck_rcpt_qty_nonneg"
            ),
        ),
        migrations.AddConstraint(
            model_name="inboundreceiptline",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_price__gte", 0)), name="ck_rcpt_price_nonneg"
            ),
        ),
        migrations.AddConstraint(
            model_name="inboundreceiptline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("exp_date__isnull", True),
                    ("mfg_date__isnull", True),
                    ("exp_date__gte", models.F("mfg_date")),
                    _connector="OR",
                ),
                name="ck_rcpt_exp_ge_mfg",
            ),
        ),
        migrations.AddConstraint(
            model_name="inboundreceiptline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("pack_qty__isnull", True),
                    models.Q(("pack_size__isnull", False), ("pack_size__gt", 0)),
                    _connector="OR",
                ),
                name="ck_rcpt_pack_pair",
            ),
        ),
        migrations.AddIndex(
            model_name="lot",
            index=models.Index(
                fields=["owner", "product_code", "exp_date"],
                name="idx_lot_owner_prod_exp",
            ),
        ),
        migrations.AddIndex(
            model_name="lot",
            index=models.Index(
                fields=["owner", "supplier", "product_code"],
                name="idx_lot_owner_supp_prod",
            ),
        ),
        migrations.AddConstraint(
            model_name="lot",
            constraint=models.UniqueConstraint(
                fields=("owner", "product_code", "lot_no_norm"),
                name="ux_lot_owner_prod_lotnorm",
            ),
        ),
        migrations.AddConstraint(
            model_name="lot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("exp_date__isnull", True),
                    ("mfg_date__isnull", True),
                    ("exp_date__gte", models.F("mfg_date")),
                    _connector="OR",
                ),
                name="chk_lot_exp_ge_mfg",
            ),
        ),
        migrations.AddIndex(
            model_name="lotwarehouse",
            index=models.Index(
                fields=["warehouse", "qa_status"], name="idx_lotwh_wh_qastat"
            ),
        ),
        migrations.AddIndex(
            model_name="lotwarehouse",
            index=models.Index(
                fields=["warehouse", "blocked_until"], name="idx_lotwh_wh_blockuntil"
            ),
        ),
        migrations.AddIndex(
            model_name="lotwarehouse",
            index=models.Index(
                fields=["owner", "warehouse", "qa_status"],
                name="idx_lotwh_owner_wh_qastat",
            ),
        ),
        migrations.AddConstraint(
            model_name="lotwarehouse",
            constraint=models.UniqueConstraint(
                fields=("lot", "warehouse"), name="ux_lotwh_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="lotwarehouse",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("blocked_until__isnull", True),
                    models.Q(
                        ("blocked_until__isnull", False),
                        ("blocked_reason__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="ck_lotwh_block_pair",
            ),
        ),
        migrations.AddIndex(
            model_name="returninspection",
            index=models.Index(
                fields=["warehouse", "status", "disposition"],
                name="idx_retinsp_wh_status_disp",
            ),
        ),
        migrations.AddIndex(
            model_name="returninspection",
            index=models.Index(fields=["order_line"], name="idx_retinsp_orderline"),
        ),
        migrations.AddIndex(
            model_name="returninspection",
            index=models.Index(
                fields=["owner", "lot_no"], name="idx_retinsp_owner_lot"
            ),
        ),
        migrations.AddConstraint(
            model_name="returninspection",
            constraint=models.CheckConstraint(
                condition=models.Q(("qty__gt", 0)), name="chk_retinsp_qty_pos"
            ),
        ),
        migrations.AddConstraint(
            model_name="returninspection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("serial_no__isnull", True), ("qty", 1), _connector="OR"
                ),
                name="chk_retinsp_serial_qty_eq1",
            ),
        ),
        migrations.AddConstraint(
            model_name="returninspection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("approved_by__isnull", True), ("approved_at__isnull", True)
                    ),
                    models.Q(
                        ("approved_by__isnull", False), ("approved_at__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="chk_retinsp_approved_pair",
            ),
        ),
        migrations.AddConstraint(
            model_name="returninspection",
            constraint=models.UniqueConstraint(
                fields=("owner", "serial_no_norm"), name="ux_retinsp_owner_serial_norm"
            ),
        ),
    ]
