# Generated by Django 5.2.5 on 2025-10-19 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inbound", "0001_initial"),
        ("locations", "0002_remove_location_zone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inboundorder",
            name="warehouse",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inbound_orders",
                to="locations.warehouse",
                verbose_name="大库",
            ),
        ),
        migrations.AlterField(
            model_name="inboundreceipt",
            name="warehouse",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inbound_receipts",
                to="locations.warehouse",
                verbose_name="所属大仓",
            ),
        ),
        migrations.AlterField(
            model_name="lotwarehouse",
            name="warehouse",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lot_warehouses",
                to="locations.warehouse",
            ),
        ),
        migrations.AlterField(
            model_name="returninspection",
            name="warehouse",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="return_inspections",
                to="locations.warehouse",
            ),
        ),
    ]
