# Generated by Django 5.2.5 on 2026-06-19 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inbound", "0001_initial"),
        ("tasking", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PdaNoOrderReceive",
            fields=[],
            options={
                "verbose_name": "PDA无订单收货",
                "verbose_name_plural": "PDA无订单收货",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("tasking.wmstask",),
        ),
    ]
