# Generated by Django 5.2.5 on 2026-08-07 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0004_operations_report_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboundreceiptline',
            name='product_code',
            field=models.CharField(max_length=60, verbose_name='货主商品编码'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='product_code',
            field=models.CharField(max_length=60, verbose_name='货主商品编码（快照）'),
        ),
    ]
