# Generated by Django 5.2.5 on 2026-02-09 12:18

import datetime
import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.comparison
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("baseinfo", "0002_initial"),
        ("inbound", "0001_initial"),
        ("locations", "0001_initial"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="已删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用状态"),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "zone_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "拣选区"),
                            (2, "存储区"),
                            (3, "收货区"),
                            (4, "发运区"),
                            (5, "退货区"),
                            (6, "整件区"),
                            (7, "拆零区"),
                            (8, "破损区"),
                            (9, "其他"),
                        ],
                        db_index=True,
                        default=1,
                        verbose_name="区域类型",
                    ),
                ),
                (
                    "batch_no",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="批次号"
                    ),
                ),
                (
                    "production_date",
                    models.DateField(blank=True, null=True, verbose_name="生产日期"),
                ),
                (
                    "expiry_date",
                    models.DateField(blank=True, null=True, verbose_name="有效期至"),
                ),
                (
                    "serial_no",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="序列号"
                    ),
                ),
                (
                    "serial_no_norm",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        null=True,
                        verbose_name="序列号(规范化)",
                    ),
                ),
                ("base_unit", models.CharField(max_length=30, verbose_name="基本单位")),
                (
                    "product_serial_control",
                    models.BooleanField(default=False, verbose_name="序列化控制快照"),
                ),
                (
                    "onhand_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="账面库存",
                    ),
                ),
                (
                    "allocated_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="已分配数量",
                    ),
                ),
                (
                    "locked_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="锁定数量",
                    ),
                ),
                (
                    "damaged_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="损坏数量",
                    ),
                ),
                (
                    "available_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="可用数量",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="locations.location",
                        verbose_name="库位",
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inbound.lot",
                        verbose_name="批次",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="baseinfo.owner",
                        verbose_name="货主",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="products.product",
                        verbose_name="商品",
                    ),
                ),
                (
                    "subwarehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="locations.subwarehouse",
                        verbose_name="仓库",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        default=1,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="locations.warehouse",
                        verbose_name="仓库",
                    ),
                ),
            ],
            options={
                "verbose_name": "库存现存量",
                "verbose_name_plural": "库存现存量",
            },
        ),
        migrations.CreateModel(
            name="InventoryQuickInboundAdjust",
            fields=[],
            options={
                "verbose_name": "入库快调",
                "verbose_name_plural": "入库快调",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("inventory.inventorydetail",),
        ),
        migrations.CreateModel(
            name="InventoryQuickOutboundAdjust",
            fields=[],
            options={
                "verbose_name": "出库快调",
                "verbose_name_plural": "出库快调",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("inventory.inventorydetail",),
        ),
        migrations.CreateModel(
            name="InventorySummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="已删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用状态"),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
                ("base_unit", models.CharField(max_length=30, verbose_name="基本单位")),
                (
                    "onhand_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="账面库存",
                    ),
                ),
                (
                    "allocated_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="已分配数量",
                    ),
                ),
                (
                    "locked_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="锁定数量",
                    ),
                ),
                (
                    "damaged_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="损坏数量",
                    ),
                ),
                (
                    "available_qty",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="可用数量",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="baseinfo.owner",
                        verbose_name="货主",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="products.product",
                        verbose_name="商品",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "库存汇总",
                "verbose_name_plural": "库存汇总",
            },
        ),
        migrations.CreateModel(
            name="InventoryTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="已删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用状态"),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "tx_type",
                    models.CharField(
                        choices=[
                            ("MOVE_IN", "移入"),
                            ("MOVE_OUT", "移出"),
                            ("RECEIVE", "入"),
                            ("ISSUE", "出"),
                            ("ADJ_GAIN", "调整增"),
                            ("ADJ_LOSS", "调整减"),
                        ],
                        max_length=16,
                        verbose_name="事务类型",
                    ),
                ),
                (
                    "zone_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "拣选区"),
                            (2, "存储区"),
                            (3, "收货区"),
                            (4, "发运区"),
                            (5, "退货区"),
                            (6, "整件区"),
                            (7, "拆零区"),
                            (8, "破损区"),
                            (9, "其他"),
                        ],
                        db_index=True,
                        default=1,
                        verbose_name="区域类型",
                    ),
                ),
                (
                    "batch_no",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="批次号"
                    ),
                ),
                (
                    "production_date",
                    models.DateField(blank=True, null=True, verbose_name="生产日期"),
                ),
                (
                    "expiry_date",
                    models.DateField(blank=True, null=True, verbose_name="有效期至"),
                ),
                (
                    "serial_no",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="序列号"
                    ),
                ),
                (
                    "base_unit",
                    models.CharField(
                        editable=False, max_length=30, verbose_name="基本单位"
                    ),
                ),
                (
                    "qty_delta",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=18,
                        verbose_name="数量变化(+入/-出)",
                    ),
                ),
                (
                    "pair_id",
                    models.UUIDField(
                        blank=True, db_index=True, null=True, verbose_name="配对号"
                    ),
                ),
                ("src_model", models.CharField(max_length=64, verbose_name="来源类型")),
                ("src_id", models.BigIntegerField(verbose_name="来源ID")),
                (
                    "src_line_id",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="来源行ID"
                    ),
                ),
                (
                    "src_no",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="来源单号"
                    ),
                ),
                (
                    "memo",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="备注"
                    ),
                ),
                (
                    "posted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="过账时间"
                    ),
                ),
                (
                    "posting_batch",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=40,
                        null=True,
                        verbose_name="过账批次号",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="locations.location",
                        verbose_name="库位",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="baseinfo.owner",
                        verbose_name="货主",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="products.product",
                        verbose_name="商品",
                    ),
                ),
                (
                    "subwarehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="locations.subwarehouse",
                        verbose_name="仓库",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        default=1,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="locations.warehouse",
                        verbose_name="仓库",
                    ),
                ),
            ],
            options={
                "verbose_name": "库存事务流水",
                "verbose_name_plural": "库存事务流水",
            },
        ),
        migrations.CreateModel(
            name="PostingJournal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "src_model",
                    models.CharField(
                        db_index=True, max_length=32, verbose_name="来源模型"
                    ),
                ),
                (
                    "src_id",
                    models.BigIntegerField(db_index=True, verbose_name="来源ID"),
                ),
                (
                    "tx_type",
                    models.CharField(
                        db_index=True, max_length=16, verbose_name="动作类型"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="PENDING", max_length=16, verbose_name="状态"
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="说明"
                    ),
                ),
                (
                    "attempt_count",
                    models.IntegerField(default=0, verbose_name="尝试次数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["created_at"], name="idx_post_created"),
                    models.Index(fields=["status"], name="idx_post_status"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("src_model", "src_id", "tx_type"),
                        name="uniq_post_src_tx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ReviewDifference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_no",
                    models.CharField(max_length=50, unique=True, verbose_name="单号"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待复核"),
                            ("IN_PROGRESS", "复核中"),
                            ("COMPLETED", "已完成"),
                            ("CANCELLED", "已取消"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, null=True, verbose_name="复核原因"),
                ),
                ("note", models.TextField(blank=True, null=True, verbose_name="备注")),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="复核人",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        default=1,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="locations.warehouse",
                        verbose_name="仓库",
                    ),
                ),
            ],
            options={
                "verbose_name": "复核差异单",
                "verbose_name_plural": "复核差异单",
            },
        ),
        migrations.CreateModel(
            name="ReviewDifferenceLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_no",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="批次号"
                    ),
                ),
                (
                    "serial_no",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="序列号"
                    ),
                ),
                (
                    "quantity_before",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="复核前数量"
                    ),
                ),
                (
                    "quantity_after",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="复核后数量"
                    ),
                ),
                (
                    "quantity_difference",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="差异数量"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待复核"),
                            ("IN_PROGRESS", "复核中"),
                            ("COMPLETED", "已完成"),
                            ("CANCELLED", "已取消"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="差异状态",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="locations.location",
                        verbose_name="库位",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="products.product",
                        verbose_name="商品",
                    ),
                ),
                (
                    "recheck_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="inventory.reviewdifference",
                        verbose_name="复核单",
                    ),
                ),
            ],
            options={
                "verbose_name": "复核差异单明细",
                "verbose_name_plural": "复核差异单明细",
            },
        ),
        migrations.AddIndex(
            model_name="inventorydetail",
            index=models.Index(
                models.F("owner"),
                models.F("product"),
                models.F("warehouse"),
                models.F("location"),
                django.db.models.functions.comparison.Coalesce(
                    models.F("expiry_date"), models.Value(datetime.date(9999, 12, 31))
                ),
                name="idx_inv_fefo_mysql",
            ),
        ),
        migrations.AddIndex(
            model_name="inventorydetail",
            index=models.Index(
                models.F("owner"),
                models.F("product"),
                django.db.models.functions.text.Upper(
                    django.db.models.functions.comparison.Coalesce(
                        models.F("batch_no"), models.Value("")
                    )
                ),
                name="idx_inv_owner_prod_batch_mysql",
            ),
        ),
        migrations.AddIndex(
            model_name="inventorydetail",
            index=models.Index(
                models.F("owner"),
                models.F("product"),
                django.db.models.functions.comparison.Coalesce(
                    models.F("expiry_date"), models.Value(datetime.date(1000, 1, 1))
                ),
                name="idx_inv_owner_prod_exp",
            ),
        ),
        migrations.AddIndex(
            model_name="inventorydetail",
            index=models.Index(
                fields=["warehouse", "subwarehouse", "location", "product"],
                name="idx_inv_loc_product_mysql",
            ),
        ),
        migrations.AddIndex(
            model_name="inventorydetail",
            index=models.Index(fields=["is_active"], name="idx_inv_is_active"),
        ),
        migrations.AddConstraint(
            model_name="inventorydetail",
            constraint=models.UniqueConstraint(
                models.F("owner"),
                models.F("product"),
                models.F("warehouse"),
                models.F("location"),
                django.db.models.functions.text.Upper(
                    django.db.models.functions.comparison.Coalesce(
                        models.F("batch_no"), models.Value("")
                    )
                ),
                django.db.models.functions.comparison.Coalesce(
                    models.F("production_date"), models.Value(datetime.date(1000, 1, 1))
                ),
                django.db.models.functions.comparison.Coalesce(
                    models.F("expiry_date"), models.Value(datetime.date(1000, 1, 1))
                ),
                django.db.models.functions.text.Upper(
                    django.db.models.functions.comparison.Coalesce(
                        models.F("serial_no"), models.Value("")
                    )
                ),
                models.F("is_active"),
                name="ux_inv_dim_active_mysql",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventorydetail",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("allocated_qty__gte", 0),
                    ("available_qty__gte", 0),
                    ("damaged_qty__gte", 0),
                    ("locked_qty__gte", 0),
                    ("onhand_qty__gte", 0),
                ),
                name="chk_inv_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventorydetail",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("product_serial_control", False),
                    models.Q(
                        ("allocated_qty__lte", 1),
                        ("available_qty__lte", 1),
                        ("damaged_qty__lte", 1),
                        ("locked_qty__lte", 1),
                        ("onhand_qty__lte", 1),
                    ),
                    _connector="OR",
                ),
                name="chk_inv_serial_qty_le_one",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventorydetail",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "available_qty",
                        django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(
                                django.db.models.expressions.CombinedExpression(
                                    models.F("onhand_qty"),
                                    "-",
                                    models.F("allocated_qty"),
                                ),
                                "-",
                                models.F("locked_qty"),
                            ),
                            "-",
                            models.F("damaged_qty"),
                        ),
                    )
                ),
                name="chk_inv_available_identity",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventorydetail",
            constraint=models.UniqueConstraint(
                fields=("owner", "product", "serial_no_norm", "is_active"),
                name="ux_inv_serial_owner_prod_act",
            ),
        ),
        migrations.AddIndex(
            model_name="inventorysummary",
            index=models.Index(
                fields=["owner", "product"], name="idx_summary_owner_product"
            ),
        ),
        migrations.AddIndex(
            model_name="inventorysummary",
            index=models.Index(fields=["is_active"], name="idx_summary_is_active"),
        ),
        migrations.AddConstraint(
            model_name="inventorysummary",
            constraint=models.UniqueConstraint(
                models.F("owner"),
                models.F("product"),
                django.db.models.functions.comparison.NullIf(
                    models.F("is_active"),
                    models.Value(False),
                    output_field=models.BooleanField(),
                ),
                name="ux_sum_owner_prod_active_only",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventorysummary",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("onhand_qty__gte", 0),
                    ("available_qty__gte", 0),
                    ("allocated_qty__gte", 0),
                    ("locked_qty__gte", 0),
                    ("damaged_qty__gte", 0),
                ),
                name="chk_invsummary_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventorysummary",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "available_qty",
                        django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(
                                django.db.models.expressions.CombinedExpression(
                                    models.F("onhand_qty"),
                                    "-",
                                    models.F("allocated_qty"),
                                ),
                                "-",
                                models.F("locked_qty"),
                            ),
                            "-",
                            models.F("damaged_qty"),
                        ),
                    )
                ),
                name="chk_sum_avail_identity",
            ),
        ),
        migrations.AddIndex(
            model_name="inventorytransaction",
            index=models.Index(
                fields=["tx_type", "owner", "product"], name="idx_tx_type_owner_product"
            ),
        ),
        migrations.AddIndex(
            model_name="inventorytransaction",
            index=models.Index(fields=["warehouse", "location"], name="idx_tx_wh_loc"),
        ),
        migrations.AddIndex(
            model_name="inventorytransaction",
            index=models.Index(
                fields=["owner", "product", "batch_no"], name="idx_tx_batch"
            ),
        ),
        migrations.AddIndex(
            model_name="inventorytransaction",
            index=models.Index(
                fields=["owner", "product", "expiry_date"], name="idx_tx_expiry"
            ),
        ),
        migrations.AddIndex(
            model_name="inventorytransaction",
            index=models.Index(
                fields=["owner", "product", "serial_no"], name="idx_tx_serial"
            ),
        ),
        migrations.AddIndex(
            model_name="inventorytransaction",
            index=models.Index(fields=["src_model", "src_id"], name="idx_tx_src"),
        ),
        migrations.AddIndex(
            model_name="inventorytransaction",
            index=models.Index(fields=["pair_id"], name="idx_tx_pair"),
        ),
        migrations.AddIndex(
            model_name="inventorytransaction",
            index=models.Index(fields=["posted_at"], name="idx_tx_posted_at"),
        ),
        migrations.AddIndex(
            model_name="inventorytransaction",
            index=models.Index(fields=["posting_batch"], name="idx_tx_posting_batch"),
        ),
        migrations.AddConstraint(
            model_name="inventorytransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("location__isnull", False)),
                name="ck_tx_location_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventorytransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("qty_delta", 0), _negated=True),
                name="ck_tx_qty_non_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventorytransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("tx_type", "RECEIVE"), ("qty_delta__gt", 0)),
                    models.Q(("tx_type", "ISSUE"), ("qty_delta__lt", 0)),
                    ("tx_type__in", ["ADJ_GAIN", "ADJ_LOSS"]),
                    _connector="OR",
                ),
                name="ck_tx_sign_by_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventorytransaction",
            constraint=models.UniqueConstraint(
                fields=("src_model", "src_id", "src_line_id", "tx_type"),
                name="ux_tx_src_unique",
            ),
        ),
    ]
