# Generated by Django 5.2.5 on 2026-06-23 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        ("locations", "0003_clarify_warehouse_subwarehouse_scope"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorydetail",
            name="subwarehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="locations.subwarehouse",
                verbose_name="子仓",
            ),
        ),
        migrations.AlterField(
            model_name="inventorytransaction",
            name="subwarehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="locations.subwarehouse",
                verbose_name="子仓",
            ),
        ),
    ]
