# Generated by Django 5.2.5 on 2025-10-18 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventorydetail",
            name="zone",
        ),
    ]
