# Generated by Django 5.2.5 on 2025-10-18 15:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_remove_inventorydetail_zone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorydetail",
            name="available_qty",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                max_digits=18,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="可用数量",
            ),
        ),
        migrations.AlterField(
            model_name="inventorydetail",
            name="base_unit",
            field=models.CharField(max_length=30, verbose_name="基本单位"),
        ),
        migrations.AlterField(
            model_name="inventorydetail",
            name="product_serial_control",
            field=models.BooleanField(default=False, verbose_name="序列化控制快照"),
        ),
        migrations.AlterField(
            model_name="inventorysummary",
            name="allocated_qty",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                max_digits=18,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="已分配数量",
            ),
        ),
        migrations.AlterField(
            model_name="inventorysummary",
            name="available_qty",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                max_digits=18,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="可用数量",
            ),
        ),
        migrations.AlterField(
            model_name="inventorysummary",
            name="base_unit",
            field=models.CharField(max_length=30, verbose_name="基本单位"),
        ),
        migrations.AlterField(
            model_name="inventorysummary",
            name="damaged_qty",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                max_digits=18,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="损坏数量",
            ),
        ),
        migrations.AlterField(
            model_name="inventorysummary",
            name="locked_qty",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                max_digits=18,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="锁定数量",
            ),
        ),
        migrations.AlterField(
            model_name="inventorysummary",
            name="onhand_qty",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                max_digits=18,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="账面库存",
            ),
        ),
    ]
