# Generated by Django 5.2.5 on 2025-10-19 01:41

import datetime
import django.db.models.deletion
import django.db.models.functions.comparison
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseinfo", "0004_remove_carriercompany_idx_carrier_wh_center_and_more"),
        ("inbound", "0003_alter_inboundorder_warehouse_and_more"),
        ("inventory", "0003_alter_inventorydetail_available_qty_and_more"),
        ("locations", "0002_remove_location_zone"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="inventorydetail",
            name="ux_inv_dim_active_mysql",
        ),
        migrations.AlterField(
            model_name="inventorydetail",
            name="warehouse",
            field=models.ForeignKey(
                default=1,
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                to="locations.warehouse",
                verbose_name="仓库",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventorydetail",
            constraint=models.UniqueConstraint(
                models.F("owner"),
                models.F("product"),
                models.F("warehouse"),
                models.F("location"),
                django.db.models.functions.text.Upper(
                    django.db.models.functions.comparison.Coalesce(
                        models.F("batch_no"), models.Value("")
                    )
                ),
                django.db.models.functions.comparison.Coalesce(
                    models.F("production_date"), models.Value(datetime.date(1000, 1, 1))
                ),
                django.db.models.functions.comparison.Coalesce(
                    models.F("expiry_date"), models.Value(datetime.date(1000, 1, 1))
                ),
                django.db.models.functions.text.Upper(
                    django.db.models.functions.comparison.Coalesce(
                        models.F("serial_no"), models.Value("")
                    )
                ),
                models.F("is_active"),
                name="ux_inv_dim_active_mysql",
            ),
        ),
    ]
