# Generated by Django 5.2.5 on 2025-10-19 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_remove_inventorydetail_ux_inv_dim_active_mysql_and_more"),
        ("locations", "0002_remove_location_zone"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorytransaction",
            name="subwarehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="locations.subwarehouse",
                verbose_name="仓库",
            ),
        ),
        migrations.AddField(
            model_name="inventorytransaction",
            name="zone_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "拣选区"),
                    (2, "存储区"),
                    (3, "收货区"),
                    (4, "发运区"),
                    (5, "退货区"),
                    (6, "整件区"),
                    (7, "拆零区"),
                    (8, "破损区"),
                    (9, "其他"),
                ],
                db_index=True,
                default=1,
                verbose_name="区域类型",
            ),
        ),
        migrations.AlterField(
            model_name="inventorytransaction",
            name="warehouse",
            field=models.ForeignKey(
                default=1,
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                to="locations.warehouse",
                verbose_name="仓库",
            ),
        ),
        migrations.AlterField(
            model_name="reviewdifference",
            name="warehouse",
            field=models.ForeignKey(
                default=1,
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                to="locations.warehouse",
                verbose_name="仓库",
            ),
        ),
    ]
