# Generated by Django 5.2.5 on 2025-11-08 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_inventorytransaction_subwarehouse_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryQuickInboundAdjust",
            fields=[],
            options={
                "verbose_name": "入库快调",
                "verbose_name_plural": "入库快调",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("inventory.inventorydetail",),
        ),
        migrations.CreateModel(
            name="InventoryQuickOutboundAdjust",
            fields=[],
            options={
                "verbose_name": "出库快调",
                "verbose_name_plural": "出库快调",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("inventory.inventorydetail",),
        ),
    ]
