# Generated by Django 5.2.5 on 2026-08-05 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseinfo", "0005_ownerwarehousebinding"),
        ("inbound", "0004_operations_report_indexes"),
        ("inventory", "0009_inventory_snapshot_unit_source"),
        ("locations", "0004_alter_location_zone_type"),
        ("products", "0004_productcategory_mall_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryCostLayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_no", models.CharField(blank=True, default="", max_length=64)),
                ("serial_no", models.CharField(blank=True, default="", max_length=64)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "received_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                ("original_qty", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "cost_currency",
                    models.CharField(blank=True, default="", max_length=8),
                ),
                (
                    "cost_quality",
                    models.CharField(
                        choices=[
                            ("VERIFIED", "可信"),
                            ("COST_MISSING", "成本缺失"),
                            ("LEGACY_OPENING", "遗留期初"),
                        ],
                        default="COST_MISSING",
                        max_length=20,
                    ),
                ),
                ("source_type", models.CharField(max_length=40)),
                ("source_id", models.CharField(max_length=80)),
                (
                    "source_line_id",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inbound.lot",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="baseinfo.owner"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="products.product",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="locations.warehouse",
                    ),
                ),
                (
                    "base_uom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_cost_layers",
                        to="products.productuom",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InventoryCostAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_unit_cost",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                ("new_unit_cost", models.DecimalField(decimal_places=6, max_digits=18)),
                (
                    "old_currency",
                    models.CharField(blank=True, default="", max_length=8),
                ),
                ("new_currency", models.CharField(max_length=8)),
                ("reason", models.CharField(max_length=200)),
                ("effective_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "layer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cost_adjustments",
                        to="inventory.inventorycostlayer",
                    ),
                ),
            ],
            options={
                "ordering": ["effective_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="InventoryLayerMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("RECEIVE", "收货"),
                            ("MOVE", "移库"),
                            ("ISSUE", "出库"),
                            ("ADJUST", "调整"),
                            ("COST_ADJUST", "成本调整"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                ("occurred_at", models.DateTimeField()),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cost_layer_moves_out",
                        to="locations.location",
                    ),
                ),
                (
                    "inventory_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.inventorytransaction",
                    ),
                ),
                (
                    "layer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="inventory.inventorycostlayer",
                    ),
                ),
                (
                    "to_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cost_layer_moves_in",
                        to="locations.location",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InventoryLayerPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remaining_qty", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "container_scope_id",
                    models.PositiveBigIntegerField(default=0, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "container",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="locations.container",
                    ),
                ),
                (
                    "layer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="positions",
                        to="inventory.inventorycostlayer",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="locations.location",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="inventorycostlayer",
            index=models.Index(
                fields=["owner", "warehouse", "product", "received_date"],
                name="ix_cost_layer_fifo",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventorycostlayer",
            constraint=models.CheckConstraint(
                condition=models.Q(("original_qty__gt", 0)),
                name="chk_cost_layer_qty_pos",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventorycostlayer",
            constraint=models.UniqueConstraint(
                fields=(
                    "source_type",
                    "source_id",
                    "source_line_id",
                    "product",
                    "batch_no",
                    "serial_no",
                ),
                name="ux_cost_layer_source_dim",
            ),
        ),
        migrations.AddIndex(
            model_name="inventorylayermovement",
            index=models.Index(
                fields=["layer", "occurred_at"], name="ix_layer_move_time"
            ),
        ),
        migrations.AddConstraint(
            model_name="inventorylayermovement",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="chk_layer_move_qty_pos"
            ),
        ),
        migrations.AddIndex(
            model_name="inventorylayerposition",
            index=models.Index(
                fields=["location", "layer"], name="ix_layer_pos_location"
            ),
        ),
        migrations.AddConstraint(
            model_name="inventorylayerposition",
            constraint=models.CheckConstraint(
                condition=models.Q(("remaining_qty__gte", 0)),
                name="chk_layer_pos_qty_nonneg",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventorylayerposition",
            constraint=models.UniqueConstraint(
                fields=("layer", "location", "container_scope_id"),
                name="ux_layer_position",
            ),
        ),
    ]
