# Generated by Django 5.2.5 on 2026-04-24 20:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="已删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用状态"),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="省"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="市"
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="区"
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        blank=True, max_length=80, null=True, verbose_name="路/街道"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="详细地址"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="邮编"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, max_length=30, verbose_name="客户编号"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="客户名称"
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True, max_length=80, null=True, verbose_name="联系人"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="联系电话"
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="移动电话"
                    ),
                ),
                (
                    "qq",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="QQ"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="电子邮箱"
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=60,
                        null=True,
                        verbose_name="客户区域",
                    ),
                ),
                (
                    "delivery_route",
                    models.CharField(
                        blank=True, max_length=60, null=True, verbose_name="配送线路"
                    ),
                ),
                (
                    "delivery_seq",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="配送序号",
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="客户等级",
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True, max_length=60, null=True, verbose_name="银行"
                    ),
                ),
                (
                    "bank_account",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="银行账号"
                    ),
                ),
                (
                    "delivery_distance_km",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="配送距离(公里)",
                    ),
                ),
                (
                    "promised_days",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="应达天数",
                    ),
                ),
                (
                    "external_code",
                    models.CharField(
                        blank=True,
                        max_length=60,
                        null=True,
                        verbose_name="客户接口对照编号",
                    ),
                ),
            ],
            options={
                "verbose_name": "终端客户",
                "verbose_name_plural": "终端客户管理",
                "ordering": ["owner_id", "code"],
            },
        ),
        migrations.CreateModel(
            name="DictCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="已删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用状态"),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="分类编码",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="分类名称")),
                (
                    "is_locked",
                    models.BooleanField(default=False, verbose_name="锁定（禁止删除）"),
                ),
            ],
            options={
                "verbose_name": "数据字典分类",
                "verbose_name_plural": "数据字典分类",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="DictItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="已删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用状态"),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="条目编码"
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="条目名称")),
                (
                    "value",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="条目值"
                    ),
                ),
                (
                    "extra",
                    models.JSONField(
                        blank=True, null=True, verbose_name="扩展数据(JSON)"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="排序号"),
                ),
            ],
            options={
                "verbose_name": "数据字典条目",
                "verbose_name_plural": "数据字典条目",
                "ordering": ["category_id", "sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="已删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用状态"),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="省"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="市"
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="区"
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        blank=True, max_length=80, null=True, verbose_name="路/街道"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="详细地址"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="邮编"
                    ),
                ),
                ("name", models.CharField(max_length=10, verbose_name="姓名")),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "男"), ("F", "女")],
                        max_length=1,
                        null=True,
                        verbose_name="性别",
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="电话仅允许数字、+、-、空格、()，长度5-20。",
                                regex="^[0-9+\\-\\s()]{5,20}$",
                            )
                        ],
                        verbose_name="手机号码",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="电话号码"
                    ),
                ),
                (
                    "id_number",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="身份证号码"
                    ),
                ),
                (
                    "driver_license_no",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="驾驶证号码"
                    ),
                ),
                (
                    "driver_license_expiry",
                    models.DateField(
                        blank=True, null=True, verbose_name="驾驶证有效期"
                    ),
                ),
            ],
            options={
                "verbose_name": "司机",
                "verbose_name_plural": "司机档案",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="已删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用状态"),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        max_length=30,
                        unique=True,
                        verbose_name="职员代码",
                    ),
                ),
                (
                    "name",
                    models.CharField(db_index=True, max_length=50, verbose_name="姓名"),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "男"), ("F", "女"), ("O", "其他")],
                        max_length=1,
                        null=True,
                        verbose_name="性别",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, max_length=60, null=True, verbose_name="部门"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=60, null=True, verbose_name="职务"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="电话仅允许数字、+、-、空格、()，长度5-20。",
                                regex="^[0-9+\\-\\s()]{5,20}$",
                            )
                        ],
                        verbose_name="联系电话",
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="电话仅允许数字、+、-、空格、()，长度5-20。",
                                regex="^[0-9+\\-\\s()]{5,20}$",
                            )
                        ],
                        verbose_name="移动电话",
                    ),
                ),
                (
                    "birthday",
                    models.DateField(blank=True, null=True, verbose_name="出生年月日"),
                ),
                (
                    "education",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="文化程度"
                    ),
                ),
                (
                    "id_number",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="身份证号"
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True, max_length=60, null=True, verbose_name="银行"
                    ),
                ),
                (
                    "bank_account",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="银行账号"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="住址"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "hire_date",
                    models.DateField(blank=True, null=True, verbose_name="入职日期"),
                ),
                (
                    "leave_date",
                    models.DateField(blank=True, null=True, verbose_name="离职日期"),
                ),
            ],
            options={
                "verbose_name": "公司职员",
                "verbose_name_plural": "公司职员管理",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="已删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用状态"),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="省"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="市"
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="区"
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        blank=True, max_length=80, null=True, verbose_name="路/街道"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="详细地址"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="邮编"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="货主名称"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="货主代码"
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="联系人"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="联系电话"
                    ),
                ),
                (
                    "sms_mobile",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="短信接收号码",
                    ),
                ),
                (
                    "bank_account",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="银行账号"
                    ),
                ),
                (
                    "wx",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="微信"
                    ),
                ),
                (
                    "qq",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="QQ"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "business_license",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="营业执照"
                    ),
                ),
                (
                    "tax_registration",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="税务登记证"
                    ),
                ),
                (
                    "organization_code",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="组织机构代码证",
                    ),
                ),
            ],
            options={
                "verbose_name": "货主",
                "verbose_name_plural": "货主管理",
                "ordering": ["name"],
                "permissions": [("asownermanager", "货主管理员权")],
            },
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="已删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用状态"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        max_length=30,
                        unique=True,
                        verbose_name="线路编号",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="线路名称")),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="备注"
                    ),
                ),
            ],
            options={
                "verbose_name": "线路",
                "verbose_name_plural": "线路管理",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="已删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用状态"),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="省"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="市"
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="区"
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        blank=True, max_length=80, null=True, verbose_name="路/街道"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="详细地址"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="邮编"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="供应商代码"
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="供应商名称")),
                (
                    "contact_person",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="联系人"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="电话仅允许数字、+、-、空格、()，长度5-20。",
                                regex="^[0-9+\\-\\s()]{5,20}$",
                            )
                        ],
                        verbose_name="联系电话",
                    ),
                ),
                (
                    "bank_account",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="银行账号"
                    ),
                ),
                (
                    "qq",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="QQ"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "yb",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="邮编"
                    ),
                ),
            ],
            options={
                "verbose_name": "供应商",
                "verbose_name_plural": "供应商管理",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="已删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用状态"),
                ),
                (
                    "license_no",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="行驶证号"
                    ),
                ),
                (
                    "plate_no",
                    models.CharField(
                        db_index=True, max_length=20, unique=True, verbose_name="车牌号"
                    ),
                ),
                (
                    "use_type",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="用车类型"
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="车型"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="车辆分类"
                    ),
                ),
                (
                    "vin",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="车架号码"
                    ),
                ),
                (
                    "engine_no",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="发动机号"
                    ),
                ),
                (
                    "trailer_no",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="挂车号码"
                    ),
                ),
                (
                    "insurance_no",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="保险单号"
                    ),
                ),
                (
                    "operation_permit_no",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="营运证号"
                    ),
                ),
                (
                    "payload_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="可载重量(kg)",
                    ),
                ),
                (
                    "surcharge_cert_no",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="附加费证号"
                    ),
                ),
                (
                    "length_m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="车长(米)",
                    ),
                ),
                (
                    "volume_m3",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="可载体积(m³)",
                    ),
                ),
                (
                    "maintenance_km",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="保养公里数"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IDLE", "空闲"),
                            ("ON_DUTY", "在岗"),
                            ("MAINT", "保养"),
                            ("DISABLED", "停用"),
                        ],
                        default="IDLE",
                        max_length=20,
                        verbose_name="车辆状态",
                    ),
                ),
                (
                    "warranty_expiry",
                    models.DateField(
                        blank=True, null=True, verbose_name="保修单到期日"
                    ),
                ),
                (
                    "maintenance_due",
                    models.DateField(blank=True, null=True, verbose_name="保养到期日"),
                ),
                (
                    "operation_permit_annual_due",
                    models.DateField(
                        blank=True, null=True, verbose_name="营运证年审到期日"
                    ),
                ),
                (
                    "annual_inspection_due",
                    models.DateField(blank=True, null=True, verbose_name="年检到期日"),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
            ],
            options={
                "verbose_name": "车辆",
                "verbose_name_plural": "车辆档案",
                "ordering": ["plate_no"],
            },
        ),
        migrations.CreateModel(
            name="CarrierCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="已删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用状态"),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="省"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="市"
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="区"
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        blank=True, max_length=80, null=True, verbose_name="路/街道"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="详细地址"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="邮编"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        max_length=30,
                        unique=True,
                        verbose_name="承运公司名称",
                    ),
                ),
                (
                    "manager",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="负责人"
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="手机号码"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="电话号码"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "承运公司",
                "verbose_name_plural": "承运公司档案",
                "ordering": ["name"],
            },
        ),
    ]
