# Generated by Django 5.2.12 on 2026-07-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseinfo", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="owner",
            name="allow_warehouse_assisted_outbound",
            field=models.BooleanField(
                default=False,
                help_text="启用后，具备专用权限的仓库操作员可代该货主新建并完成出库。",
                verbose_name="允许仓库代办出库",
            ),
        ),
    ]
