# Generated by Django 5.2.5 on 2026-03-29 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0002_initial'),
        ('locations', '0002_alter_container_warehouse_alter_location_warehouse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carriercompany',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carrier_company', to='locations.warehouse', verbose_name='所属大仓'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='locations.warehouse', verbose_name='所属大仓'),
        ),
    ]
