# Generated by Django 5.2.5 on 2025-10-18 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseinfo", "0002_initial"),
        ("locations", "0002_remove_location_zone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carriercompany",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="carrier_company",
                to="locations.warehouse",
                verbose_name="所属大仓",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="locations.warehouse",
                verbose_name="所属大仓",
            ),
        ),
    ]
