# Generated by Django 5.2.5 on 2025-10-29 00:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseinfo", "0004_remove_carriercompany_idx_carrier_wh_center_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="owner",
            index=models.Index(
                fields=["name", "code"], name="baseinfo_ow_name_ffd79b_idx"
            ),
        ),
    ]
