# Generated by Django 5.2.5 on 2025-10-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseinfo", "0005_owner_baseinfo_ow_name_ffd79b_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="code",
            field=models.CharField(
                blank=True,
                default=1,
                max_length=100,
                null=True,
                verbose_name="供应商代码",
            ),
            preserve_default=False,
        ),
    ]
