# Generated by Django 5.2.5 on 2025-10-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseinfo", "0006_supplier_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="code",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="供应商代码"
            ),
        ),
    ]
