# Generated by Django 5.2.5 on 2025-10-18 13:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("baseinfo", "0001_initial"),
        ("locations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EtlWatermark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(max_length=40, unique=True)),
                ("watermark_value", models.CharField(max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "ETL水位",
                "verbose_name_plural": "ETL水位",
            },
        ),
        migrations.CreateModel(
            name="ReasonDim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("code", models.CharField(max_length=40, unique=True)),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "原因码维",
                "verbose_name_plural": "原因码维",
            },
        ),
        migrations.CreateModel(
            name="TempZoneDim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=60)),
            ],
            options={
                "verbose_name": "温度带维",
                "verbose_name_plural": "温度带维",
            },
        ),
        migrations.CreateModel(
            name="CarrierDim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("valid_from", models.DateTimeField()),
                ("valid_to", models.DateTimeField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=True)),
                ("carrier_id", models.BigIntegerField()),
                ("code", models.CharField(max_length=40)),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "承运商维(SCD2)",
                "verbose_name_plural": "承运商维(SCD2)",
                "indexes": [models.Index(fields=["code"], name="idx_car_code")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("carrier_id", "valid_from"), name="uq_car_scd2"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CustomerDim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("valid_from", models.DateTimeField()),
                ("valid_to", models.DateTimeField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=True)),
                ("customer_id", models.BigIntegerField()),
                ("owner_id", models.BigIntegerField()),
                ("code", models.CharField(max_length=40)),
                ("name", models.CharField(max_length=200)),
                ("level", models.CharField(blank=True, max_length=40)),
            ],
            options={
                "verbose_name": "客户维(SCD2)",
                "verbose_name_plural": "客户维(SCD2)",
                "indexes": [
                    models.Index(
                        fields=["owner_id", "is_current"], name="idx_cust_cur"
                    ),
                    models.Index(fields=["code"], name="idx_cust_code"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("customer_id", "valid_from"), name="uq_cust_scd2"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DateDim",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("date_key", models.IntegerField(primary_key=True, serialize=False)),
                ("date", models.DateField(unique=True)),
                ("year", models.SmallIntegerField()),
                ("quarter", models.PositiveSmallIntegerField()),
                ("month", models.PositiveSmallIntegerField()),
                ("day", models.PositiveSmallIntegerField()),
                ("week", models.PositiveSmallIntegerField()),
                ("is_month_start", models.BooleanField()),
                ("is_month_end", models.BooleanField()),
                ("is_weekend", models.BooleanField()),
            ],
            options={
                "verbose_name": "日期维",
                "verbose_name_plural": "日期维",
                "indexes": [models.Index(fields=["year", "month"], name="idx_dt_ym")],
            },
        ),
        migrations.CreateModel(
            name="DedupLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(max_length=40)),
                ("dedup_key", models.CharField(max_length=120)),
                ("occurred_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "幂等去重点",
                "verbose_name_plural": "幂等去重点",
                "indexes": [
                    models.Index(
                        fields=["domain", "occurred_date"], name="idx_dedup_dom_date"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("domain", "dedup_key"), name="uq_dedup_key"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EtlJobRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_name", models.CharField(max_length=80)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("ok", models.BooleanField(default=False)),
                ("rows_in", models.IntegerField(default=0)),
                ("rows_out", models.IntegerField(default=0)),
                ("error", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "ETL运行日志",
                "verbose_name_plural": "ETL运行日志",
                "indexes": [
                    models.Index(
                        fields=["job_name", "started_at"], name="idx_job_name_time"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OwnerDim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("valid_from", models.DateTimeField()),
                ("valid_to", models.DateTimeField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=True)),
                ("owner_id", models.BigIntegerField()),
                ("code", models.CharField(max_length=40)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "货主维(SCD2)",
                "verbose_name_plural": "货主维(SCD2)",
                "indexes": [
                    models.Index(
                        fields=["owner_id", "is_current"], name="idx_owner_cur"
                    ),
                    models.Index(fields=["code"], name="idx_owner_code"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner_id", "valid_from"), name="uq_owner_scd2"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductDim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("valid_from", models.DateTimeField()),
                ("valid_to", models.DateTimeField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=True)),
                ("product_id", models.BigIntegerField()),
                ("owner_id", models.BigIntegerField()),
                ("sku_code", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=200)),
                ("category_code", models.CharField(blank=True, max_length=64)),
                ("uom", models.CharField(max_length=16)),
                (
                    "net_weight_kg",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "volume_m3",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("shelf_life_days", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "商品维(SCD2)",
                "verbose_name_plural": "商品维(SCD2)",
                "indexes": [
                    models.Index(
                        fields=["owner_id", "sku_code"], name="idx_prod_owner_sku"
                    ),
                    models.Index(fields=["is_current"], name="idx_prod_cur"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product_id", "valid_from"), name="uq_prod_scd2"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SupplierDim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("valid_from", models.DateTimeField()),
                ("valid_to", models.DateTimeField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=True)),
                ("supplier_id", models.BigIntegerField()),
                ("owner_id", models.BigIntegerField()),
                ("code", models.CharField(max_length=40)),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "供应商维(SCD2)",
                "verbose_name_plural": "供应商维(SCD2)",
                "indexes": [
                    models.Index(
                        fields=["owner_id", "is_current"], name="idx_supp_cur"
                    ),
                    models.Index(fields=["code"], name="idx_supp_code"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("supplier_id", "valid_from"), name="uq_supp_scd2"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WarehouseDim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("valid_from", models.DateTimeField()),
                ("valid_to", models.DateTimeField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=True)),
                ("warehouse_id", models.BigIntegerField()),
                ("owner_id", models.BigIntegerField()),
                ("code", models.CharField(max_length=40)),
                ("name", models.CharField(max_length=100)),
                ("city", models.CharField(blank=True, max_length=60)),
            ],
            options={
                "verbose_name": "仓库维(SCD2)",
                "verbose_name_plural": "仓库维(SCD2)",
                "indexes": [
                    models.Index(fields=["owner_id", "is_current"], name="idx_wh_cur"),
                    models.Index(fields=["code"], name="idx_wh_code"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("warehouse_id", "valid_from"), name="uq_wh_scd2"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AggOTIFDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orders", models.IntegerField(default=0)),
                ("orders_on_time", models.IntegerField(default=0)),
                ("orders_in_full", models.IntegerField(default=0)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reports.customerdim",
                    ),
                ),
                (
                    "date",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reports.datedim",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reports.ownerdim",
                    ),
                ),
            ],
            options={
                "verbose_name": "OTIF日汇总",
                "verbose_name_plural": "OTIF日汇总",
                "indexes": [
                    models.Index(fields=["owner", "date"], name="idx_otif_owner_date"),
                    models.Index(
                        fields=["customer", "date"], name="idx_otif_cust_date"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("date", "owner", "customer"), name="uq_otif_key"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("orders__gte", 0),
                            ("orders_on_time__gte", 0),
                            ("orders_in_full__gte", 0),
                        ),
                        name="chk_otif_ge0",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ReportSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("src_model", models.CharField(max_length=40, verbose_name="来源模型")),
                ("src_id", models.BigIntegerField(verbose_name="来源ID")),
                ("doc_type", models.CharField(max_length=30, verbose_name="单据类型")),
                (
                    "doc_no",
                    models.CharField(
                        blank=True, default="", max_length=40, verbose_name="单号(快照)"
                    ),
                ),
                (
                    "template",
                    models.CharField(
                        default="dispatch_note", max_length=40, verbose_name="模板键"
                    ),
                ),
                (
                    "tpl_ver",
                    models.CharField(
                        default="v1", max_length=10, verbose_name="模板版本"
                    ),
                ),
                ("payload", models.JSONField(verbose_name="渲染数据快照")),
                (
                    "html",
                    models.TextField(blank=True, default="", verbose_name="HTML快照"),
                ),
                (
                    "amount_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="金额合计",
                    ),
                ),
                (
                    "amount_upper",
                    models.CharField(
                        blank=True, default="", max_length=60, verbose_name="金额大写"
                    ),
                ),
                (
                    "fp",
                    models.CharField(max_length=64, unique=True, verbose_name="指纹"),
                ),
                (
                    "is_final",
                    models.BooleanField(default=False, verbose_name="是否定稿"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="baseinfo.owner",
                        verbose_name="货主",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="locations.warehouse",
                        verbose_name="出库",
                    ),
                ),
            ],
            options={
                "verbose_name": "报表快照",
                "verbose_name_plural": "报表快照",
                "indexes": [
                    models.Index(
                        fields=["doc_type", "doc_no"], name="ix_rpt_doctype_no"
                    ),
                    models.Index(
                        fields=["owner", "warehouse", "created_at"],
                        name="ix_rpt_own_wh_time",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount_total__gte", 0)),
                        name="ck_rpt_amt_nonneg",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FactOutboundLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_id", models.BigIntegerField(unique=True)),
                ("order_id", models.BigIntegerField()),
                (
                    "qty_plan",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "qty_alloc",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "qty_picked",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "qty_packed",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "qty_shipped",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("sec_alloc", models.IntegerField(blank=True, null=True)),
                ("sec_pick", models.IntegerField(blank=True, null=True)),
                ("sec_pack", models.IntegerField(blank=True, null=True)),
                ("sec_ship", models.IntegerField(blank=True, null=True)),
                ("in_full", models.BooleanField(default=False)),
                ("on_time", models.BooleanField(default=False)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reports.customerdim",
                    ),
                ),
                (
                    "order_date",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ob_order_dt",
                        to="reports.datedim",
                    ),
                ),
                (
                    "ship_date",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ob_ship_dt",
                        to="reports.datedim",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reports.ownerdim",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reports.productdim",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reports.warehousedim",
                    ),
                ),
            ],
            options={
                "verbose_name": "出库行事实",
                "verbose_name_plural": "出库行事实",
                "indexes": [
                    models.Index(
                        fields=["owner", "order_date"], name="idx_ob_owner_date"
                    ),
                    models.Index(
                        fields=["warehouse", "ship_date"], name="idx_ob_wh_ship"
                    ),
                    models.Index(
                        fields=["product", "order_date"], name="idx_ob_prod_date"
                    ),
                    models.Index(
                        fields=["customer", "ship_date"], name="idx_ob_cust_ship"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FactInventoryTxn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("txn_id", models.BigIntegerField(unique=True)),
                ("occurred_at", models.DateTimeField(db_index=True)),
                ("location_id", models.BigIntegerField(blank=True, null=True)),
                ("lot_no", models.CharField(blank=True, max_length=60)),
                ("order_type", models.CharField(max_length=20)),
                ("order_id", models.BigIntegerField(blank=True, null=True)),
                ("qty_delta", models.DecimalField(decimal_places=3, max_digits=18)),
                ("amount_delta", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reports.ownerdim",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reports.productdim",
                    ),
                ),
                (
                    "reason",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reports.reasondim",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reports.warehousedim",
                    ),
                ),
            ],
            options={
                "verbose_name": "库存交易事实",
                "verbose_name_plural": "库存交易事实",
                "indexes": [
                    models.Index(
                        fields=["owner", "occurred_at"], name="idx_txn_owner_time"
                    ),
                    models.Index(
                        fields=["warehouse", "occurred_at"], name="idx_txn_wh_time"
                    ),
                    models.Index(
                        fields=["product", "occurred_at"], name="idx_txn_prod_time"
                    ),
                    models.Index(
                        fields=["order_type", "occurred_at"], name="idx_txn_otype_time"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("qty_delta", 0), ("amount_delta", 0), _negated=True
                        ),
                        name="chk_txn_nonzero",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FactInventorySnapshotDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location_id", models.BigIntegerField()),
                ("lot_no", models.CharField(blank=True, max_length=60)),
                (
                    "qty_onhand",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "qty_alloc",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "qty_available",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "qty_damage",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "qty_expired",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "amount_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "snapshot_date",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reports.datedim",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reports.ownerdim",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reports.productdim",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reports.warehousedim",
                    ),
                ),
            ],
            options={
                "verbose_name": "库存日快照",
                "verbose_name_plural": "库存日快照",
                "indexes": [
                    models.Index(
                        fields=["owner", "snapshot_date"], name="idx_inv_owner_date"
                    ),
                    models.Index(
                        fields=["warehouse", "snapshot_date"], name="idx_inv_wh_date"
                    ),
                    models.Index(
                        fields=["product", "snapshot_date"], name="idx_inv_prod_date"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "snapshot_date",
                            "owner",
                            "warehouse",
                            "location_id",
                            "product",
                            "lot_no",
                        ),
                        name="uq_inv_snap_key",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("qty_onhand__gte", 0),
                            ("qty_alloc__gte", 0),
                            ("qty_available__gte", 0),
                            ("qty_damage__gte", 0),
                            ("qty_expired__gte", 0),
                            ("amount_value__gte", 0),
                        ),
                        name="chk_inv_snap_nn",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FactInboundLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_id", models.BigIntegerField(unique=True)),
                ("order_id", models.BigIntegerField()),
                (
                    "qty_plan",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "qty_received",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "qty_reject",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "qty_damage",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("sec_to_receive", models.IntegerField(blank=True, null=True)),
                ("sec_to_putaway", models.IntegerField(blank=True, null=True)),
                (
                    "order_date",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ib_order_dt",
                        to="reports.datedim",
                    ),
                ),
                (
                    "putaway_date",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ib_put_dt",
                        to="reports.datedim",
                    ),
                ),
                (
                    "receive_date",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ib_recv_dt",
                        to="reports.datedim",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reports.ownerdim",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reports.productdim",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reports.supplierdim",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reports.warehousedim",
                    ),
                ),
            ],
            options={
                "verbose_name": "入库行事实",
                "verbose_name_plural": "入库行事实",
                "indexes": [
                    models.Index(
                        fields=["owner", "order_date"], name="idx_ib_owner_date"
                    ),
                    models.Index(
                        fields=["warehouse", "receive_date"], name="idx_ib_wh_recv"
                    ),
                    models.Index(
                        fields=["product", "order_date"], name="idx_ib_prod_date"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FactBilling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fee_type", models.CharField(max_length=30)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("dedup_key", models.CharField(blank=True, max_length=80)),
                (
                    "date",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reports.datedim",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reports.ownerdim",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reports.warehousedim",
                    ),
                ),
            ],
            options={
                "verbose_name": "计费事实",
                "verbose_name_plural": "计费事实",
                "indexes": [
                    models.Index(fields=["owner", "date"], name="idx_fee_owner_date"),
                    models.Index(fields=["fee_type", "date"], name="idx_fee_type_date"),
                    models.Index(fields=["dedup_key"], name="idx_fee_dedup"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gte", 0)), name="chk_fee_amt_ge0"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AggThroughputDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inbound_lines", models.IntegerField(default=0)),
                (
                    "inbound_qty",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("outbound_lines", models.IntegerField(default=0)),
                (
                    "outbound_qty",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "date",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reports.datedim",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reports.ownerdim",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reports.warehousedim",
                    ),
                ),
            ],
            options={
                "verbose_name": "吞吐日汇总",
                "verbose_name_plural": "吞吐日汇总",
                "indexes": [
                    models.Index(fields=["owner", "date"], name="idx_tput_owner_date"),
                    models.Index(fields=["warehouse", "date"], name="idx_tput_wh_date"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("date", "owner", "warehouse"), name="uq_tput_key"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("inbound_lines__gte", 0), ("outbound_lines__gte", 0)
                        ),
                        name="chk_tput_cnt_ge0",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AggInventoryAging",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("band", models.CharField(max_length=20)),
                (
                    "qty",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "date",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reports.datedim",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reports.ownerdim",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reports.productdim",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reports.warehousedim",
                    ),
                ),
            ],
            options={
                "verbose_name": "库龄汇总",
                "verbose_name_plural": "库龄汇总",
                "indexes": [
                    models.Index(fields=["owner", "date"], name="idx_age_owner_date"),
                    models.Index(fields=["warehouse", "date"], name="idx_age_wh_date"),
                    models.Index(fields=["product", "date"], name="idx_age_prod_date"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("date", "owner", "warehouse", "product", "band"),
                        name="uq_age_key",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AggBillingDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fee_type", models.CharField(max_length=30)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "date",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reports.datedim",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reports.ownerdim",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reports.warehousedim",
                    ),
                ),
            ],
            options={
                "verbose_name": "计费日汇总",
                "verbose_name_plural": "计费日汇总",
                "indexes": [
                    models.Index(fields=["owner", "date"], name="idx_bill_owner_date"),
                    models.Index(
                        fields=["fee_type", "date"], name="idx_bill_type_date"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("date", "owner", "warehouse", "fee_type"),
                        name="uq_bill_key",
                    )
                ],
            },
        ),
    ]
