# Generated by Django 5.2.5 on 2025-10-19 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0006_remove_location_locations_l_zone_ty_be2147_idx_and_more"),
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportsnapshot",
            name="warehouse",
            field=models.ForeignKey(
                default=1,
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                to="locations.warehouse",
                verbose_name="出库",
            ),
        ),
    ]
