# Generated by Django 5.2.5 on 2026-08-05 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseinfo", "0005_ownerwarehousebinding"),
        ("locations", "0004_alter_location_zone_type"),
        ("reports", "0005_factbilling_dedup_constraint"),
        ("tasking", "0008_reloclineextra_from_container_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dedup_key", models.CharField(max_length=160, unique=True)),
                ("alert_type", models.CharField(db_index=True, max_length=60)),
                ("source_type", models.CharField(max_length=60)),
                ("source_id", models.CharField(max_length=80)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "提示"),
                            ("WARNING", "警告"),
                            ("HIGH", "高风险"),
                            ("CRITICAL", "严重"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("first_seen_at", models.DateTimeField()),
                ("last_seen_at", models.DateTimeField()),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "待处理"),
                            ("ACKNOWLEDGED", "已确认"),
                            ("IN_PROGRESS", "处理中"),
                            ("RESOLVED", "已恢复"),
                            ("CLOSED", "已关闭"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_alert_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="baseinfo.owner",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="locations.warehouse",
                    ),
                ),
            ],
            options={
                "permissions": [("manage_alert_cases", "处置经营预警")],
            },
        ),
        migrations.CreateModel(
            name="AlertCaseHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=40)),
                (
                    "from_status",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("to_status", models.CharField(blank=True, default="", max_length=20)),
                ("note", models.TextField(blank=True, default="")),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="history",
                        to="reports.alertcase",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="BusinessReviewSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("share_code", models.CharField(max_length=64, unique=True)),
                ("warehouse_ids", models.JSONField(default=list)),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                ("data_as_of", models.DateTimeField()),
                ("response_version", models.CharField(default="v1", max_length=20)),
                ("payload", models.JSONField()),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("checksum", models.CharField(max_length=64)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="business_review_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="baseinfo.owner",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revoked_business_review_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OperatingTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField()),
                (
                    "metric",
                    models.CharField(
                        choices=[
                            ("ACCRUAL_REVENUE", "应计收入"),
                            ("VOLUME_UTILIZATION", "体积利用率"),
                            ("OTIF", "OTIF"),
                            ("COLLECTION_RATE", "回款率"),
                        ],
                        max_length=40,
                    ),
                ),
                ("currency", models.CharField(blank=True, default="", max_length=8)),
                (
                    "owner_scope_id",
                    models.PositiveBigIntegerField(default=0, editable=False),
                ),
                ("target_value", models.DecimalField(decimal_places=4, max_digits=18)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="baseinfo.owner",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="locations.warehouse",
                    ),
                ),
            ],
            options={
                "permissions": [("manage_operating_targets", "维护经营目标")],
            },
        ),
        migrations.CreateModel(
            name="TaskStateSnapshotDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot_date", models.DateField()),
                ("status", models.CharField(max_length=30)),
                ("age_minutes", models.PositiveIntegerField(default=0)),
                ("captured_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="baseinfo.owner"
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tasking.wmstask",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="locations.warehouse",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="alertcase",
            index=models.Index(
                fields=["warehouse", "status", "severity"], name="ix_alert_scope_state"
            ),
        ),
        migrations.AddIndex(
            model_name="alertcase",
            index=models.Index(
                fields=["alert_type", "last_seen_at"], name="ix_alert_type_seen"
            ),
        ),
        migrations.AddIndex(
            model_name="businessreviewsnapshot",
            index=models.Index(
                fields=["created_by", "created_at"], name="ix_review_creator_time"
            ),
        ),
        migrations.AddConstraint(
            model_name="operatingtarget",
            constraint=models.UniqueConstraint(
                fields=("month", "warehouse", "owner_scope_id", "metric", "currency"),
                name="ux_operating_target_scope",
            ),
        ),
        migrations.AddConstraint(
            model_name="operatingtarget",
            constraint=models.CheckConstraint(
                condition=models.Q(("target_value__gte", 0)),
                name="chk_operating_target_nonneg",
            ),
        ),
        migrations.AddIndex(
            model_name="taskstatesnapshotdaily",
            index=models.Index(
                fields=["warehouse", "snapshot_date", "status"],
                name="ix_task_snap_scope",
            ),
        ),
        migrations.AddConstraint(
            model_name="taskstatesnapshotdaily",
            constraint=models.UniqueConstraint(
                fields=("snapshot_date", "task"), name="ux_task_state_day"
            ),
        ),
    ]
