# Generated by Django 5.2.5 on 2026-08-05 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alertcase_alertcasehistory_businessreviewsnapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactOutboundOrderSLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.BigIntegerField(unique=True)),
                ('etd', models.DateTimeField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('planned_qty', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('shipped_qty', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('sla_eligible', models.BooleanField(default=False)),
                ('on_time', models.BooleanField(default=False)),
                ('in_full', models.BooleanField(default=False)),
                ('otif', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reports.customerdim')),
                ('order_date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.datedim')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.ownerdim')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.warehousedim')),
            ],
            options={
                'indexes': [models.Index(fields=['owner', 'order_date', 'sla_eligible'], name='ix_order_sla_owner'), models.Index(fields=['warehouse', 'order_date', 'sla_eligible'], name='ix_order_sla_wh')],
            },
        ),
    ]
