# Generated by Django 5.2.5 on 2026-04-24 20:40

import allapp.billing.models
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("baseinfo", "0002_initial"),
        ("inventory", "0001_initial"),
        ("locations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingJobRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_name",
                    models.CharField(
                        choices=[("DAILY_METRIC_GENERATION", "日指标生成")],
                        max_length=40,
                        verbose_name="作业名",
                    ),
                ),
                ("service_date", models.DateField(verbose_name="服务日期")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "运行中"),
                            ("SUCCESS", "成功"),
                            ("FAILED", "失败"),
                            ("SKIPPED", "跳过"),
                        ],
                        default="RUNNING",
                        max_length=20,
                        verbose_name="执行状态",
                    ),
                ),
                (
                    "attempts",
                    models.PositiveIntegerField(default=1, verbose_name="尝试次数"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="执行消息"
                    ),
                ),
                (
                    "summary",
                    models.JSONField(blank=True, default=dict, verbose_name="执行摘要"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "计费作业执行记录",
                "verbose_name_plural": "计费作业执行记录",
            },
        ),
        migrations.CreateModel(
            name="BillingMetricDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_date", models.DateField(verbose_name="日期")),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("AREA_M2", "面积(㎡)"),
                            ("CBM", "体积(CBM)"),
                            ("PALLET", "托盘位(个)"),
                            ("ORDER_AMT", "订单金额"),
                        ],
                        max_length=20,
                        verbose_name="指标类型",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=4, max_digits=18, verbose_name="指标值"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, default="", max_length=40, verbose_name="来源"
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="备注"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "计费日指标",
                "verbose_name_plural": "计费日指标",
            },
        ),
        migrations.CreateModel(
            name="BillingPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=20, verbose_name="账期标签")),
                ("start_date", models.DateField(verbose_name="开始日期")),
                ("end_date", models.DateField(verbose_name="结束日期")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "开账"),
                            ("CLOSED", "关账"),
                            ("INVOICED", "已开票"),
                        ],
                        default="OPEN",
                        max_length=20,
                        verbose_name="账期状态",
                    ),
                ),
                (
                    "currency",
                    models.CharField(default="CNY", max_length=8, verbose_name="币种"),
                ),
            ],
            options={
                "verbose_name": "账期",
                "verbose_name_plural": "账期",
            },
        ),
        migrations.CreateModel(
            name="BillingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "charge_type",
                    models.CharField(
                        choices=[
                            ("RECEIVE", "收货"),
                            ("PUTAWAY", "上架/移库入"),
                            ("RELOC", "移库"),
                            ("PICK", "拣货"),
                            ("REVIEW", "复核"),
                            ("PACK", "打包"),
                            ("LOAD", "装车"),
                            ("DISPATCH", "发运/订单处理"),
                            ("COUNT", "盘点"),
                            ("ADJUST", "调整"),
                            ("STORAGE", "仓储/保管"),
                        ],
                        max_length=20,
                        verbose_name="计费类型",
                    ),
                ),
                (
                    "calc_method",
                    models.CharField(
                        choices=[
                            ("PER_TASK", "按任务"),
                            ("PER_LINE", "按任务行"),
                            ("PER_QTY_BASE", "按基础数量"),
                            ("PER_QTY_ABSDEL", "按数量差额绝对值"),
                            ("PER_ORDER", "按订单"),
                            ("PER_ORDER_LINE", "按订单行"),
                            ("PER_PARCEL", "按包裹件数"),
                            ("PER_DAY_ONHAND_BASE", "按日在库(基础数)"),
                            ("PER_PALLET_DAY", "按托盘位/天"),
                            ("PER_CBM_DAY", "按体积CBM/天"),
                            ("PER_AREA_MONTH", "按面积㎡/月"),
                            ("PERCENT_OF_ORDER_AMOUNT", "按订单金额比例"),
                        ],
                        max_length=40,
                        verbose_name="计量方式",
                    ),
                ),
                (
                    "ladder_mode",
                    models.CharField(
                        blank=True,
                        choices=[("WHOLE", "整档全量价"), ("INCREMENTAL", "分段累进")],
                        default=None,
                        max_length=16,
                        null=True,
                        verbose_name="阶梯模式",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=18,
                        null=True,
                        verbose_name="单价/费率（无阶梯时生效）",
                    ),
                ),
                (
                    "currency",
                    models.CharField(default="CNY", max_length=8, verbose_name="币种"),
                ),
                ("taxable", models.BooleanField(default=False, verbose_name="含税")),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=6,
                        verbose_name="税率",
                    ),
                ),
                (
                    "min_charge",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=18,
                        verbose_name="最低收费",
                    ),
                ),
                (
                    "cap_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NONE", "不封顶"),
                            ("PER_DAY", "按天封顶"),
                            ("PER_PERIOD", "按账期封顶"),
                        ],
                        default="NONE",
                        max_length=16,
                        null=True,
                        verbose_name="封顶口径",
                    ),
                ),
                (
                    "cap_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="封顶金额",
                    ),
                ),
                (
                    "bundle_key",
                    models.CharField(
                        blank=True, default="", max_length=40, verbose_name="打包分组键"
                    ),
                ),
                (
                    "bundle_scope",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NONE", "不打包"),
                            ("PER_DAY", "按天打包"),
                            ("PER_PERIOD", "按账期打包"),
                        ],
                        default="NONE",
                        max_length=16,
                        null=True,
                        verbose_name="打包口径",
                    ),
                ),
                (
                    "bundle_type",
                    models.CharField(
                        blank=True,
                        choices=[("CAP", "打包上限"), ("FIXED", "固定打包价")],
                        default="CAP",
                        max_length=8,
                        null=True,
                        verbose_name="打包类型",
                    ),
                ),
                (
                    "bundle_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="打包价",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "priority",
                    models.IntegerField(default=100, verbose_name="优先级（小数优先）"),
                ),
                (
                    "effective_from",
                    models.DateField(blank=True, null=True, verbose_name="生效开始日"),
                ),
                (
                    "effective_to",
                    models.DateField(blank=True, null=True, verbose_name="生效截止日"),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="备注"
                    ),
                ),
            ],
            options={
                "verbose_name": "计费规则",
                "verbose_name_plural": "计费规则",
            },
        ),
        migrations.CreateModel(
            name="BillingRuleTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "threshold_from",
                    models.DecimalField(
                        decimal_places=4, max_digits=18, verbose_name="起始阈值(含)"
                    ),
                ),
                (
                    "threshold_to",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=18,
                        null=True,
                        verbose_name="截至阈值(不含)",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=18,
                        null=True,
                        verbose_name="单价(按量)",
                    ),
                ),
                (
                    "percent_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=18,
                        null=True,
                        verbose_name="费率(按金额)",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="备注"
                    ),
                ),
            ],
            options={
                "verbose_name": "阶梯规则",
                "verbose_name_plural": "阶梯规则",
            },
        ),
        migrations.CreateModel(
            name="BillLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "charge_type",
                    models.CharField(
                        choices=[
                            ("RECEIVE", "收货"),
                            ("PUTAWAY", "上架/移库入"),
                            ("RELOC", "移库"),
                            ("PICK", "拣货"),
                            ("REVIEW", "复核"),
                            ("PACK", "打包"),
                            ("LOAD", "装车"),
                            ("DISPATCH", "发运/订单处理"),
                            ("COUNT", "盘点"),
                            ("ADJUST", "调整"),
                            ("STORAGE", "仓储/保管"),
                        ],
                        max_length=20,
                        verbose_name="计费类型",
                    ),
                ),
                ("service_date", models.DateField(verbose_name="服务日期")),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4, max_digits=18, verbose_name="计费数量"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=4, max_digits=18, verbose_name="有效单价/费率"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=18, verbose_name="金额(不含税)"
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=18,
                        verbose_name="税额",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="行说明"
                    ),
                ),
            ],
            options={
                "verbose_name": "发票/结算单明细",
                "verbose_name_plural": "发票/结算单明细",
            },
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_no",
                    models.CharField(
                        max_length=40, unique=True, verbose_name="发票/结算单号"
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(
                        default=allapp.billing.models.bill_issue_date_default,
                        verbose_name="开票日期",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="到期日期"),
                ),
                (
                    "currency",
                    models.CharField(default="CNY", max_length=8, verbose_name="币种"),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=18,
                        verbose_name="小计(不含税)",
                    ),
                ),
                (
                    "tax_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=18,
                        verbose_name="税额合计",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=18,
                        verbose_name="价税合计",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "草稿"),
                            ("ISSUED", "已开票"),
                            ("PAID", "已收款"),
                            ("VOID", "作废"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="单据状态",
                    ),
                ),
                (
                    "memo",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="备注"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="baseinfo.owner",
                        verbose_name="货主",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="locations.warehouse",
                        verbose_name="大仓",
                    ),
                ),
            ],
            options={
                "verbose_name": "发票/结算单",
                "verbose_name_plural": "发票/结算单",
            },
        ),
        migrations.CreateModel(
            name="BillingAccrual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "charge_type",
                    models.CharField(
                        choices=[
                            ("RECEIVE", "收货"),
                            ("PUTAWAY", "上架/移库入"),
                            ("RELOC", "移库"),
                            ("PICK", "拣货"),
                            ("REVIEW", "复核"),
                            ("PACK", "打包"),
                            ("LOAD", "装车"),
                            ("DISPATCH", "发运/订单处理"),
                            ("COUNT", "盘点"),
                            ("ADJUST", "调整"),
                            ("STORAGE", "仓储/保管"),
                        ],
                        max_length=20,
                        verbose_name="计费类型",
                    ),
                ),
                ("service_date", models.DateField(verbose_name="服务日期")),
                (
                    "currency",
                    models.CharField(default="CNY", max_length=8, verbose_name="币种"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4, max_digits=18, verbose_name="计费数量"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=4, max_digits=18, verbose_name="有效单价/费率"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=18, verbose_name="金额(不含税)"
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=18,
                        verbose_name="税额",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "未锁定"),
                            ("LOCKED", "已锁定"),
                            ("INVOICED", "已开票"),
                            ("VOID", "作废"),
                        ],
                        default="OPEN",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "bundle_key",
                    models.CharField(
                        blank=True, default="", max_length=40, verbose_name="打包分组键"
                    ),
                ),
                (
                    "acc_fingerprint",
                    models.CharField(
                        max_length=160, unique=True, verbose_name="应计指纹"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "pre_adjustment_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="调整前金额",
                    ),
                ),
                (
                    "is_reversal",
                    models.BooleanField(default=False, verbose_name="是否冲销"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="billing_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="baseinfo.owner",
                        verbose_name="货主",
                    ),
                ),
                (
                    "reversal_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversals",
                        to="billing.billingaccrual",
                        verbose_name="冲销来源",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="locations.warehouse",
                        verbose_name="大仓",
                    ),
                ),
            ],
            options={
                "verbose_name": "应计费用",
                "verbose_name_plural": "应计费用",
            },
        ),
        migrations.CreateModel(
            name="BillingEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "charge_type",
                    models.CharField(
                        choices=[
                            ("RECEIVE", "收货"),
                            ("PUTAWAY", "上架/移库入"),
                            ("RELOC", "移库"),
                            ("PICK", "拣货"),
                            ("REVIEW", "复核"),
                            ("PACK", "打包"),
                            ("LOAD", "装车"),
                            ("DISPATCH", "发运/订单处理"),
                            ("COUNT", "盘点"),
                            ("ADJUST", "调整"),
                            ("STORAGE", "仓储/保管"),
                        ],
                        max_length=20,
                        verbose_name="计费类型",
                    ),
                ),
                ("service_date", models.DateField(verbose_name="服务日期")),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        max_digits=18,
                        verbose_name="计费数量",
                    ),
                ),
                (
                    "quantity_uom",
                    models.CharField(
                        default="BASE", max_length=20, verbose_name="数量单位"
                    ),
                ),
                (
                    "event_fp",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="事件指纹"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="baseinfo.owner",
                        verbose_name="货主",
                    ),
                ),
                (
                    "posting_journal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.postingjournal",
                        verbose_name="过账日志",
                    ),
                ),
            ],
            options={
                "verbose_name": "计费事件",
                "verbose_name_plural": "计费事件",
            },
        ),
    ]
