# Generated by Django 5.2.5 on 2025-10-18 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("baseinfo", "0002_initial"),
        ("billing", "0001_initial"),
        ("locations", "0001_initial"),
        ("tasking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingevent",
            name="scan_log",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tasking.taskscanlog",
                verbose_name="来源扫描记录",
            ),
        ),
        migrations.AddField(
            model_name="billingevent",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tasking.wmstask",
                verbose_name="来源任务",
            ),
        ),
        migrations.AddField(
            model_name="billingevent",
            name="task_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tasking.wmstaskline",
                verbose_name="来源任务行",
            ),
        ),
        migrations.AddField(
            model_name="billingevent",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="locations.warehouse",
                verbose_name="仓库",
            ),
        ),
        migrations.AddField(
            model_name="billingaccrual",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="billing.billingevent",
                verbose_name="来源事件",
            ),
        ),
        migrations.AddField(
            model_name="billingmetricdaily",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="baseinfo.owner",
                verbose_name="货主",
            ),
        ),
        migrations.AddField(
            model_name="billingmetricdaily",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="locations.warehouse",
                verbose_name="仓库",
            ),
        ),
        migrations.AddField(
            model_name="billingperiod",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="baseinfo.owner",
                verbose_name="货主",
            ),
        ),
        migrations.AddField(
            model_name="billingperiod",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="locations.warehouse",
                verbose_name="仓库",
            ),
        ),
        migrations.AddField(
            model_name="billingaccrual",
            name="period",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="billing.billingperiod",
                verbose_name="账期",
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="billing.billingperiod",
                verbose_name="账期",
            ),
        ),
        migrations.AddField(
            model_name="billingrule",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="baseinfo.owner",
                verbose_name="货主",
            ),
        ),
        migrations.AddField(
            model_name="billingrule",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="locations.warehouse",
                verbose_name="仓库",
            ),
        ),
        migrations.AddField(
            model_name="billingaccrual",
            name="rule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="billing.billingrule",
                verbose_name="计费规则",
            ),
        ),
        migrations.AddField(
            model_name="billingruletier",
            name="rule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tiers",
                to="billing.billingrule",
                verbose_name="计费规则",
            ),
        ),
        migrations.AddField(
            model_name="billline",
            name="accrual",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="billing.billingaccrual",
                verbose_name="来源应计",
            ),
        ),
        migrations.AddField(
            model_name="billline",
            name="bill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="billing.bill",
                verbose_name="所属发票/结算单",
            ),
        ),
        migrations.AddIndex(
            model_name="billingmetricdaily",
            index=models.Index(
                fields=["owner", "warehouse", "service_date", "metric_type"],
                name="billing_bil_owner_i_1804f8_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="billingmetricdaily",
            constraint=models.UniqueConstraint(
                fields=("owner", "warehouse", "service_date", "metric_type"),
                name="ux_billing_metric_daily_owh_date_metric",
            ),
        ),
        migrations.AddConstraint(
            model_name="billingperiod",
            constraint=models.UniqueConstraint(
                fields=("owner", "warehouse", "label"),
                name="ux_billing_period_owner_wh_label",
            ),
        ),
        migrations.AddIndex(
            model_name="billingrule",
            index=models.Index(
                fields=["owner", "warehouse", "charge_type", "active", "priority"],
                name="billing_bil_owner_i_a8669d_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="billingrule",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_price__gte", 0)), name="chk_rule_price_nonneg"
            ),
        ),
        migrations.AddConstraint(
            model_name="billingrule",
            constraint=models.CheckConstraint(
                condition=models.Q(("tax_rate__gte", 0), ("tax_rate__lte", 1)),
                name="chk_rule_taxrate_range",
            ),
        ),
        migrations.AddIndex(
            model_name="billingaccrual",
            index=models.Index(
                fields=["owner", "warehouse", "service_date", "charge_type", "status"],
                name="billing_bil_owner_i_45fd85_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="billingaccrual",
            index=models.Index(
                fields=["bundle_key", "service_date"],
                name="billing_bil_bundle__b68262_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="billingaccrual",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)), name="chk_amount_nonneg"
            ),
        ),
        migrations.AddConstraint(
            model_name="billingaccrual",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 0)), name="chk_qty_nonneg"
            ),
        ),
        migrations.AddIndex(
            model_name="billingruletier",
            index=models.Index(
                fields=["rule", "threshold_from", "threshold_to"],
                name="billing_bil_rule_id_ca2573_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="billingruletier",
            constraint=models.UniqueConstraint(
                fields=("rule", "threshold_from", "threshold_to"),
                name="ux_rule_tier_from_to",
            ),
        ),
        migrations.AddConstraint(
            model_name="billingruletier",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("threshold_to__isnull", True),
                    ("threshold_to__gt", models.F("threshold_from")),
                    _connector="OR",
                ),
                name="chk_tier_range_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="billingruletier",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("percent_rate__isnull", True), ("unit_price__isnull", False)
                    ),
                    models.Q(
                        ("percent_rate__isnull", False), ("unit_price__isnull", True)
                    ),
                    _connector="OR",
                ),
                name="chk_tier_price_or_rate",
            ),
        ),
    ]
