# Generated by Django 5.2.5 on 2026-03-29 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseinfo", "0002_initial"),
        ("billing", "0002_initial"),
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingJobRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_name",
                    models.CharField(
                        choices=[("DAILY_METRIC_GENERATION", "日指标生成")],
                        max_length=40,
                        verbose_name="作业名",
                    ),
                ),
                ("service_date", models.DateField(verbose_name="服务日期")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "运行中"),
                            ("SUCCESS", "成功"),
                            ("FAILED", "失败"),
                            ("SKIPPED", "跳过"),
                        ],
                        default="RUNNING",
                        max_length=20,
                        verbose_name="执行状态",
                    ),
                ),
                (
                    "attempts",
                    models.PositiveIntegerField(default=1, verbose_name="尝试次数"),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="结束时间"),
                ),
                (
                    "message",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="执行消息"
                    ),
                ),
                (
                    "summary",
                    models.JSONField(blank=True, default=dict, verbose_name="执行摘要"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="baseinfo.owner",
                        verbose_name="货主",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        default=1,
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="locations.warehouse",
                        verbose_name="大仓",
                    ),
                ),
            ],
            options={
                "verbose_name": "计费作业执行记录",
                "verbose_name_plural": "计费作业执行记录",
                "indexes": [
                    models.Index(
                        fields=["job_name", "status", "service_date"],
                        name="billing_bil_job_nam_e258f9_idx",
                    ),
                    models.Index(
                        fields=["owner", "warehouse", "service_date"],
                        name="billing_bil_owner_i_a81e04_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("job_name", "owner", "warehouse", "service_date"),
                        name="ux_billing_job_run_job_owh_date",
                    )
                ],
            },
        ),
    ]
