# Generated by Django 5.2.5 on 2025-10-19 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baseinfo", "0004_remove_carriercompany_idx_carrier_wh_center_and_more"),
        ("billing", "0002_initial"),
        ("locations", "0002_remove_location_zone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="billingaccrual",
            name="billing_bil_owner_i_45fd85_idx",
        ),
        migrations.RemoveIndex(
            model_name="billingrule",
            name="billing_bil_owner_i_a8669d_idx",
        ),
        migrations.AlterField(
            model_name="bill",
            name="warehouse",
            field=models.ForeignKey(
                default=1,
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                to="locations.warehouse",
                verbose_name="大仓",
            ),
        ),
        migrations.AlterField(
            model_name="billingaccrual",
            name="warehouse",
            field=models.ForeignKey(
                default=1,
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                to="locations.warehouse",
                verbose_name="大仓",
            ),
        ),
        migrations.AlterField(
            model_name="billingevent",
            name="warehouse",
            field=models.ForeignKey(
                default=1,
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                to="locations.warehouse",
                verbose_name="大仓",
            ),
        ),
        migrations.AlterField(
            model_name="billingmetricdaily",
            name="warehouse",
            field=models.ForeignKey(
                default=1,
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                to="locations.warehouse",
                verbose_name="大仓",
            ),
        ),
        migrations.AlterField(
            model_name="billingperiod",
            name="warehouse",
            field=models.ForeignKey(
                default=1,
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                to="locations.warehouse",
                verbose_name="大仓",
            ),
        ),
        migrations.AlterField(
            model_name="billingrule",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                default=1,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="locations.warehouse",
                verbose_name="大仓",
            ),
        ),
        migrations.AddIndex(
            model_name="billingaccrual",
            index=models.Index(
                fields=["owner", "service_date", "charge_type", "status"],
                name="billing_bil_owner_i_85d9fa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="billingrule",
            index=models.Index(
                fields=["owner", "charge_type", "active", "priority"],
                name="billing_bil_owner_i_ce8d6b_idx",
            ),
        ),
    ]
