# Generated by Django 5.2.5 on 2026-03-29 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_billing_job_run"),
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="locations.warehouse",
                verbose_name="大仓",
            ),
        ),
        migrations.AlterField(
            model_name="billingaccrual",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="locations.warehouse",
                verbose_name="大仓",
            ),
        ),
        migrations.AlterField(
            model_name="billingevent",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="locations.warehouse",
                verbose_name="大仓",
            ),
        ),
        migrations.AlterField(
            model_name="billingjobrun",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="locations.warehouse",
                verbose_name="大仓",
            ),
        ),
        migrations.AlterField(
            model_name="billingmetricdaily",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="locations.warehouse",
                verbose_name="大仓",
            ),
        ),
        migrations.AlterField(
            model_name="billingperiod",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="locations.warehouse",
                verbose_name="大仓",
            ),
        ),
        migrations.AlterField(
            model_name="billingrule",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="locations.warehouse",
                verbose_name="大仓",
            ),
        ),
    ]
