# Generated by Django 5.2.5 on 2026-03-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_explicit_warehouse_scope"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="bill",
            constraint=models.UniqueConstraint(
                fields=("owner", "warehouse", "period"),
                name="ux_bill_owner_wh_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="billingperiod",
            constraint=models.CheckConstraint(
                condition=models.Q(end_date__gte=models.F("start_date")),
                name="chk_billing_period_date_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="billline",
            constraint=models.UniqueConstraint(fields=("accrual",), name="ux_billline_accrual_once"),
        ),
    ]
