# Generated by Django 5.2.5 on 2026-03-29 13:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0003_alter_carriercompany_warehouse_and_more'),
        ('billing', '0005_bill_ux_bill_owner_wh_period_and_more'),
        ('inventory', '0003_alter_inventorydetail_warehouse_and_more'),
        ('locations', '0002_alter_container_warehouse_alter_location_warehouse_and_more'),
        ('tasking', '0002_alter_taskscanlog_warehouse_alter_wmstask_warehouse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='billingrule',
            name='billing_bil_owner_i_ce8d6b_idx',
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['owner', 'warehouse', 'status'], name='ix_bill_owh_stat'),
        ),
        migrations.AddIndex(
            model_name='billingevent',
            index=models.Index(fields=['owner', 'warehouse', 'service_date', 'charge_type'], name='ix_bevt_scope_dt'),
        ),
        migrations.AddIndex(
            model_name='billingrule',
            index=models.Index(fields=['active', 'charge_type', 'calc_method', 'owner', 'warehouse', 'priority'], name='ix_rule_select'),
        ),
        migrations.AddConstraint(
            model_name='billingaccrual',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='chk_unit_price_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='billingaccrual',
            constraint=models.CheckConstraint(condition=models.Q(('tax_amount__gte', 0)), name='chk_tax_amount_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='billingmetricdaily',
            constraint=models.CheckConstraint(condition=models.Q(('value__gte', 0)), name='chk_metric_value_nonneg'),
        ),
    ]
