# Generated by Django 5.2.5 on 2026-08-05 20:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0005_ownerwarehousebinding'),
        ('billing', '0005_billing_integrity_enforcement'),
        ('locations', '0004_alter_location_zone_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='document_status',
            field=models.CharField(choices=[('DRAFT', '草稿'), ('ISSUED', '已开票'), ('VOID', '作废')], db_index=True, default='DRAFT', max_length=20, verbose_name='单据状态(新)'),
        ),
        migrations.AddField(
            model_name='bill',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', '未收款'), ('PARTIAL', '部分收款'), ('PAID', '已收清')], db_index=True, default='UNPAID', max_length=20, verbose_name='回款状态'),
        ),
        migrations.AddField(
            model_name='billingperiod',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='关账时间'),
        ),
        migrations.AddField(
            model_name='billingperiod',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_periods_closed', to=settings.AUTH_USER_MODEL, verbose_name='关账人'),
        ),
        migrations.AddField(
            model_name='billingperiod',
            name='invoiced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开票时间'),
        ),
        migrations.AddField(
            model_name='billingperiod',
            name='invoiced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_periods_invoiced', to=settings.AUTH_USER_MODEL, verbose_name='开票人'),
        ),
        migrations.AddField(
            model_name='billingperiod',
            name='transition_quality',
            field=models.CharField(default='VERIFIED', max_length=40, verbose_name='状态时间质量'),
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=8)),
                ('receipt_no', models.CharField(max_length=40, unique=True)),
                ('receipt_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('channel', models.CharField(blank=True, default='', max_length=40)),
                ('bank_reference', models.CharField(blank=True, default='', max_length=80)),
                ('memo', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('POSTED', '已过账'), ('REVERSED', '已冲销')], db_index=True, default='DRAFT', max_length=20)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_receipts', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='baseinfo.owner')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_receipts', to=settings.AUTH_USER_MODEL)),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_receipt', to='billing.paymentreceipt')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_receipts', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.warehouse')),
            ],
            options={
                'verbose_name': '收款单',
                'verbose_name_plural': '收款单',
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('allocated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_reversal', models.BooleanField(default=False)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='billing.bill')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='billing.paymentallocation')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='billing.paymentreceipt')),
            ],
            options={
                'verbose_name': '收款核销分录',
                'verbose_name_plural': '收款核销分录',
            },
        ),
        migrations.CreateModel(
            name='ReceivableCollectionCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', '待跟进'), ('IN_PROGRESS', '跟进中'), ('PROMISED', '已承诺'), ('RESOLVED', '已解决'), ('CLOSED', '已关闭')], default='OPEN', max_length=20)),
                ('next_follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('promised_payment_date', models.DateField(blank=True, null=True)),
                ('promised_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_cases', to=settings.AUTH_USER_MODEL)),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='collection_case', to='billing.bill')),
            ],
            options={
                'permissions': [('manage_collections', '维护应收催收记录')],
            },
        ),
        migrations.CreateModel(
            name='CollectionActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('channel', models.CharField(max_length=40)),
                ('result', models.CharField(max_length=80)),
                ('note', models.TextField(blank=True, default='')),
                ('next_follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='billing.receivablecollectioncase')),
            ],
            options={
                'ordering': ['contacted_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BillingServiceContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_type', models.CharField(choices=[('RECEIVE', '收货'), ('PUTAWAY', '上架/移库入'), ('RELOC', '移库'), ('PICK', '拣货'), ('REVIEW', '复核'), ('PACK', '打包'), ('LOAD', '装车'), ('DISPATCH', '发运/订单处理'), ('COUNT', '盘点'), ('ADJUST', '调整'), ('STORAGE', '仓储/保管')], max_length=20, verbose_name='计费类型')),
                ('calc_method', models.CharField(choices=[('PER_TASK', '按任务'), ('PER_LINE', '按任务行'), ('PER_QTY_BASE', '按基础数量'), ('PER_QTY_ABSDEL', '按数量差额绝对值'), ('PER_ORDER', '按订单'), ('PER_ORDER_LINE', '按订单行'), ('PER_PARCEL', '按包裹件数'), ('PER_DAY_ONHAND_BASE', '按日在库(基础数)'), ('PER_PALLET_DAY', '按托盘位/天'), ('PER_CBM_DAY', '按体积CBM/天'), ('PER_AREA_MONTH', '按面积㎡/月'), ('PERCENT_OF_ORDER_AMOUNT', '按订单金额比例')], max_length=40, verbose_name='计量方式')),
                ('currency', models.CharField(default='CNY', max_length=8, verbose_name='币种')),
                ('effective_from', models.DateField(verbose_name='生效日期')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='失效日期')),
                ('source_type', models.CharField(default='TASK', max_length=40, verbose_name='来源类型')),
                ('billing_timing', models.CharField(default='ON_POSTING', max_length=40, verbose_name='计费时点')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='baseinfo.owner', verbose_name='货主')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.warehouse', verbose_name='仓库')),
            ],
            options={
                'verbose_name': '计费服务合同',
                'verbose_name_plural': '计费服务合同',
                'indexes': [models.Index(fields=['owner', 'warehouse', 'effective_from', 'effective_to'], name='ix_bill_contract_scope_dt')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'warehouse', 'charge_type', 'calc_method', 'currency', 'effective_from'), name='ux_bill_contract_scope_from'), models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='chk_bill_contract_dates')],
            },
        ),
        migrations.AddIndex(
            model_name='paymentreceipt',
            index=models.Index(fields=['owner', 'warehouse', 'currency', 'receipt_date'], name='ix_receipt_scope_date'),
        ),
        migrations.AddConstraint(
            model_name='paymentreceipt',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='chk_receipt_amount_pos'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['bill', 'allocated_at'], name='ix_alloc_bill_time'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='chk_alloc_amount_pos'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.UniqueConstraint(fields=('receipt', 'bill', 'is_reversal'), name='ux_alloc_receipt_bill_side'),
        ),
    ]
