# Generated by Django 5.2.5 on 2026-08-05 20:52

import datetime

from django.db import migrations, models


def backfill_p1_billing(apps, schema_editor):
    Bill = apps.get_model("billing", "Bill")
    PaymentReceipt = apps.get_model("billing", "PaymentReceipt")
    PaymentAllocation = apps.get_model("billing", "PaymentAllocation")
    BillingPeriod = apps.get_model("billing", "BillingPeriod")
    BillingRule = apps.get_model("billing", "BillingRule")
    BillingServiceContract = apps.get_model("billing", "BillingServiceContract")

    Bill.objects.filter(status="DRAFT").update(
        document_status="DRAFT", payment_status="UNPAID"
    )
    Bill.objects.filter(status="ISSUED").update(
        document_status="ISSUED", payment_status="UNPAID"
    )
    Bill.objects.filter(status="VOID").update(
        document_status="VOID", payment_status="UNPAID"
    )
    for bill in Bill.objects.filter(status="PAID").iterator():
        Bill.objects.filter(pk=bill.pk).update(
            document_status="ISSUED", payment_status="PAID"
        )
        if bill.total <= 0:
            continue
        receipt = PaymentReceipt.objects.create(
            owner_id=bill.owner_id,
            warehouse_id=bill.warehouse_id,
            currency=bill.currency or "UNKNOWN",
            receipt_no=f"LEGACY-PAID-{bill.pk}",
            receipt_date=bill.issue_date,
            date_quality="UNKNOWN",
            amount=bill.total,
            channel="LEGACY_PAID",
            memo="历史 PAID 状态合成收款；真实收款日期未知",
            status="POSTED",
        )
        PaymentAllocation.objects.create(
            receipt_id=receipt.pk,
            bill_id=bill.pk,
            amount=bill.total,
            is_reversal=False,
        )

    BillingPeriod.objects.exclude(status="OPEN").update(
        transition_quality="LEGACY_TRANSITION_TIME_UNKNOWN"
    )

    daily_methods = {
        "PER_DAY_ONHAND_BASE",
        "PER_PALLET_DAY",
        "PER_CBM_DAY",
        "PER_AREA_MONTH",
    }
    for rule in BillingRule.objects.filter(
        active=True, owner_id__isnull=False, warehouse_id__isnull=False
    ).iterator():
        effective_from = rule.effective_from or datetime.date(1970, 1, 1)
        overlap = BillingServiceContract.objects.filter(
            owner_id=rule.owner_id,
            warehouse_id=rule.warehouse_id,
            charge_type=rule.charge_type,
            calc_method=rule.calc_method,
            currency=rule.currency or "UNKNOWN",
            effective_from__lte=rule.effective_to or datetime.date.max,
        ).filter(
            models.Q(effective_to__isnull=True)
            | models.Q(effective_to__gte=effective_from)
        )
        if overlap.exclude(effective_from=effective_from).exists():
            raise RuntimeError(
                "Overlapping BillingRule ranges cannot be uniquely converted to "
                f"a service contract; rule_id={rule.pk}."
            )
        BillingServiceContract.objects.get_or_create(
            owner_id=rule.owner_id,
            warehouse_id=rule.warehouse_id,
            charge_type=rule.charge_type,
            calc_method=rule.calc_method,
            currency=rule.currency or "UNKNOWN",
            effective_from=effective_from,
            defaults={
                "effective_to": rule.effective_to,
                "source_type": (
                    "DAILY_METRIC" if rule.calc_method in daily_methods else "TASK"
                ),
                "billing_timing": (
                    "DAILY_CLOSE" if rule.calc_method in daily_methods else "ON_POSTING"
                ),
                "is_active": True,
            },
        )


def noop_reverse(apps, schema_editor):
    # Financial history is intentionally not deleted on migration rollback.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0006_bill_document_status_bill_payment_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentreceipt",
            name="date_quality",
            field=models.CharField(default="VERIFIED", max_length=20),
        ),
        migrations.RunPython(backfill_p1_billing, noop_reverse),
    ]
