# Generated by Django 5.2.5 on 2026-03-29 13:52

import allapp.billing.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0003_alter_carriercompany_warehouse_and_more'),
        ('billing', '0006_remove_billingrule_billing_bil_owner_i_ce8d6b_idx_and_more'),
        ('locations', '0002_alter_container_warehouse_alter_location_warehouse_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='issue_date',
            field=models.DateField(default=allapp.billing.models.bill_issue_date_default, verbose_name='开票日期'),
        ),
        migrations.AddIndex(
            model_name='billingaccrual',
            index=models.Index(fields=['owner', 'warehouse', 'service_date', 'charge_type', 'status'], name='ix_accr_owh_dt_ct_st'),
        ),
        migrations.AddConstraint(
            model_name='billingrule',
            constraint=models.CheckConstraint(condition=models.Q(('min_charge__gte', 0)), name='chk_rule_min_charge_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='billingrule',
            constraint=models.CheckConstraint(condition=models.Q(('cap_amount__isnull', True), ('cap_amount__gte', 0), _connector='OR'), name='chk_rule_cap_amount_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='billingrule',
            constraint=models.CheckConstraint(condition=models.Q(('bundle_price__isnull', True), ('bundle_price__gte', 0), _connector='OR'), name='chk_rule_bundle_price_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='billingruletier',
            constraint=models.CheckConstraint(condition=models.Q(('threshold_from__gte', 0)), name='chk_tier_from_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='billingruletier',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__isnull', True), ('unit_price__gte', 0), _connector='OR'), name='chk_tier_unit_price_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='billingruletier',
            constraint=models.CheckConstraint(condition=models.Q(('percent_rate__isnull', True), models.Q(('percent_rate__gte', 0), ('percent_rate__lte', 1)), _connector='OR'), name='chk_tier_percent_rate_rng'),
        ),
    ]
