# Generated by Django 5.2.5 on 2026-03-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0003_alter_carriercompany_warehouse_and_more'),
        ('billing', '0007_alter_bill_issue_date_and_more'),
        ('locations', '0002_alter_container_warehouse_alter_location_warehouse_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='chk_bill_subtotal_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.CheckConstraint(condition=models.Q(('tax_total__gte', 0)), name='chk_bill_tax_total_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='chk_bill_total_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='billline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='chk_billline_qty_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='billline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='chk_billline_unit_price_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='billline',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='chk_billline_amount_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='billline',
            constraint=models.CheckConstraint(condition=models.Q(('tax_amount__gte', 0)), name='chk_billline_tax_amount_nonneg'),
        ),
    ]
