# Generated by Django 5.2.12 on 2026-04-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0003_alter_carriercompany_warehouse_and_more'),
        ('billing', '0008_bill_chk_bill_subtotal_nonneg_and_more'),
        ('locations', '0002_alter_container_warehouse_alter_location_warehouse_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='billingrule',
            name='chk_rule_price_nonneg',
        ),
        migrations.AlterField(
            model_name='billingrule',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='单价/费率（无阶梯时生效）'),
        ),
        migrations.AddConstraint(
            model_name='billingrule',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__isnull', True), ('unit_price__gte', 0), _connector='OR'), name='chk_rule_price_nonneg'),
        ),
    ]
