# Generated by Django 5.2.12 on 2026-04-08 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0003_alter_carriercompany_warehouse_and_more'),
        ('billing', '0009_allow_null_unit_price'),
        ('locations', '0002_alter_container_warehouse_alter_location_warehouse_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bill',
            name='chk_bill_subtotal_nonneg',
        ),
        migrations.RemoveConstraint(
            model_name='bill',
            name='chk_bill_tax_total_nonneg',
        ),
        migrations.RemoveConstraint(
            model_name='bill',
            name='chk_bill_total_nonneg',
        ),
        migrations.RemoveConstraint(
            model_name='billingaccrual',
            name='chk_amount_nonneg',
        ),
        migrations.RemoveConstraint(
            model_name='billingaccrual',
            name='chk_unit_price_nonneg',
        ),
        migrations.RemoveConstraint(
            model_name='billingaccrual',
            name='chk_tax_amount_nonneg',
        ),
        migrations.RemoveConstraint(
            model_name='billline',
            name='chk_billline_unit_price_nonneg',
        ),
        migrations.RemoveConstraint(
            model_name='billline',
            name='chk_billline_amount_nonneg',
        ),
        migrations.RemoveConstraint(
            model_name='billline',
            name='chk_billline_tax_amount_nonneg',
        ),
        migrations.AddField(
            model_name='billingaccrual',
            name='is_reversal',
            field=models.BooleanField(default=False, verbose_name='是否冲销'),
        ),
        migrations.AddField(
            model_name='billingaccrual',
            name='pre_adjustment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='调整前金额'),
        ),
        migrations.AddField(
            model_name='billingaccrual',
            name='reversal_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='billing.billingaccrual', verbose_name='冲销来源'),
        ),
        migrations.AddConstraint(
            model_name='billingaccrual',
            constraint=models.CheckConstraint(condition=models.Q(('is_reversal', False), ('reversal_of__isnull', False), _connector='OR'), name='chk_reversal_has_ref'),
        ),
    ]
