"""
Django settings for wmsmaster project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/ddd在

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import json
import os
import sys
from datetime import timedelta
from pathlib import Path

import environ
from django.core.exceptions import ImproperlyConfigured

from wmsmaster.environment import is_test_command, load_environment

BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DEBUG=(bool, False),
    ENABLE_DEBUG_TOOLBAR=(bool, True),
    CORS_ALLOW_ALL_ORIGINS=(bool, False),
    LOG_LEVEL=(str, "INFO"),
)

# Local test runs use an isolated, ignored environment file when present.
# Explicit shell/CI variables take priority, followed by the local test file
# and finally the base .env file. Normal development and production commands
# do not load the local test file.
_LOCAL_TEST_ENV = BASE_DIR / ".env.test.local"
load_environment(BASE_DIR / ".env", _LOCAL_TEST_ENV, sys.argv)


def _detect_app_env():
    explicit = env("APP_ENV", default="").strip().lower()
    if explicit:
        return explicit

    if is_test_command(sys.argv):
        return "test"
    return "development"


def _csv_env(name, default=None):
    value = env(name, default=None)
    if value is None:
        return list(default or [])
    if isinstance(value, (list, tuple)):
        return [str(item).strip() for item in value if str(item).strip()]
    return [item.strip() for item in str(value).split(",") if item.strip()]


def _validated_choice(name, value, allowed):
    normalized = str(value).strip().lower()
    if normalized not in allowed:
        choices = "、".join(sorted(allowed))
        raise ImproperlyConfigured(f"{name} 必须是 {choices}。")
    return normalized


def _validated_login_rate(name, default):
    """Return a DRF-style positive rate while failing closed on bad config."""

    value = env(name, default=default).strip().lower()
    try:
        count, period = value.split("/", 1)
        if int(count) <= 0 or period not in {
            "s",
            "sec",
            "second",
            "m",
            "min",
            "minute",
            "h",
            "hour",
            "d",
            "day",
        }:
            raise ValueError
    except (TypeError, ValueError):
        raise ImproperlyConfigured(
            f"{name} 必须是正整数/时间单位，例如 5/min。"
        ) from None
    return value


APP_ENV = _detect_app_env()
if APP_ENV not in {"development", "test", "production"}:
    raise ImproperlyConfigured("APP_ENV 必须是 development、test 或 production。")

IS_DEVELOPMENT = APP_ENV == "development"
IS_TEST = APP_ENV == "test"
IS_PRODUCTION = APP_ENV == "production"

# Replenishment is rolled out in independently observable stages.  Keep every
# behavior-changing stage disabled until the warehouse is audited and ready.
REPLENISHMENT_MANUAL_ENABLED = env.bool("REPLENISHMENT_MANUAL_ENABLED", default=False)
REPLENISHMENT_PDA_ENABLED = env.bool("REPLENISHMENT_PDA_ENABLED", default=False)
REPLENISHMENT_MINMAX_ENABLED = env.bool("REPLENISHMENT_MINMAX_ENABLED", default=False)
REPLENISHMENT_DEMAND_ENABLED = env.bool("REPLENISHMENT_DEMAND_ENABLED", default=False)
RELOCATION_REQUEST_ENABLED = env.bool("RELOCATION_REQUEST_ENABLED", default=False)
RELOCATION_PDA_ENABLED = env.bool("RELOCATION_PDA_ENABLED", default=False)
RELOCATION_CONTAINER_ENABLED = env.bool("RELOCATION_CONTAINER_ENABLED", default=False)
APIZERO_GS1_URL = env(
    "APIZERO_GS1_URL", default="https://v1.apizero.cn/api/barcode-gs1"
)
APIZERO_GS1_TIMEOUT = env.float("APIZERO_GS1_TIMEOUT", default=5.0)
SYSTEM_SETTING_ENCRYPTION_KEY = env(
    "SYSTEM_SETTING_ENCRYPTION_KEY", default=""
).strip()

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY", default="").strip()
if not SECRET_KEY:
    raise ImproperlyConfigured("SECRET_KEY 未配置，服务拒绝启动。")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=IS_DEVELOPMENT)
if IS_PRODUCTION and DEBUG:
    raise ImproperlyConfigured("生产环境必须设置 DEBUG=False。")

# ENABLE_DEBUG_TOOLBAR = (not IS_PRODUCTION) and DEBUG and env.bool(
#     "ENABLE_DEBUG_TOOLBAR",
#     default=IS_DEVELOPMENT,
# )
ENABLE_DEBUG_TOOLBAR = False
# Application definition
INSTALLED_APPS = [
    "allapp.core",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "dal",
    "dal_select2",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "rest_framework.authtoken",
    "corsheaders",
    "django_filters",
    "import_export",
    "django_htmx",
    # 'allapp.tasking',
    "allapp.console",
    "allapp.accounts",
    "allapp.baseinfo",
    "allapp.billing.apps.BillingConfig",
    "allapp.inbound",
    "allapp.inventory.apps.InventoryConfig",
    "allapp.locations",
    "allapp.outbound.apps.OutboundConfig",
    "allapp.products",
    "allapp.pos.apps.PosConfig",
    "allapp.salesapp",
    "allapp.reports",
    "allapp.driverapp",
    "allapp.tasking.apps.TaskingConfig",
    "allapp.strategies",
]

if ENABLE_DEBUG_TOOLBAR:
    INSTALLED_APPS.insert(0, "debug_toolbar")

AUTH_USER_MODEL = "accounts.User"

LOGIN_USERNAME_IP_RATE = _validated_login_rate("LOGIN_USERNAME_IP_RATE", "5/min")
LOGIN_IP_RATE = _validated_login_rate("LOGIN_IP_RATE", "30/min")
LOGIN_TRUSTED_PROXY_COUNT = env.int("LOGIN_TRUSTED_PROXY_COUNT", default=0)
if LOGIN_TRUSTED_PROXY_COUNT < 0:
    raise ImproperlyConfigured("LOGIN_TRUSTED_PROXY_COUNT 不能小于 0。")
LOGIN_THROTTLE_CACHE_ALIAS = "login_throttle"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_FILTER_BACKENDS": (
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ),
}

# （可选）JWT 令牌时效等
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "CHECK_REVOKE_TOKEN": True,
}

WECHAT_MINI_APPID = env("WECHAT_MINI_APPID", default="").strip()
WECHAT_MINI_SECRET = env("WECHAT_MINI_SECRET", default="").strip()
WECHAT_JSCODE2SESSION_URL = env(
    "WECHAT_JSCODE2SESSION_URL",
    default="https://api.weixin.qq.com/sns/jscode2session",
).strip()
WECHAT_PAY_API_BASE_URL = (
    env(
        "WECHAT_PAY_API_BASE_URL",
        default="https://api.mch.weixin.qq.com",
    )
    .strip()
    .rstrip("/")
)
WECHAT_PAY_MCH_ID = env("WECHAT_PAY_MCH_ID", default="").strip()
WECHAT_PAY_MCH_SERIAL_NO = env("WECHAT_PAY_MCH_SERIAL_NO", default="").strip()
WECHAT_PAY_PRIVATE_KEY = env("WECHAT_PAY_PRIVATE_KEY", default="").strip()
WECHAT_PAY_PRIVATE_KEY_PATH = env("WECHAT_PAY_PRIVATE_KEY_PATH", default="").strip()
WECHAT_PAY_APIV3_KEY = env("WECHAT_PAY_APIV3_KEY", default="").strip()
WECHAT_PAY_NOTIFY_URL = env("WECHAT_PAY_NOTIFY_URL", default="").strip()
WECHAT_PAY_REFUND_NOTIFY_URL = env("WECHAT_PAY_REFUND_NOTIFY_URL", default="").strip()
WECHAT_PAY_PLATFORM_PUBLIC_KEY = env(
    "WECHAT_PAY_PLATFORM_PUBLIC_KEY",
    default="",
).strip()
WECHAT_PAY_PLATFORM_PUBLIC_KEY_PATH = env(
    "WECHAT_PAY_PLATFORM_PUBLIC_KEY_PATH",
    default="",
).strip()
try:
    WECHAT_PAY_PLATFORM_KEYS = json.loads(env("WECHAT_PAY_PLATFORM_KEYS", default="{}"))
except (TypeError, ValueError) as exc:
    raise ImproperlyConfigured(
        "WECHAT_PAY_PLATFORM_KEYS 必须是序列号到 PEM 或文件路径的 JSON 对象。"
    ) from exc
if not isinstance(WECHAT_PAY_PLATFORM_KEYS, dict):
    raise ImproperlyConfigured("WECHAT_PAY_PLATFORM_KEYS 必须是 JSON 对象。")
WECHAT_PAY_VERIFY_CALLBACK_SIGNATURE = env.bool(
    "WECHAT_PAY_VERIFY_CALLBACK_SIGNATURE",
    default=IS_PRODUCTION,
)
WECHAT_PAY_CALLBACK_MAX_AGE_SECONDS = env.int(
    "WECHAT_PAY_CALLBACK_MAX_AGE_SECONDS",
    default=300,
)
SALE_MINI_PAY_TIMEOUT_MINUTES = env.int("SALE_MINI_PAY_TIMEOUT_MINUTES", default=30)
SALE_MINI_REFUND_MAX_RETRIES = env.int(
    "SALE_MINI_REFUND_MAX_RETRIES",
    default=6,
)
SALE_MINI_REFUND_QUERY_INTERVAL_MINUTES = env.int(
    "SALE_MINI_REFUND_QUERY_INTERVAL_MINUTES",
    default=5,
)
SALE_MINI_POINT_EXCHANGE_RATE = env("SALE_MINI_POINT_EXCHANGE_RATE", default="100")
SALE_MINI_DISTRIBUTION_COMMISSION_RATE = env(
    "SALE_MINI_DISTRIBUTION_COMMISSION_RATE",
    default="0",
)

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # 放在最上面
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_htmx.middleware.HtmxMiddleware",
]

if ENABLE_DEBUG_TOOLBAR:
    MIDDLEWARE.insert(8, "debug_toolbar.middleware.DebugToolbarMiddleware")

INTERNAL_IPS = (
    _csv_env("INTERNAL_IPS", default=["127.0.0.1"]) if ENABLE_DEBUG_TOOLBAR else []
)

# 允许指定的域访问（修改为你的前端 URL）

CORS_ALLOWED_ORIGINS = _csv_env("CORS_ALLOWED_ORIGINS", default=[])
if IS_PRODUCTION and any(
    not origin.lower().startswith("https://") for origin in CORS_ALLOWED_ORIGINS
):
    raise ImproperlyConfigured("生产环境 CORS_ALLOWED_ORIGINS 只允许 HTTPS 来源。")

# MIDDLEWARE_CLASSES = (
#    'admin_model_list_order.middleware.AdminModelListOrder',
# )
ADMIN_MODEL_DEFAULT_PRIORITY = 100

ROOT_URLCONF = "wmsmaster.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],  # 项目根 templates/
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [],
        },
    },
]

TEMPLATES[0]["OPTIONS"]["context_processors"] = [
    "django.template.context_processors.request",
    "django.contrib.auth.context_processors.auth",
    "django.contrib.messages.context_processors.messages",
]
if DEBUG:
    TEMPLATES[0]["OPTIONS"]["context_processors"].insert(
        0,
        "django.template.context_processors.debug",
    )

WSGI_APPLICATION = "wmsmaster.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DB_ENGINE = env("DB_ENGINE", default="django.db.backends.mysql").strip()
DB_NAME = env("DB_NAME", default="wms_db").strip()

db_options = {}
if DB_ENGINE == "django.db.backends.mysql":
    db_options = {
        "charset": "utf8mb4",  # 避免乱码
        # 如需 SSL，可以在这里加 SSL 相关参数
        # "ssl": {"ca": "/path/to/ca.pem", "cert": "...", "key": "..."},
    }
    db_socket = env("DB_SOCKET", default="")
    if db_socket:
        db_options["unix_socket"] = db_socket

db_test = {}
db_test_name = env("DB_TEST_NAME", default="").strip()
if db_test_name:
    db_test["NAME"] = db_test_name
if DB_ENGINE == "django.db.backends.mysql" and env.bool(
    "DB_TEST_DISABLE_FK_CHECKS", default=False
):
    db_test["OPTIONS"] = {
        "init_command": "SET foreign_key_checks = 0;",
    }

DATABASES = {
    "default": {
        "ENGINE": DB_ENGINE,
        "NAME": DB_NAME,  # 数据库名
        "USER": env("DB_USER", default="wmsuser"),  # MySQL 用户
        "PASSWORD": env("DB_PASSWORD", default=""),  # 密码
        "HOST": env(
            "DB_HOST", default="127.0.0.1"
        ),  # 主机（本机用 localhost 或 127.0.0.1）
        "PORT": env("DB_PORT", default="3306"),  # 端口
        "OPTIONS": db_options,
        "TEST": db_test,
    }
}

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "wms-default",
    },
    LOGIN_THROTTLE_CACHE_ALIAS: {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "wms_login_throttle_cache",
        "TIMEOUT": 60,
        "OPTIONS": {"MAX_ENTRIES": 100000},
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "zh-hans"

TIME_ZONE = "Asia/Shanghai"
USE_TZ = False  # 确保启用时区支持

USE_I18N = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# STATIC_URL = '/static/'
STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]  # 指向外层 /wmsmaster/static
STATIC_ROOT = BASE_DIR / "staticfiles"  # 生产用，开发不影响

LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/admin/"  # 或 'inbound:order_list'
LOGOUT_REDIRECT_URL = "/accounts/login/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOG_LEVEL = env("LOG_LEVEL", default="INFO").upper()

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
    },
    "root": {"handlers": ["console"], "level": LOG_LEVEL},
    # 可选：减少重复
    "loggers": {
        "django.server": {"handlers": ["console"], "level": "INFO", "propagate": False},
    },
}


# 条码解析函数（点路径）
TASKING_BARCODE_RESOLVER = "allapp.tasking.plugins.barcodes.default_resolver"
# 过账处理器（点路径）
TASKING_POSTING_HANDLER = "allapp.tasking.plugins.handlers.DefaultPostingHandler"
# （可选）仅过账已复核通过的扫描
TASKING_POST_ONLY_APPROVED = True
# 可选但强烈建议（避免 PUTAWAY/RECEIVE 无库位）
TASKING_DEFAULT_RECEIVE_LOCATION_ID = 1  # 替换为你“收货暂存位”的ID
TASKING_DEFAULT_PUTAWAY_FROM_LOCATION_ID = 2  # 替换为你“待上架暂存位”的ID

ALLOWED_HOSTS = _csv_env(
    "ALLOWED_HOSTS",
    default=(
        []
        if IS_PRODUCTION
        else ["127.0.0.1", "localhost", "testserver", "192.168.1.128"]
    ),
)
CSRF_TRUSTED_ORIGINS = _csv_env(
    "CSRF_TRUSTED_ORIGINS",
    default=[] if IS_PRODUCTION else ["http://127.0.0.1", "http://localhost"],
)
if IS_PRODUCTION and any(
    not origin.lower().startswith("https://") for origin in CSRF_TRUSTED_ORIGINS
):
    raise ImproperlyConfigured("生产环境 CSRF_TRUSTED_ORIGINS 只允许 HTTPS 来源。")
if IS_PRODUCTION and not ALLOWED_HOSTS:
    raise ImproperlyConfigured("生产环境必须显式配置 ALLOWED_HOSTS。")

SESSION_COOKIE_SECURE = IS_PRODUCTION
CSRF_COOKIE_SECURE = IS_PRODUCTION
SECURE_SSL_REDIRECT = IS_PRODUCTION
SECURE_PROXY_SSL_HEADER = (
    ("HTTP_X_FORWARDED_PROTO", "https")
    if env.bool("TRUST_PROXY_SSL_HEADER", default=IS_PRODUCTION)
    else None
)
SECURE_HSTS_SECONDS = env.int(
    "SECURE_HSTS_SECONDS", default=31536000 if IS_PRODUCTION else 0
)
SECURE_HSTS_INCLUDE_SUBDOMAINS = IS_PRODUCTION and env.bool(
    "SECURE_HSTS_INCLUDE_SUBDOMAINS", default=True
)
SECURE_HSTS_PRELOAD = IS_PRODUCTION and env.bool("SECURE_HSTS_PRELOAD", default=False)
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"

OUTBOUND_ALLOCATE_ON = "OWNER_APPROVE"  # 何时分配：OWNER_APPROVE / WH_APPROVE
OUTBOUND_PICK_TASK_STATUS_ON_APPROVE = "DRAFT"  # 生成的拣货任务初始态
OUTBOUND_ALLOCATE_FIRM_ON_APPROVE = True  # True：硬分配（allocated 冻结）
OUTBOUND_AT_DRAFT_VALIDATE_MODE = "warn"  # "warn" | "block"
OUTBOUND_LEGACY_AUTHZ_MODE = _validated_choice(
    "OUTBOUND_LEGACY_AUTHZ_MODE",
    env("OUTBOUND_LEGACY_AUTHZ_MODE", default="enforce"),
    {"shadow", "enforce"},
)
# Explicit UserRoleScope rows are mandatory by default.  This switch exists only
# for a time-bounded migration rollback and must never be enabled in production.
WMS_ACCESS_SCOPE_LEGACY_FALLBACK = env.bool(
    "WMS_ACCESS_SCOPE_LEGACY_FALLBACK", default=False
)
if IS_PRODUCTION and WMS_ACCESS_SCOPE_LEGACY_FALLBACK:
    raise ImproperlyConfigured("生产环境禁止启用 WMS_ACCESS_SCOPE_LEGACY_FALLBACK。")
COUNT_MAX_TIMES = 2
BILLING_TASKLINE_ORDER_RESOLVER = "allapp.billing.resolvers:taskline_to_order_mapping"
BILLING_METRIC_SCHEDULER_ENABLED = env.bool(
    "BILLING_METRIC_SCHEDULER_ENABLED", default=True
)
BILLING_METRIC_SCHEDULER_HOUR = env.int("BILLING_METRIC_SCHEDULER_HOUR", default=1)
BILLING_METRIC_SCHEDULER_MINUTE = env.int("BILLING_METRIC_SCHEDULER_MINUTE", default=5)
BILLING_METRIC_SCHEDULER_LOOKBACK_DAYS = env.int(
    "BILLING_METRIC_SCHEDULER_LOOKBACK_DAYS", default=3
)
BILLING_METRIC_SCHEDULER_POLL_SECONDS = env.int(
    "BILLING_METRIC_SCHEDULER_POLL_SECONDS", default=60
)
BILLING_METRIC_SCHEDULER_STALE_MINUTES = env.int(
    "BILLING_METRIC_SCHEDULER_STALE_MINUTES", default=180
)
BILLING_METRIC_SCHEDULER_ALLOW_AREA_FALLBACK = env.bool(
    "BILLING_METRIC_SCHEDULER_ALLOW_AREA_FALLBACK", default=False
)
INVENTORY_SNAPSHOT_LOCATION_AREA_RESOLVER = env(
    "INVENTORY_SNAPSHOT_LOCATION_AREA_RESOLVER",
    default="",
)
INVENTORY_FIFO_ENABLED = env.bool("INVENTORY_FIFO_ENABLED", default=False)
TEMPLATES[0]["OPTIONS"]["context_processors"] += [
    "allapp.console.context_processors.console_menu",
]
CORS_ALLOW_ALL_ORIGINS = env.bool("CORS_ALLOW_ALL_ORIGINS", default=False)
if IS_PRODUCTION and CORS_ALLOW_ALL_ORIGINS:
    raise ImproperlyConfigured("生产环境禁止启用 CORS_ALLOW_ALL_ORIGINS。")
# Media文件配置
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# 可选：调整上传文件大小限制
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB

# 必须：给“默认仓库/默认快调库位”设定实际存在的 ID
DEFAULT_WAREHOUSE_ID = 1  # ← 换成你的默认仓库ID
DEFAULT_ADJUST_LOCATION_ID = 1  # ← 换成该仓库下的某个‘调整/暂存’库位ID
